// -------------------------------------------------------------
// 
// File Name: D:\Desktop\Mul_Freq_DUC\2024-Multi-frequency-DUC\matlab\hdlsrc\DUC_1\CIC_Compensation.v
// Created: 2024-10-04 21:47:13
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CIC_Compensation
// Source Path: DUC_1/DUC_AM/DUC_module/CIC Compensation
// Hierarchy Level: 2
// Model version: 3.16
// 
// Discrete FIR Filter
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CIC_Compensation
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En14
  input   validIn;
  output  signed [15:0] dataOut;  // sfix16_En14
  output  validOut;


  wire syncReset;


  assign syncReset = 1'b0;

  Filter FilterBank_1 (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .dataIn(dataIn),  // sfix16_En14
                       .validIn(validIn),
                       .syncReset(syncReset),
                       .dataOut(dataOut),  // sfix16_En14
                       .validOut(validOut)
                       );

endmodule  // CIC_Compensation

