SLStudio.Utils.RemoveHighlighting(get_param('DUC_1', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_DUC_1', 'handle'));
annotate_port('gm_DUC_1/DUC_AM/DUC_module', 0, 1, '');
annotate_port('gm_DUC_1/DUC_AM/DUC_module/CIC Interpolation', 0, 1, '');
annotate_port('gm_DUC_1/DUC_AM/DUC_module/CIC Interpolation/us', 0, 1, '');
annotate_port('gm_DUC_1/DUC_AM/DUC_module/CIC Interpolation/us', 1, 1, '');
annotate_port('DUC_1/DUC_AM/DUC_module/CIC Interpolation', 1, 1, '');
annotate_port('gm_DUC_1/DUC_AM/DUC_module/CIC Interpolation/IS_Section_delay', 1, 1, '');
annotate_port('gm_DUC_1/DUC_AM/DUC_module/CIC Interpolation/IS_Section_add_1', 0, 1, '');
annotate_port('gm_DUC_1/DUC_AM/DUC_module/CIC Interpolation/CS_Section_delay', 0, 1, '');
annotate_port('gm_DUC_1/DUC_AM/DUC_module/CIC Interpolation/CS_Section_sub_4', 0, 1, '');
annotate_port('gm_DUC_1/DUC_AM/DUC_module/CIC Interpolation/CS_Section_sub_3', 0, 1, '');
annotate_port('gm_DUC_1/DUC_AM/DUC_module/CIC Interpolation/CS_Section_sub_2', 0, 1, '');
annotate_port('gm_DUC_1/DUC_AM/DUC_module/CIC Interpolation/CS_Section_sub_1', 0, 1, '');
