open_system('gm_DUC_1');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC_1/DUC&AM/DUC_module', 'user2');
annotate_port('gm_DUC_1/DUC&AM/DUC_module', 0, 1, 'cp : 14.151 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation', 'user2');
annotate_port('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation', 0, 1, 'cp : 14.151 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/us', 'user2');
annotate_port('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/us', 0, 1, 'cp : 11.129 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/IS_Section_delay', 'user1');
annotate_port('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/IS_Section_delay', 1, 1, 'cp : 14.151 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/IS_Section_add_1', 'user2');
annotate_port('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/IS_Section_add_1', 0, 1, 'cp : 13.941 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/CS_Section_delay', 'user1');
annotate_port('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/CS_Section_delay', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/CS_Section_sub_4', 'user2');
annotate_port('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/CS_Section_sub_4', 0, 1, 'cp : 10.903 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/CS_Section_sub_3', 'user2');
annotate_port('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/CS_Section_sub_3', 0, 1, 'cp : 8.091 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/CS_Section_sub_2', 'user2');
annotate_port('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/CS_Section_sub_2', 0, 1, 'cp : 5.279 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/CS_Section_sub_1', 'user2');
annotate_port('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/CS_Section_sub_1', 0, 1, 'cp : 2.669 ns');
