vlib work
vlog  DUC_AM_tc.v
vlog  CIC_Interpolation.v
vlog  FilterCoef.v
vlog  FilterTapSystolicPreAddWvlIn.v
vlog  subFilter.v
vlog  Filter.v
vlog  CIC_Compensation.v
vlog  FilterCoef_block.v
vlog  FilterTapSystolicPreAddWvlIn_block.v
vlog  FilterTapSystolicWvldInC0.v
vlog  subFilter_block.v
vlog  Filter_block.v
vlog  Halfband.v
vlog  FilterCoef_block1.v
vlog  FilterTapSystolicPreAddWvlIn_block1.v
vlog  subFilter_block1.v
vlog  Filter_block1.v
vlog  Lowpass.v
vlog  DitherGen.v
vlog  Lookup_Table.v
vlog  LookUpTableGen.v
vlog  WaveformGen.v
vlog  NCO.v
vlog  DUC_module.v
vlog  DitherGen_block.v
vlog  Lookup_Table_block.v
vlog  LookUpTableGen_block.v
vlog  WaveformGen_block.v
vlog  NCO_block.v
vlog  DUC_AM.v
