open_system('DUC_1');
open_system('gm_DUC_1');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/us', 'user2');
annotate_port('gm_DUC_1/DUC&AM/DUC_module/CIC Interpolation/us', 1, 1, '时钟频率流水线的障碍');
hilite_system('DUC_1/DUC&AM/DUC_module/CIC Interpolation', 'user2');
annotate_port('DUC_1/DUC&AM/DUC_module/CIC Interpolation', 1, 1, '时钟频率流水线的障碍');
