// -------------------------------------------------------------
// 
// File Name: D:\Desktop\Mul_Freq_DUC\2024-Multi-frequency-DUC\matlab\hdlsrc\DUC_1\LookUpTableGen.v
// Created: 2024-10-04 21:47:14
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LookUpTableGen
// Source Path: DUC_1/DUC_AM/DUC_module/NCO/WaveformGen/LookUpTableGen
// Hierarchy Level: 4
// Model version: 3.16
// 
// Look Up Table Generation Component
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LookUpTableGen
          (clk,
           reset,
           enb,
           lutaddr,
           lutoutput);


  input   clk;
  input   reset;
  input   enb;
  input   [10:0] lutaddr;  // ufix11
  output  signed [15:0] lutoutput;  // sfix16_En14


  reg [10:0] lutaddrInReg;  // ufix11
  wire signed [15:0] lutout;  // sfix16_En14
  reg signed [15:0] lutout_reg;  // sfix16_En14
  reg signed [15:0] lutoutput_1;  // sfix16_En14

  initial begin
    lutaddrInReg = 11'b00000000000;
    lutout_reg = 16'sb0000000000000000;
  end

  // Look up table address input register
  always @(posedge clk)
    begin : LUTaddrRegister_process
      if (enb) begin
        lutaddrInReg <= lutaddr;
      end
    end

  // Quarter sine wave table
  Lookup_Table Lookup_Table_1_1 (.in1(lutaddrInReg),  // ufix11
                                 .out_rsvd(lutout)  // sfix16_En14
                                 );

  // Lookup table output register
  always @(posedge clk)
    begin : LUToutResetRegister_process
      if (enb) begin
        lutout_reg <= lutout;
      end
    end

  always @(posedge clk)
    begin : LUToutRegister_process
      if (reset == 1'b0) begin
        lutoutput_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          lutoutput_1 <= lutout_reg;
        end
      end
    end

  assign lutoutput = lutoutput_1;

endmodule  // LookUpTableGen

