// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC_1\subFilter_block1.v
// Created: 2024-09-16 20:54:07
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: subFilter_block1
// Source Path: DUC_1/DUC&AM/DUC_module/Lowpass/Filter/subFilter
// Hierarchy Level: 4
// Model version: 3.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module subFilter_block1
          (clk,
           reset,
           enb,
           dinReg2_0_re,
           coefIn_0,
           coefIn_1,
           coefIn_2,
           coefIn_3,
           coefIn_4,
           coefIn_5,
           coefIn_6,
           coefIn_7,
           coefIn_8,
           coefIn_9,
           coefIn_10,
           coefIn_11,
           coefIn_12,
           coefIn_13,
           dinRegVld,
           syncReset,
           dout_1_re,
           doutVld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dinReg2_0_re;  // sfix16_En14
  input   signed [15:0] coefIn_0;  // sfix16_En15
  input   signed [15:0] coefIn_1;  // sfix16_En15
  input   signed [15:0] coefIn_2;  // sfix16_En15
  input   signed [15:0] coefIn_3;  // sfix16_En15
  input   signed [15:0] coefIn_4;  // sfix16_En15
  input   signed [15:0] coefIn_5;  // sfix16_En15
  input   signed [15:0] coefIn_6;  // sfix16_En15
  input   signed [15:0] coefIn_7;  // sfix16_En15
  input   signed [15:0] coefIn_8;  // sfix16_En15
  input   signed [15:0] coefIn_9;  // sfix16_En15
  input   signed [15:0] coefIn_10;  // sfix16_En15
  input   signed [15:0] coefIn_11;  // sfix16_En15
  input   signed [15:0] coefIn_12;  // sfix16_En15
  input   signed [15:0] coefIn_13;  // sfix16_En15
  input   dinRegVld;
  input   syncReset;
  output  signed [15:0] dout_1_re;  // sfix16_En14
  output  doutVld;


  reg  [17:0] intdelay_reg;  // ufix1 [18]
  wire vldShift;
  wire vldOutTmp;
  wire signed [15:0] ZERO_OUT;  // sfix16_En14
  wire signed [43:0] addin;  // sfix44_En29
  wire signed [15:0] dinDly2;  // sfix16_En14
  wire signed [15:0] dinDly2_1;  // sfix16_En14
  wire signed [43:0] tapout;  // sfix44_En29
  wire signed [15:0] dinDly2_2;  // sfix16_En14
  wire signed [43:0] tapout_1;  // sfix44_En29
  wire signed [15:0] dinDly2_3;  // sfix16_En14
  wire signed [43:0] tapout_2;  // sfix44_En29
  wire signed [15:0] dinDly2_4;  // sfix16_En14
  wire signed [43:0] tapout_3;  // sfix44_En29
  wire signed [15:0] dinDly2_5;  // sfix16_En14
  wire signed [43:0] tapout_4;  // sfix44_En29
  wire signed [15:0] dinDly2_6;  // sfix16_En14
  wire signed [43:0] tapout_5;  // sfix44_En29
  wire signed [15:0] dinDly2_7;  // sfix16_En14
  wire signed [43:0] tapout_6;  // sfix44_En29
  wire signed [15:0] dinDly2_8;  // sfix16_En14
  wire signed [43:0] tapout_7;  // sfix44_En29
  wire signed [15:0] dinDly2_9;  // sfix16_En14
  wire signed [43:0] tapout_8;  // sfix44_En29
  wire signed [15:0] dinDly2_10;  // sfix16_En14
  wire signed [43:0] tapout_9;  // sfix44_En29
  wire signed [15:0] dinDly2_11;  // sfix16_En14
  wire signed [43:0] tapout_10;  // sfix44_En29
  wire signed [15:0] dinDly2_12;  // sfix16_En14
  wire signed [43:0] tapout_11;  // sfix44_En29
  wire signed [15:0] dinDly2_13;  // sfix16_En14
  wire signed [43:0] tapout_12;  // sfix44_En29
  wire signed [43:0] tapout_13;  // sfix44_En29
  reg signed [43:0] foutDly;  // sfix44_En29
  wire signed [15:0] dout_cast;  // sfix16_En14
  wire signed [15:0] muxOut;  // sfix16_En14
  reg signed [15:0] dout_1_re_1;  // sfix16_En14
  reg  doutVld_1;


  always @(posedge clk or negedge reset)
    begin : intdelay_process
      if (reset == 1'b0) begin
        intdelay_reg <= {18{1'b0}};
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            intdelay_reg <= {18{1'b0}};
          end
          else begin
            if (dinRegVld) begin
              intdelay_reg[0] <= dinRegVld;
              intdelay_reg[32'sd17:32'sd1] <= intdelay_reg[32'sd16:32'sd0];
            end
          end
        end
      end
    end

  assign vldShift = intdelay_reg[17];

  assign vldOutTmp = dinRegVld & vldShift;

  assign ZERO_OUT = 16'sb0000000000000000;

  assign addin = 44'sh00000000000;

  FilterTapSystolicPreAddWvlIn_block1 u_FilterTap_1 (.clk(clk),
                                                     .enb(enb),
                                                     .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                     .dinPreAdd(dinDly2),  // sfix16_En14
                                                     .coefIn_0(coefIn_0),  // sfix16_En15
                                                     .addin(addin),  // sfix44_En29
                                                     .dinRegVld(dinRegVld),
                                                     .syncReset(syncReset),
                                                     .dinDly2(dinDly2_1),  // sfix16_En14
                                                     .tapout(tapout)  // sfix44_En29
                                                     );

  FilterTapSystolicPreAddWvlIn_block1 u_FilterTap_2 (.clk(clk),
                                                     .enb(enb),
                                                     .dinReg2_0_re(dinDly2_1),  // sfix16_En14
                                                     .dinPreAdd(dinDly2),  // sfix16_En14
                                                     .coefIn_0(coefIn_1),  // sfix16_En15
                                                     .addin(tapout),  // sfix44_En29
                                                     .dinRegVld(dinRegVld),
                                                     .syncReset(syncReset),
                                                     .dinDly2(dinDly2_2),  // sfix16_En14
                                                     .tapout(tapout_1)  // sfix44_En29
                                                     );

  FilterTapSystolicPreAddWvlIn_block1 u_FilterTap_3 (.clk(clk),
                                                     .enb(enb),
                                                     .dinReg2_0_re(dinDly2_2),  // sfix16_En14
                                                     .dinPreAdd(dinDly2),  // sfix16_En14
                                                     .coefIn_0(coefIn_2),  // sfix16_En15
                                                     .addin(tapout_1),  // sfix44_En29
                                                     .dinRegVld(dinRegVld),
                                                     .syncReset(syncReset),
                                                     .dinDly2(dinDly2_3),  // sfix16_En14
                                                     .tapout(tapout_2)  // sfix44_En29
                                                     );

  FilterTapSystolicPreAddWvlIn_block1 u_FilterTap_4 (.clk(clk),
                                                     .enb(enb),
                                                     .dinReg2_0_re(dinDly2_3),  // sfix16_En14
                                                     .dinPreAdd(dinDly2),  // sfix16_En14
                                                     .coefIn_0(coefIn_3),  // sfix16_En15
                                                     .addin(tapout_2),  // sfix44_En29
                                                     .dinRegVld(dinRegVld),
                                                     .syncReset(syncReset),
                                                     .dinDly2(dinDly2_4),  // sfix16_En14
                                                     .tapout(tapout_3)  // sfix44_En29
                                                     );

  FilterTapSystolicPreAddWvlIn_block1 u_FilterTap_5 (.clk(clk),
                                                     .enb(enb),
                                                     .dinReg2_0_re(dinDly2_4),  // sfix16_En14
                                                     .dinPreAdd(dinDly2),  // sfix16_En14
                                                     .coefIn_0(coefIn_4),  // sfix16_En15
                                                     .addin(tapout_3),  // sfix44_En29
                                                     .dinRegVld(dinRegVld),
                                                     .syncReset(syncReset),
                                                     .dinDly2(dinDly2_5),  // sfix16_En14
                                                     .tapout(tapout_4)  // sfix44_En29
                                                     );

  FilterTapSystolicPreAddWvlIn_block1 u_FilterTap_6 (.clk(clk),
                                                     .enb(enb),
                                                     .dinReg2_0_re(dinDly2_5),  // sfix16_En14
                                                     .dinPreAdd(dinDly2),  // sfix16_En14
                                                     .coefIn_0(coefIn_5),  // sfix16_En15
                                                     .addin(tapout_4),  // sfix44_En29
                                                     .dinRegVld(dinRegVld),
                                                     .syncReset(syncReset),
                                                     .dinDly2(dinDly2_6),  // sfix16_En14
                                                     .tapout(tapout_5)  // sfix44_En29
                                                     );

  FilterTapSystolicPreAddWvlIn_block1 u_FilterTap_7 (.clk(clk),
                                                     .enb(enb),
                                                     .dinReg2_0_re(dinDly2_6),  // sfix16_En14
                                                     .dinPreAdd(dinDly2),  // sfix16_En14
                                                     .coefIn_0(coefIn_6),  // sfix16_En15
                                                     .addin(tapout_5),  // sfix44_En29
                                                     .dinRegVld(dinRegVld),
                                                     .syncReset(syncReset),
                                                     .dinDly2(dinDly2_7),  // sfix16_En14
                                                     .tapout(tapout_6)  // sfix44_En29
                                                     );

  FilterTapSystolicPreAddWvlIn_block1 u_FilterTap_8 (.clk(clk),
                                                     .enb(enb),
                                                     .dinReg2_0_re(dinDly2_7),  // sfix16_En14
                                                     .dinPreAdd(dinDly2),  // sfix16_En14
                                                     .coefIn_0(coefIn_7),  // sfix16_En15
                                                     .addin(tapout_6),  // sfix44_En29
                                                     .dinRegVld(dinRegVld),
                                                     .syncReset(syncReset),
                                                     .dinDly2(dinDly2_8),  // sfix16_En14
                                                     .tapout(tapout_7)  // sfix44_En29
                                                     );

  FilterTapSystolicPreAddWvlIn_block1 u_FilterTap_9 (.clk(clk),
                                                     .enb(enb),
                                                     .dinReg2_0_re(dinDly2_8),  // sfix16_En14
                                                     .dinPreAdd(dinDly2),  // sfix16_En14
                                                     .coefIn_0(coefIn_8),  // sfix16_En15
                                                     .addin(tapout_7),  // sfix44_En29
                                                     .dinRegVld(dinRegVld),
                                                     .syncReset(syncReset),
                                                     .dinDly2(dinDly2_9),  // sfix16_En14
                                                     .tapout(tapout_8)  // sfix44_En29
                                                     );

  FilterTapSystolicPreAddWvlIn_block1 u_FilterTap_10 (.clk(clk),
                                                      .enb(enb),
                                                      .dinReg2_0_re(dinDly2_9),  // sfix16_En14
                                                      .dinPreAdd(dinDly2),  // sfix16_En14
                                                      .coefIn_0(coefIn_9),  // sfix16_En15
                                                      .addin(tapout_8),  // sfix44_En29
                                                      .dinRegVld(dinRegVld),
                                                      .syncReset(syncReset),
                                                      .dinDly2(dinDly2_10),  // sfix16_En14
                                                      .tapout(tapout_9)  // sfix44_En29
                                                      );

  FilterTapSystolicPreAddWvlIn_block1 u_FilterTap_11 (.clk(clk),
                                                      .enb(enb),
                                                      .dinReg2_0_re(dinDly2_10),  // sfix16_En14
                                                      .dinPreAdd(dinDly2),  // sfix16_En14
                                                      .coefIn_0(coefIn_10),  // sfix16_En15
                                                      .addin(tapout_9),  // sfix44_En29
                                                      .dinRegVld(dinRegVld),
                                                      .syncReset(syncReset),
                                                      .dinDly2(dinDly2_11),  // sfix16_En14
                                                      .tapout(tapout_10)  // sfix44_En29
                                                      );

  FilterTapSystolicPreAddWvlIn_block1 u_FilterTap_12 (.clk(clk),
                                                      .enb(enb),
                                                      .dinReg2_0_re(dinDly2_11),  // sfix16_En14
                                                      .dinPreAdd(dinDly2),  // sfix16_En14
                                                      .coefIn_0(coefIn_11),  // sfix16_En15
                                                      .addin(tapout_10),  // sfix44_En29
                                                      .dinRegVld(dinRegVld),
                                                      .syncReset(syncReset),
                                                      .dinDly2(dinDly2_12),  // sfix16_En14
                                                      .tapout(tapout_11)  // sfix44_En29
                                                      );

  FilterTapSystolicPreAddWvlIn_block1 u_FilterTap_13 (.clk(clk),
                                                      .enb(enb),
                                                      .dinReg2_0_re(dinDly2_12),  // sfix16_En14
                                                      .dinPreAdd(dinDly2),  // sfix16_En14
                                                      .coefIn_0(coefIn_12),  // sfix16_En15
                                                      .addin(tapout_11),  // sfix44_En29
                                                      .dinRegVld(dinRegVld),
                                                      .syncReset(syncReset),
                                                      .dinDly2(dinDly2_13),  // sfix16_En14
                                                      .tapout(tapout_12)  // sfix44_En29
                                                      );

  FilterTapSystolicPreAddWvlIn_block1 u_FilterTap_14 (.clk(clk),
                                                      .enb(enb),
                                                      .dinReg2_0_re(dinDly2_13),  // sfix16_En14
                                                      .dinPreAdd(dinDly2),  // sfix16_En14
                                                      .coefIn_0(coefIn_13),  // sfix16_En15
                                                      .addin(tapout_12),  // sfix44_En29
                                                      .dinRegVld(dinRegVld),
                                                      .syncReset(syncReset),
                                                      .dinDly2(dinDly2),  // sfix16_En14
                                                      .tapout(tapout_13)  // sfix44_En29
                                                      );

  always @(posedge clk or negedge reset)
    begin : intdelay_1_process
      if (reset == 1'b0) begin
        foutDly <= 44'sh00000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            foutDly <= 44'sh00000000000;
          end
          else begin
            if (dinRegVld) begin
              foutDly <= tapout_13;
            end
          end
        end
      end
    end

  assign dout_cast = foutDly[30:15];

  assign muxOut = (vldOutTmp == 1'b0 ? ZERO_OUT :
              dout_cast);

  always @(posedge clk or negedge reset)
    begin : intdelay_2_process
      if (reset == 1'b0) begin
        dout_1_re_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dout_1_re_1 <= 16'sb0000000000000000;
          end
          else begin
            dout_1_re_1 <= muxOut;
          end
        end
      end
    end

  always @(posedge clk or negedge reset)
    begin : intdelay_3_process
      if (reset == 1'b0) begin
        doutVld_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            doutVld_1 <= 1'b0;
          end
          else begin
            doutVld_1 <= vldOutTmp;
          end
        end
      end
    end

  assign dout_1_re = dout_1_re_1;

  assign doutVld = doutVld_1;

endmodule  // subFilter_block1

