function Hd = non_sinc
%NON_SINC 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 24.2 and DSP System Toolbox 24.2.
% Generated on: 09-Mar-2025 16:36:07

% FIR constrained equiripple Inverse Sinc Lowpass filter designed using
% the FIRCEQRIP function.

% All frequency values are normalized to 1.

N            = 15;              % Order
Fc           = 0.5;             % Cutoff Frequency
slope        = 1;               % Stopband Slope
isincffactor = 1;               % Inverse Sinc Frequency Factor
isincpower   = 1;               % Inverse Sinc Power
Dstop        = 0.001;           % Stopband Attenuation
Dpass        = 0.057501127785;  % Passband Ripple

% Calculate the coefficients using the FIRCEQRIP function.
b  = firceqrip(N, Fc, [Dpass, Dstop], 'slope', slope, 'min', 'invsinc', ...
               [isincffactor isincpower]);
Hd = dfilt.dffir(b);

% [EOF]
