// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC\Filter_block.v
// Created: 2025-01-05 17:57:41
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Filter_block
// Source Path: DUC/DUC_module/Halfband Filter 2/Filter
// Hierarchy Level: 2
// Model version: 3.21
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Filter_block
          (clk,
           rst_n,
           enb,
           dataIn,
           validIn,
           syncReset,
           dataOut,
           validOut);


  input   clk;
  input   rst_n;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  input   syncReset;
  output  signed [15:0] dataOut;  // sfix16_En15
  output  validOut;


  reg  dinRegVld;
  reg signed [15:0] dinReg_0_re;  // sfix16_En15
  reg signed [15:0] dinReg2_0_re;  // sfix16_En15
  wire signed [15:0] CoefOut_1;  // sfix16_En15
  wire signed [15:0] CoefOut_3;  // sfix16_En15
  wire signed [15:0] CoefOut_5;  // sfix16_En15
  wire signed [15:0] CoefOut_7;  // sfix16_En15
  wire signed [15:0] CoefOut_9;  // sfix16_En15
  wire signed [15:0] CoefOut_11;  // sfix16_En15
  wire signed [15:0] CoefOut_13;  // sfix16_En15
  wire signed [15:0] CoefOut_15;  // sfix16_En15
  wire signed [15:0] CoefOut_17;  // sfix16_En15
  wire signed [15:0] CoefOut_19;  // sfix16_En15
  wire signed [15:0] CoefOut_21;  // sfix16_En15
  wire signed [15:0] CoefOut_23;  // sfix16_En15
  wire signed [15:0] CoefOut_24;  // sfix16_En15
  reg  dinReg2Vld;
  wire signed [15:0] dout_1_re;  // sfix16_En15
  wire doutVld;


  always @(posedge clk)
    begin : intdelay_process
      if (rst_n == 1'b0) begin
        dinRegVld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinRegVld <= 1'b0;
          end
          else begin
            dinRegVld <= validIn;
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_1_process
      if (rst_n == 1'b0) begin
        dinReg_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_re <= dataIn;
            end
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_2_process
      if (rst_n == 1'b0) begin
        dinReg2_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_re <= dinReg_0_re;
            end
          end
        end
      end
    end

  FilterCoef_block u_CoefTable_1 (.CoefOut_1(CoefOut_1),  // sfix16_En15
                                  .CoefOut_3(CoefOut_3),  // sfix16_En15
                                  .CoefOut_5(CoefOut_5),  // sfix16_En15
                                  .CoefOut_7(CoefOut_7),  // sfix16_En15
                                  .CoefOut_9(CoefOut_9),  // sfix16_En15
                                  .CoefOut_11(CoefOut_11),  // sfix16_En15
                                  .CoefOut_13(CoefOut_13),  // sfix16_En15
                                  .CoefOut_15(CoefOut_15),  // sfix16_En15
                                  .CoefOut_17(CoefOut_17),  // sfix16_En15
                                  .CoefOut_19(CoefOut_19),  // sfix16_En15
                                  .CoefOut_21(CoefOut_21),  // sfix16_En15
                                  .CoefOut_23(CoefOut_23),  // sfix16_En15
                                  .CoefOut_24(CoefOut_24)  // sfix16_En15
                                  );

  always @(posedge clk)
    begin : intdelay_3_process
      if (rst_n == 1'b0) begin
        dinReg2Vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2Vld <= 1'b0;
          end
          else begin
            dinReg2Vld <= dinRegVld;
          end
        end
      end
    end

  subFilter_block u_subFilter_1_re (.clk(clk),
                                    .rst_n(rst_n),
                                    .enb(enb),
                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En15
                                    .coefIn_1(CoefOut_1),  // sfix16_En15
                                    .coefIn_3(CoefOut_3),  // sfix16_En15
                                    .coefIn_5(CoefOut_5),  // sfix16_En15
                                    .coefIn_7(CoefOut_7),  // sfix16_En15
                                    .coefIn_9(CoefOut_9),  // sfix16_En15
                                    .coefIn_11(CoefOut_11),  // sfix16_En15
                                    .coefIn_13(CoefOut_13),  // sfix16_En15
                                    .coefIn_15(CoefOut_15),  // sfix16_En15
                                    .coefIn_17(CoefOut_17),  // sfix16_En15
                                    .coefIn_19(CoefOut_19),  // sfix16_En15
                                    .coefIn_21(CoefOut_21),  // sfix16_En15
                                    .coefIn_23(CoefOut_23),  // sfix16_En15
                                    .coefIn_24(CoefOut_24),  // sfix16_En15
                                    .dinRegVld(dinReg2Vld),
                                    .syncReset(syncReset),
                                    .dout_1_re(dout_1_re),  // sfix16_En15
                                    .doutVld(doutVld)
                                    );

  assign dataOut = dout_1_re;

  assign validOut = doutVld;

endmodule  // Filter_block

