# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/DUC_AM_9767.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_processing_system7_0_0 || ORIG_REF_NAME==top_processing_system7_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_gpio_0_0/top_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_gpio_0_0 || ORIG_REF_NAME==top_axi_gpio_0_0} -quiet] -quiet

# IP: bd/top/ip/top_ps7_0_axi_periph_0/top_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ps7_0_axi_periph_0 || ORIG_REF_NAME==top_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_ps7_0_120M_0/top_rst_ps7_0_120M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_ps7_0_120M_0 || ORIG_REF_NAME==top_rst_ps7_0_120M_0} -quiet] -quiet

# IP: bd/top/ip/top_util_vector_logic_0_2/top_util_vector_logic_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_util_vector_logic_0_2 || ORIG_REF_NAME==top_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/top/ip/top_util_vector_logic_0_3/top_util_vector_logic_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_util_vector_logic_0_3 || ORIG_REF_NAME==top_util_vector_logic_0_3} -quiet] -quiet

# IP: bd/top/ip/top_Signal_Source_module_0_4/top_Signal_Source_module_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_Signal_Source_module_0_4 || ORIG_REF_NAME==top_Signal_Source_module_0_4} -quiet] -quiet

# IP: bd/top/ip/top_DUC_module_0_3/top_DUC_module_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_DUC_module_0_3 || ORIG_REF_NAME==top_DUC_module_0_3} -quiet] -quiet

# IP: bd/top/ip/top_DAC_module_0_0/top_DAC_module_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_DAC_module_0_0 || ORIG_REF_NAME==top_DAC_module_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_0_2/top_xlconstant_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_0_2 || ORIG_REF_NAME==top_xlconstant_0_2} -quiet] -quiet

# IP: bd/top/ip/top_DAC_module_0_1/top_DAC_module_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_DAC_module_0_1 || ORIG_REF_NAME==top_DAC_module_0_1} -quiet] -quiet

# IP: bd/top/ip/top_util_vector_logic_1_0/top_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_util_vector_logic_1_0 || ORIG_REF_NAME==top_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/top/ip/top_util_vector_logic_1_1/top_util_vector_logic_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_util_vector_logic_1_1 || ORIG_REF_NAME==top_util_vector_logic_1_1} -quiet] -quiet

# IP: bd/top/ip/top_AM_module_0_4/top_AM_module_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_AM_module_0_4 || ORIG_REF_NAME==top_AM_module_0_4} -quiet] -quiet

# IP: bd/top/ip/top_util_vector_logic_3_0/top_util_vector_logic_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_util_vector_logic_3_0 || ORIG_REF_NAME==top_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_0/top_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_0 || ORIG_REF_NAME==top_auto_pc_0} -quiet] -quiet

# XDC: d:/Desktop/Mul_Freq_DUC/2024-Multi-frequency-DUC/vivado/DUC_AM_ZYNQ/DUC_AM_ZYNQ.gen/sources_1/bd/top/top_ooc.xdc
