// -------------------------------------------------------------
// 
// File Name: D:\Desktop\Mul_Freq_DUC\2024-Multi-frequency-DUC\matlab\codegen\hdl_IP\hdlsrc\bSection.v
// Created: 2024-10-31 17:07:43
// 
// Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: bSection
// Source Path: hdl_IP/Upsampler/bSection
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module bSection
          (clk,
           reset,
           enb,
           usOut1_re_0,
           usOut1_re_1,
           usOut1_re_2,
           usOut1_im_0,
           usOut1_im_1,
           usOut1_im_2,
           us_vout1,
           internalReset,
           usOut_re_0,
           usOut_re_1,
           usOut_re_2,
           usOut_im_0,
           usOut_im_1,
           usOut_im_2,
           us_vout);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] usOut1_re_0;  // sfix16_En14
  input   signed [15:0] usOut1_re_1;  // sfix16_En14
  input   signed [15:0] usOut1_re_2;  // sfix16_En14
  input   signed [15:0] usOut1_im_0;  // sfix16_En14
  input   signed [15:0] usOut1_im_1;  // sfix16_En14
  input   signed [15:0] usOut1_im_2;  // sfix16_En14
  input   us_vout1;
  input   internalReset;
  output  signed [15:0] usOut_re_0;  // sfix16_En14
  output  signed [15:0] usOut_re_1;  // sfix16_En14
  output  signed [15:0] usOut_re_2;  // sfix16_En14
  output  signed [15:0] usOut_im_0;  // sfix16_En14
  output  signed [15:0] usOut_im_1;  // sfix16_En14
  output  signed [15:0] usOut_im_2;  // sfix16_En14
  output  us_vout;


  wire signed [15:0] usOut1_re [0:2];  // sfix16_En14 [3]
  wire signed [15:0] usOut1_im [0:2];  // sfix16_En14 [3]
  reg signed [15:0] bufferSectionVecOut_buffreg_re [0:2];  // sfix16 [3]
  reg signed [15:0] bufferSectionVecOut_buffreg_im [0:2];  // sfix16 [3]
  reg  bufferSectionVecOut_buffstate;
  reg signed [15:0] bufferSectionVecOut_buffreg_re_next [0:2];  // sfix16_En14 [3]
  reg signed [15:0] bufferSectionVecOut_buffreg_im_next [0:2];  // sfix16_En14 [3]
  reg  bufferSectionVecOut_buffstate_next;
  reg signed [15:0] usOut_re [0:2];  // sfix16_En14 [3]
  reg signed [15:0] usOut_im [0:2];  // sfix16_En14 [3]
  reg  us_vout_1;
  reg signed [31:0] bufferSectionVecOut_t_0_0;  // int32
  reg signed [31:0] bufferSectionVecOut_t_1;  // int32
  reg signed [31:0] bufferSectionVecOut_t_2_0;  // int32
  reg signed [31:0] bufferSectionVecOut_t_0_1;  // int32


  assign usOut1_re[0] = usOut1_re_0;
  assign usOut1_re[1] = usOut1_re_1;
  assign usOut1_re[2] = usOut1_re_2;

  assign usOut1_im[0] = usOut1_im_0;
  assign usOut1_im[1] = usOut1_im_1;
  assign usOut1_im[2] = usOut1_im_2;

  always @(posedge clk)
    begin : bufferSectionVecOut_process
      if (reset == 1'b0) begin
        bufferSectionVecOut_buffreg_re[0] <= 16'sb0000000000000000;
        bufferSectionVecOut_buffreg_im[0] <= 16'sb0000000000000000;
        bufferSectionVecOut_buffreg_re[1] <= 16'sb0000000000000000;
        bufferSectionVecOut_buffreg_im[1] <= 16'sb0000000000000000;
        bufferSectionVecOut_buffreg_re[2] <= 16'sb0000000000000000;
        bufferSectionVecOut_buffreg_im[2] <= 16'sb0000000000000000;
        bufferSectionVecOut_buffstate <= 1'b0;
      end
      else begin
        if (enb) begin

          for(bufferSectionVecOut_t_0_1 = 32'sd0; bufferSectionVecOut_t_0_1 <= 32'sd2; bufferSectionVecOut_t_0_1 = bufferSectionVecOut_t_0_1 + 32'sd1) begin
            bufferSectionVecOut_buffreg_re[bufferSectionVecOut_t_0_1] <= bufferSectionVecOut_buffreg_re_next[bufferSectionVecOut_t_0_1];
            bufferSectionVecOut_buffreg_im[bufferSectionVecOut_t_0_1] <= bufferSectionVecOut_buffreg_im_next[bufferSectionVecOut_t_0_1];
          end

          bufferSectionVecOut_buffstate <= bufferSectionVecOut_buffstate_next;
        end
      end
    end

  always @* begin

    for(bufferSectionVecOut_t_0_0 = 32'sd0; bufferSectionVecOut_t_0_0 <= 32'sd2; bufferSectionVecOut_t_0_0 = bufferSectionVecOut_t_0_0 + 32'sd1) begin
      bufferSectionVecOut_buffreg_re_next[bufferSectionVecOut_t_0_0] = bufferSectionVecOut_buffreg_re[bufferSectionVecOut_t_0_0];
      bufferSectionVecOut_buffreg_im_next[bufferSectionVecOut_t_0_0] = bufferSectionVecOut_buffreg_im[bufferSectionVecOut_t_0_0];
    end

    if (us_vout1 != 1'b0) begin
      for(bufferSectionVecOut_t_1 = 32'sd0; bufferSectionVecOut_t_1 <= 32'sd2; bufferSectionVecOut_t_1 = bufferSectionVecOut_t_1 + 32'sd1) begin
        bufferSectionVecOut_buffreg_re_next[bufferSectionVecOut_t_1] = usOut1_re[bufferSectionVecOut_t_1];
        bufferSectionVecOut_buffreg_im_next[bufferSectionVecOut_t_1] = usOut1_im[bufferSectionVecOut_t_1];
      end
    end
    bufferSectionVecOut_buffstate_next = us_vout1 != 1'b0;

    for(bufferSectionVecOut_t_2_0 = 32'sd0; bufferSectionVecOut_t_2_0 <= 32'sd2; bufferSectionVecOut_t_2_0 = bufferSectionVecOut_t_2_0 + 32'sd1) begin
      usOut_re[bufferSectionVecOut_t_2_0] = bufferSectionVecOut_buffreg_re[bufferSectionVecOut_t_2_0];
      usOut_im[bufferSectionVecOut_t_2_0] = bufferSectionVecOut_buffreg_im[bufferSectionVecOut_t_2_0];
    end

    us_vout_1 = bufferSectionVecOut_buffstate;
  end

  assign usOut_re_0 = usOut_re[0];

  assign usOut_re_1 = usOut_re[1];

  assign usOut_re_2 = usOut_re[2];

  assign usOut_im_0 = usOut_im[0];

  assign usOut_im_1 = usOut_im[1];

  assign usOut_im_2 = usOut_im[2];

  assign us_vout = us_vout_1;

endmodule  // bSection

