// -------------------------------------------------------------
// 
// File Name: D:\Desktop\Mul_Freq_DUC\2024-Multi-frequency-DUC\matlab\codegen\hdl_IP\hdlsrc\Upsampler.v
// Created: 2024-10-31 17:07:43
// 
// Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Upsampler
// Source Path: hdl_IP/Upsampler
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Upsampler
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           dataOut_0,
           dataOut_1,
           dataOut_2,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En14
  input   validIn;
  output  signed [15:0] dataOut_0;  // sfix16_En14
  output  signed [15:0] dataOut_1;  // sfix16_En14
  output  signed [15:0] dataOut_2;  // sfix16_En14
  output  validOut;


  wire softReset;
  reg signed [15:0] dataInreg;  // sfix16_En14
  wire signed [15:0] dtc_im;  // sfix16_En14
  reg  validInreg;
  wire signed [15:0] usOut1_re_0;  // sfix16_En14
  wire signed [15:0] usOut1_re_1;  // sfix16_En14
  wire signed [15:0] usOut1_re_2;  // sfix16_En14
  wire signed [15:0] usOut1_im_0;  // sfix16_En14
  wire signed [15:0] usOut1_im_1;  // sfix16_En14
  wire signed [15:0] usOut1_im_2;  // sfix16_En14
  wire us_vout1;
  wire signed [15:0] usOut_re_0;  // sfix16_En14
  wire signed [15:0] usOut_re_1;  // sfix16_En14
  wire signed [15:0] usOut_re_2;  // sfix16_En14
  wire signed [15:0] usOut_im_0;  // sfix16_En14
  wire signed [15:0] usOut_im_1;  // sfix16_En14
  wire signed [15:0] usOut_im_2;  // sfix16_En14
  wire us_vout;
  wire signed [15:0] invalidOut_1 [0:2];  // sfix16_En14 [3]
  wire signed [15:0] dataOutTmp [0:2];  // sfix16_En14 [3]
  reg signed [15:0] dataOut [0:2];  // sfix16_En14 [3]
  reg signed [31:0] alpha_t_0_0;  // int32
  reg signed [31:0] alpha_t_1;  // int32


  assign softReset = 1'b0;

  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b0) begin
        dataInreg <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (softReset == 1'b1) begin
            dataInreg <= 16'sb0000000000000000;
          end
          else begin
            dataInreg <= dataIn;
          end
        end
      end
    end

  assign dtc_im = 16'sb0000000000000000;

  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b0) begin
        validInreg <= 1'b0;
      end
      else begin
        if (enb) begin
          if (softReset == 1'b1) begin
            validInreg <= 1'b0;
          end
          else begin
            validInreg <= validIn;
          end
        end
      end
    end

  usSection u_usSection (.clk(clk),
                         .reset(reset),
                         .enb(enb),
                         .dataInus_re(dataInreg),  // sfix16_En14
                         .dataInus_im(dtc_im),  // sfix16_En14
                         .validInus(validInreg),
                         .internalReset(softReset),
                         .usOut_re_0(usOut1_re_0),  // sfix16_En14
                         .usOut_re_1(usOut1_re_1),  // sfix16_En14
                         .usOut_re_2(usOut1_re_2),  // sfix16_En14
                         .usOut_im_0(usOut1_im_0),  // sfix16_En14
                         .usOut_im_1(usOut1_im_1),  // sfix16_En14
                         .usOut_im_2(usOut1_im_2),  // sfix16_En14
                         .us_vout(us_vout1)
                         );

  bSection u_bSection (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .usOut1_re_0(usOut1_re_0),  // sfix16_En14
                       .usOut1_re_1(usOut1_re_1),  // sfix16_En14
                       .usOut1_re_2(usOut1_re_2),  // sfix16_En14
                       .usOut1_im_0(usOut1_im_0),  // sfix16_En14
                       .usOut1_im_1(usOut1_im_1),  // sfix16_En14
                       .usOut1_im_2(usOut1_im_2),  // sfix16_En14
                       .us_vout1(us_vout1),
                       .internalReset(softReset),
                       .usOut_re_0(usOut_re_0),  // sfix16_En14
                       .usOut_re_1(usOut_re_1),  // sfix16_En14
                       .usOut_re_2(usOut_re_2),  // sfix16_En14
                       .usOut_im_0(usOut_im_0),  // sfix16_En14
                       .usOut_im_1(usOut_im_1),  // sfix16_En14
                       .usOut_im_2(usOut_im_2),  // sfix16_En14
                       .us_vout(us_vout)
                       );

  assign invalidOut_1[0] = 16'sb0000000000000000;
  assign invalidOut_1[1] = 16'sb0000000000000000;
  assign invalidOut_1[2] = 16'sb0000000000000000;

  assign dataOutTmp[0] = usOut_re_0;
  assign dataOutTmp[1] = usOut_re_1;
  assign dataOutTmp[2] = usOut_re_2;

  always @* begin
    if (us_vout == 1'b0) begin
      for(alpha_t_1 = 32'sd0; alpha_t_1 <= 32'sd2; alpha_t_1 = alpha_t_1 + 32'sd1) begin
        dataOut[alpha_t_1] = invalidOut_1[alpha_t_1];
      end
    end
    else begin
      for(alpha_t_0_0 = 32'sd0; alpha_t_0_0 <= 32'sd2; alpha_t_0_0 = alpha_t_0_0 + 32'sd1) begin
        dataOut[alpha_t_0_0] = dataOutTmp[alpha_t_0_0];
      end
    end
  end

  assign dataOut_0 = dataOut[0];

  assign dataOut_1 = dataOut[1];

  assign dataOut_2 = dataOut[2];

  assign validOut = us_vout;

endmodule  // Upsampler

