// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC\Addressable_Delay_Line_block.v
// Created: 2024-12-28 19:00:54
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Addressable_Delay_Line_block
// Source Path: DUC/DUC_module/CIC_Comp Filter 2/Addressable_Delay_Line
// Hierarchy Level: 2
// Model version: 3.19
// 
// Addressable Delay Line
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Addressable_Delay_Line_block
          (clk,
           rst_n,
           enb,
           dataIn,
           validIn,
           rdAddr,
           delayLineEnd,
           dataOut);


  input   clk;
  input   rst_n;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  input   rdAddr;  // ufix1
  output  signed [15:0] delayLineEnd;  // sfix16_En15
  output  signed [15:0] dataOut;  // sfix16_En15


  reg signed [15:0] delayedSignals0;  // sfix16_En15
  reg signed [15:0] delayedSignals1;  // sfix16_En15
  wire signed [15:0] switchDataOut;  // sfix16_En15
  reg signed [15:0] dataOut_1;  // sfix16_En15


  always @(posedge clk)
    begin : delay0_process
      if (rst_n == 1'b0) begin
        delayedSignals0 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && validIn) begin
          delayedSignals0 <= dataIn;
        end
      end
    end

  always @(posedge clk)
    begin : delay1_process
      if (rst_n == 1'b0) begin
        delayedSignals1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && validIn) begin
          delayedSignals1 <= delayedSignals0;
        end
      end
    end

  assign delayLineEnd = delayedSignals1;

  assign switchDataOut = (rdAddr == 1'b0 ? delayedSignals1 :
              (rdAddr == 1'b1 ? delayedSignals0 :
              delayedSignals0));

  always @(posedge clk)
    begin : dataOutReg_process
      if (rst_n == 1'b0) begin
        dataOut_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          dataOut_1 <= switchDataOut;
        end
      end
    end

  assign dataOut = dataOut_1;

endmodule  // Addressable_Delay_Line_block

