// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC\Addressable_Delay_Line_block10.v
// Created: 2025-03-10 16:37:57
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Addressable_Delay_Line_block10
// Source Path: DUC/DUC_module/Wave_Source/Discrete FIR Filter/Addressable_Delay_Line
// Hierarchy Level: 3
// Model version: 3.54
// 
// Addressable Delay Line
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Addressable_Delay_Line_block10
          (clk,
           rst_n,
           enb,
           dataIn,
           validIn,
           wrAddr,
           rdAddr,
           dataOut);


  input   clk;
  input   rst_n;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  input   [3:0] wrAddr;  // ufix4
  input   [3:0] rdAddr;  // ufix4
  output  signed [15:0] dataOut;  // sfix16_En15


  wire signed [15:0] delayedSignals;  // sfix16_En15
  reg signed [15:0] dataOut_1;  // sfix16_En15


  SimpleDualPortRAM_generic #(.AddrWidth(4),
                              .DataWidth(16)
                              )
                            u_simpleDualPortRam (.clk(clk),
                                                 .enb(enb),
                                                 .wr_din(dataIn),
                                                 .wr_addr(wrAddr),
                                                 .wr_en(validIn),
                                                 .rd_addr(rdAddr),
                                                 .dout(delayedSignals)
                                                 );

  always @(posedge clk)
    begin : reg_rsvd_process
      if (rst_n == 1'b0) begin
        dataOut_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          dataOut_1 <= delayedSignals;
        end
      end
    end

  assign dataOut = dataOut_1;

endmodule  // Addressable_Delay_Line_block10

