vlib work
vlog  phInc.v
vlog  DitherGen.v
vlog  Lookup_Table.v
vlog  LookUpTableGen.v
vlog  WaveformGen.v
vlog  Carrier_1.v
vlog  DitherGen_block.v
vlog  Lookup_Table_block.v
vlog  LookUpTableGen_block.v
vlog  WaveformGen_block.v
vlog  Carrier_2.v
vlog  DitherGen_block1.v
vlog  Lookup_Table_block1.v
vlog  LookUpTableGen_block1.v
vlog  WaveformGen_block1.v
vlog  Carrier_3.v
vlog  AM_module_mul_freq.v
