// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC\CIC.v
// Created: 2025-03-25 14:21:11
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CIC
// Source Path: DUC/DUC_module/CIC/CIC
// Hierarchy Level: 2
// Model version: 3.79
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CIC
          (clk,
           rst_n,
           enb,
           enb_1_625_1,
           enb_1_625_0,
           enb_1_1_1,
           CIC_in,
           CIC_out);


  input   clk;
  input   rst_n;
  input   enb;
  input   enb_1_625_1;
  input   enb_1_625_0;
  input   enb_1_1_1;
  input   signed [15:0] CIC_in;  // sfix16_En15
  output  signed [15:0] CIC_out;  // sfix16_E23


  wire signed [16:0] CS_Section_1_in_DTC;  // sfix17_En15
  reg signed [16:0] CS_Section_1_delay;  // sfix17_En15
  wire signed [16:0] CS_Section_sub_1_sub_cast;  // sfix17_En15
  wire signed [16:0] CS_Section_1_out;  // sfix17_En15
  wire signed [17:0] CS_Section_2_in_DTC;  // sfix18_En15
  reg signed [17:0] CS_Section_2_delay;  // sfix18_En15
  wire signed [17:0] CS_Section_sub_2_sub_cast;  // sfix18_En15
  wire signed [17:0] CS_Section_2_out;  // sfix18_En15
  wire signed [18:0] CS_Section_3_in_DTC;  // sfix19_En15
  reg signed [18:0] CS_Section_3_delay;  // sfix19_En15
  wire signed [18:0] CS_Section_sub_3_sub_cast;  // sfix19_En15
  wire signed [18:0] CS_Section_3_out;  // sfix19_En15
  wire signed [19:0] CS_Section_4_in_DTC;  // sfix20_En15
  reg signed [19:0] CS_Section_4_delay;  // sfix20_En15
  wire signed [19:0] CS_Section_sub_4_sub_cast;  // sfix20_En15
  wire signed [19:0] CS_Section_4_out;  // sfix20_En15
  reg signed [19:0] CS_Section_5_delay;  // sfix20_En15
  wire signed [19:0] CS_Section_5_out;  // sfix20_En15
  wire signed [19:0] us_zero;  // sfix20_En15
  wire signed [19:0] us_muxout;  // sfix20_En15
  reg signed [19:0] us_bypass_reg;  // sfix20
  wire signed [19:0] us_bypassout;  // sfix20_En15
  reg signed [19:0] IS_Section_1_delay;  // sfix20_En15
  wire signed [19:0] IS_Section_1_out;  // sfix20_En15
  reg signed [28:0] IS_Section_2_delay;  // sfix29_En15
  wire signed [28:0] IS_Section_add_2_add_cast;  // sfix29_En15
  wire signed [28:0] IS_Section_2_out;  // sfix29_En15
  reg signed [36:0] IS_Section_3_delay;  // sfix37_En15
  wire signed [36:0] IS_Section_add_3_add_cast;  // sfix37_En15
  wire signed [36:0] IS_Section_3_out;  // sfix37_En15
  reg signed [44:0] IS_Section_4_delay;  // sfix45_En15
  wire signed [44:0] IS_Section_add_4_add_cast;  // sfix45_En15
  wire signed [44:0] IS_Section_4_out;  // sfix45_En15
  reg signed [53:0] IS_Section_5_delay;  // sfix54_En15
  wire signed [53:0] IS_Section_add_5_add_cast;  // sfix54_En15
  wire signed [53:0] IS_Section_5_out;  // sfix54_En15


  assign CS_Section_1_in_DTC = {CIC_in[15], CIC_in};
  always @(posedge clk)
    begin : CS_Section_delay_process
      if (rst_n == 1'b0) begin
        CS_Section_1_delay <= 17'sb00000000000000000;
      end
      else begin
        if (enb_1_625_0) begin
          CS_Section_1_delay <= CS_Section_1_in_DTC;
        end
      end
    end
  assign CS_Section_sub_1_sub_cast = {CIC_in[15], CIC_in};
  assign CS_Section_1_out = CS_Section_sub_1_sub_cast - CS_Section_1_delay;
  assign CS_Section_2_in_DTC = {CS_Section_1_out[16], CS_Section_1_out};
  always @(posedge clk)
    begin : CS_Section_delay1_process
      if (rst_n == 1'b0) begin
        CS_Section_2_delay <= 18'sb000000000000000000;
      end
      else begin
        if (enb_1_625_0) begin
          CS_Section_2_delay <= CS_Section_2_in_DTC;
        end
      end
    end
  assign CS_Section_sub_2_sub_cast = {CS_Section_1_out[16], CS_Section_1_out};
  assign CS_Section_2_out = CS_Section_sub_2_sub_cast - CS_Section_2_delay;
  assign CS_Section_3_in_DTC = {CS_Section_2_out[17], CS_Section_2_out};
  always @(posedge clk)
    begin : CS_Section_delay2_process
      if (rst_n == 1'b0) begin
        CS_Section_3_delay <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_625_0) begin
          CS_Section_3_delay <= CS_Section_3_in_DTC;
        end
      end
    end
  assign CS_Section_sub_3_sub_cast = {CS_Section_2_out[17], CS_Section_2_out};
  assign CS_Section_3_out = CS_Section_sub_3_sub_cast - CS_Section_3_delay;
  assign CS_Section_4_in_DTC = {CS_Section_3_out[18], CS_Section_3_out};
  always @(posedge clk)
    begin : CS_Section_delay3_process
      if (rst_n == 1'b0) begin
        CS_Section_4_delay <= 20'sb00000000000000000000;
      end
      else begin
        if (enb_1_625_0) begin
          CS_Section_4_delay <= CS_Section_4_in_DTC;
        end
      end
    end
  assign CS_Section_sub_4_sub_cast = {CS_Section_3_out[18], CS_Section_3_out};
  assign CS_Section_4_out = CS_Section_sub_4_sub_cast - CS_Section_4_delay;
  always @(posedge clk)
    begin : CS_Section_delay4_process
      if (rst_n == 1'b0) begin
        CS_Section_5_delay <= 20'sb00000000000000000000;
      end
      else begin
        if (enb_1_625_0) begin
          CS_Section_5_delay <= CS_Section_4_out;
        end
      end
    end
  assign CS_Section_5_out = CS_Section_4_out - CS_Section_5_delay;
  assign us_zero = 20'sb00000000000000000000;

  // us: Upsample by 625, Sample offset 0 
  assign us_muxout = (enb_1_625_1 == 1'b1 ? CS_Section_5_out :
              us_zero);
  // Upsample bypass register
  always @(posedge clk)
    begin : us_bypass_process
      if (rst_n == 1'b0) begin
        us_bypass_reg <= 20'sb00000000000000000000;
      end
      else begin
        if (enb_1_1_1) begin
          us_bypass_reg <= us_muxout;
        end
      end
    end

  assign us_bypassout = (enb_1_1_1 == 1'b1 ? us_muxout :
              us_bypass_reg);

  assign IS_Section_1_out = us_bypassout + IS_Section_1_delay;
  always @(posedge clk)
    begin : IS_Section_delay_process
      if (rst_n == 1'b0) begin
        IS_Section_1_delay <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          IS_Section_1_delay <= IS_Section_1_out;
        end
      end
    end
  assign IS_Section_add_2_add_cast = {{9{IS_Section_1_delay[19]}}, IS_Section_1_delay};
  assign IS_Section_2_out = IS_Section_add_2_add_cast + IS_Section_2_delay;
  always @(posedge clk)
    begin : IS_Section_delay1_process
      if (rst_n == 1'b0) begin
        IS_Section_2_delay <= 29'sb00000000000000000000000000000;
      end
      else begin
        if (enb) begin
          IS_Section_2_delay <= IS_Section_2_out;
        end
      end
    end
  assign IS_Section_add_3_add_cast = {{8{IS_Section_2_delay[28]}}, IS_Section_2_delay};
  assign IS_Section_3_out = IS_Section_add_3_add_cast + IS_Section_3_delay;
  always @(posedge clk)
    begin : IS_Section_delay2_process
      if (rst_n == 1'b0) begin
        IS_Section_3_delay <= 37'sh0000000000;
      end
      else begin
        if (enb) begin
          IS_Section_3_delay <= IS_Section_3_out;
        end
      end
    end
  assign IS_Section_add_4_add_cast = {{8{IS_Section_3_delay[36]}}, IS_Section_3_delay};
  assign IS_Section_4_out = IS_Section_add_4_add_cast + IS_Section_4_delay;
  always @(posedge clk)
    begin : IS_Section_delay3_process
      if (rst_n == 1'b0) begin
        IS_Section_4_delay <= 45'sh000000000000;
      end
      else begin
        if (enb) begin
          IS_Section_4_delay <= IS_Section_4_out;
        end
      end
    end
  assign IS_Section_add_5_add_cast = {{9{IS_Section_4_delay[44]}}, IS_Section_4_delay};
  assign IS_Section_5_out = IS_Section_add_5_add_cast + IS_Section_5_delay;
  always @(posedge clk)
    begin : IS_Section_delay4_process
      if (rst_n == 1'b0) begin
        IS_Section_5_delay <= 54'sh00000000000000;
      end
      else begin
        if (enb) begin
          IS_Section_5_delay <= IS_Section_5_out;
        end
      end
    end
  assign CIC_out = IS_Section_5_delay[53:38];
endmodule  // CIC

