// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC\CIC_2.v
// Created: 2025-03-17 16:40:09
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CIC_2
// Source Path: DUC/DUC_module_with_ready/CIC_2
// Hierarchy Level: 1
// Model version: 3.72
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CIC_2
          (clk,
           rst_n,
           enb,
           enb_1_25_0,
           enb_1_25_1,
           enb_1_1_1,
           CIC_2_in,
           CIC_2_out);


  input   clk;
  input   rst_n;
  input   enb;
  input   enb_1_25_0;
  input   enb_1_25_1;
  input   enb_1_1_1;
  input   signed [15:0] CIC_2_in;  // sfix16_E4
  output  signed [15:0] CIC_2_out;  // sfix16_E23


  wire signed [16:0] CS_Section_1_in_DTC;  // sfix17_E4
  reg signed [16:0] CS_Section_1_in_DTC_1;  // sfix17_E4
  wire signed [16:0] CS_Section_sub_1_sub_cast;  // sfix17_E4
  wire signed [16:0] CS_Section_1_out;  // sfix17_E4
  wire signed [17:0] CS_Section_2_in_DTC;  // sfix18_E4
  reg signed [17:0] CS_Section_2_in_DTC_1;  // sfix18_E4
  wire signed [17:0] CS_Section_sub_2_sub_cast;  // sfix18_E4
  wire signed [17:0] CS_Section_2_out;  // sfix18_E4
  wire signed [18:0] CS_Section_3_in_DTC;  // sfix19_E4
  reg signed [18:0] CS_Section_3_in_DTC_1;  // sfix19_E4
  wire signed [18:0] CS_Section_sub_3_sub_cast;  // sfix19_E4
  wire signed [18:0] CS_Section_3_out;  // sfix19_E4
  wire signed [19:0] CS_Section_4_in_DTC;  // sfix20_E4
  reg signed [19:0] CS_Section_4_in_DTC_1;  // sfix20_E4
  wire signed [19:0] CS_Section_sub_4_sub_cast;  // sfix20_E4
  wire signed [19:0] CS_Section_4_out;  // sfix20_E4
  reg signed [19:0] CS_Section_5_in_DTC;  // sfix20_E4
  wire signed [19:0] CS_Section_5_out;  // sfix20_E4
  wire signed [19:0] us_zero;  // sfix20_E4
  wire signed [19:0] us_muxout;  // sfix20_E4
  reg signed [19:0] us_bypass_reg;  // sfix20
  wire signed [19:0] us_bypassout;  // sfix20_E4
  reg signed [19:0] rateOut;  // sfix20_E4
  reg signed [19:0] IS_Section_1_out;  // sfix20_E4
  wire signed [19:0] IS_Section_1_out_1;  // sfix20_E4
  reg signed [23:0] IS_Section_2_out;  // sfix24_E4
  wire signed [23:0] IS_Section_add_2_add_cast;  // sfix24_E4
  wire signed [23:0] IS_Section_2_out_1;  // sfix24_E4
  reg signed [27:0] IS_Section_3_out;  // sfix28_E4
  wire signed [27:0] IS_Section_add_3_add_cast;  // sfix28_E4
  wire signed [27:0] IS_Section_3_out_1;  // sfix28_E4
  reg signed [30:0] IS_Section_4_out;  // sfix31_E4
  wire signed [30:0] IS_Section_add_4_add_cast;  // sfix31_E4
  wire signed [30:0] IS_Section_4_out_1;  // sfix31_E4
  reg signed [34:0] IS_Section_5_out;  // sfix35_E4
  wire signed [34:0] IS_Section_add_5_add_cast;  // sfix35_E4
  wire signed [34:0] IS_Section_5_out_1;  // sfix35_E4


  assign CS_Section_1_in_DTC = {CIC_2_in[15], CIC_2_in};
  always @(posedge clk)
    begin : rd_0_process
      if (rst_n == 1'b0) begin
        CS_Section_1_in_DTC_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb_1_25_0) begin
          CS_Section_1_in_DTC_1 <= CS_Section_1_in_DTC;
        end
      end
    end

  assign CS_Section_sub_1_sub_cast = {CIC_2_in[15], CIC_2_in};
  assign CS_Section_1_out = CS_Section_sub_1_sub_cast - CS_Section_1_in_DTC_1;
  assign CS_Section_2_in_DTC = {CS_Section_1_out[16], CS_Section_1_out};
  always @(posedge clk)
    begin : rd_1_process
      if (rst_n == 1'b0) begin
        CS_Section_2_in_DTC_1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb_1_25_0) begin
          CS_Section_2_in_DTC_1 <= CS_Section_2_in_DTC;
        end
      end
    end

  assign CS_Section_sub_2_sub_cast = {CS_Section_1_out[16], CS_Section_1_out};
  assign CS_Section_2_out = CS_Section_sub_2_sub_cast - CS_Section_2_in_DTC_1;
  assign CS_Section_3_in_DTC = {CS_Section_2_out[17], CS_Section_2_out};
  always @(posedge clk)
    begin : rd_2_process
      if (rst_n == 1'b0) begin
        CS_Section_3_in_DTC_1 <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_25_0) begin
          CS_Section_3_in_DTC_1 <= CS_Section_3_in_DTC;
        end
      end
    end

  assign CS_Section_sub_3_sub_cast = {CS_Section_2_out[17], CS_Section_2_out};
  assign CS_Section_3_out = CS_Section_sub_3_sub_cast - CS_Section_3_in_DTC_1;
  assign CS_Section_4_in_DTC = {CS_Section_3_out[18], CS_Section_3_out};
  always @(posedge clk)
    begin : rd_3_process
      if (rst_n == 1'b0) begin
        CS_Section_4_in_DTC_1 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb_1_25_0) begin
          CS_Section_4_in_DTC_1 <= CS_Section_4_in_DTC;
        end
      end
    end

  assign CS_Section_sub_4_sub_cast = {CS_Section_3_out[18], CS_Section_3_out};
  assign CS_Section_4_out = CS_Section_sub_4_sub_cast - CS_Section_4_in_DTC_1;
  always @(posedge clk)
    begin : rd_4_process
      if (rst_n == 1'b0) begin
        CS_Section_5_in_DTC <= 20'sb00000000000000000000;
      end
      else begin
        if (enb_1_25_0) begin
          CS_Section_5_in_DTC <= CS_Section_4_out;
        end
      end
    end

  assign CS_Section_5_out = CS_Section_4_out - CS_Section_5_in_DTC;
  assign us_zero = 20'sb00000000000000000000;

  // us: Upsample by 25, Sample offset 0 
  assign us_muxout = (enb_1_25_1 == 1'b1 ? CS_Section_5_out :
              us_zero);
  // Upsample bypass register
  always @(posedge clk)
    begin : us_bypass_process
      if (rst_n == 1'b0) begin
        us_bypass_reg <= 20'sb00000000000000000000;
      end
      else begin
        if (enb_1_1_1) begin
          us_bypass_reg <= us_muxout;
        end
      end
    end

  assign us_bypassout = (enb_1_1_1 == 1'b1 ? us_muxout :
              us_bypass_reg);

  always @(posedge clk)
    begin : rd_5_process
      if (rst_n == 1'b0) begin
        rateOut <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          rateOut <= us_bypassout;
        end
      end
    end

  assign IS_Section_1_out_1 = rateOut + IS_Section_1_out;
  always @(posedge clk)
    begin : rd_6_process
      if (rst_n == 1'b0) begin
        IS_Section_1_out <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          IS_Section_1_out <= IS_Section_1_out_1;
        end
      end
    end

  assign IS_Section_add_2_add_cast = {{4{IS_Section_1_out[19]}}, IS_Section_1_out};
  assign IS_Section_2_out_1 = IS_Section_add_2_add_cast + IS_Section_2_out;
  always @(posedge clk)
    begin : rd_7_process
      if (rst_n == 1'b0) begin
        IS_Section_2_out <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          IS_Section_2_out <= IS_Section_2_out_1;
        end
      end
    end

  assign IS_Section_add_3_add_cast = {{4{IS_Section_2_out[23]}}, IS_Section_2_out};
  assign IS_Section_3_out_1 = IS_Section_add_3_add_cast + IS_Section_3_out;
  always @(posedge clk)
    begin : rd_8_process
      if (rst_n == 1'b0) begin
        IS_Section_3_out <= 28'sb0000000000000000000000000000;
      end
      else begin
        if (enb) begin
          IS_Section_3_out <= IS_Section_3_out_1;
        end
      end
    end

  assign IS_Section_add_4_add_cast = {{3{IS_Section_3_out[27]}}, IS_Section_3_out};
  assign IS_Section_4_out_1 = IS_Section_add_4_add_cast + IS_Section_4_out;
  always @(posedge clk)
    begin : rd_9_process
      if (rst_n == 1'b0) begin
        IS_Section_4_out <= 31'sb0000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          IS_Section_4_out <= IS_Section_4_out_1;
        end
      end
    end

  assign IS_Section_add_5_add_cast = {{4{IS_Section_4_out[30]}}, IS_Section_4_out};
  assign IS_Section_5_out_1 = IS_Section_add_5_add_cast + IS_Section_5_out;
  always @(posedge clk)
    begin : rd_10_process
      if (rst_n == 1'b0) begin
        IS_Section_5_out <= 35'sh000000000;
      end
      else begin
        if (enb) begin
          IS_Section_5_out <= IS_Section_5_out_1;
        end
      end
    end

  assign CIC_2_out = IS_Section_5_out[34:19];
endmodule  // CIC_2

