// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC\CIC_COMP.v
// Created: 2025-03-25 14:21:11
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CIC_COMP
// Source Path: DUC/DUC_module/CIC_COMP
// Hierarchy Level: 1
// Model version: 3.79
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CIC_COMP
          (clk,
           rst_n,
           enb,
           enb_1_625_1,
           enb_1_625_0,
           DATA_IN,
           VLD_IN,
           preCIC_RESAMPLE);


  input   clk;
  input   rst_n;
  input   enb;
  input   enb_1_625_1;
  input   enb_1_625_0;
  input   signed [15:0] DATA_IN;  // sfix16_En15
  input   VLD_IN;
  output  signed [15:0] preCIC_RESAMPLE;  // sfix16_En15


  wire signed [15:0] CIC_Comp_Filter_1_out1;  // sfix16_En15
  wire CIC_Comp_Filter_1_out2;
  reg signed [15:0] CIC_Comp_Delay_delOut;  // sfix16_En15
  wire signed [15:0] CIC_Comp_Delay_ectrl;  // sfix16_En15
  wire signed [15:0] preCIC_RESAMPLE_1;  // sfix16_En15
  reg signed [15:0] CIC_Comp_Delay_last_value;  // sfix16_En15
  reg signed [15:0] Delay1_out1;  // sfix16_En15
  reg signed [15:0] Delay1_out1_1;  // sfix16_En15


  CIC_Comp_Filter_1 u_CIC_Comp_Filter_1 (.clk(clk),
                                         .rst_n(rst_n),
                                         .enb(enb),
                                         .dataIn(DATA_IN),  // sfix16_En15
                                         .validIn(VLD_IN),
                                         .dataOut(CIC_Comp_Filter_1_out1),  // sfix16_En15
                                         .validOut(CIC_Comp_Filter_1_out2)
                                         );
  assign CIC_Comp_Delay_ectrl = (CIC_Comp_Filter_1_out2 == 1'b0 ? CIC_Comp_Delay_delOut :
              CIC_Comp_Filter_1_out1);

  always @(posedge clk)
    begin : CIC_Comp_Delay_lowered_process
      if (rst_n == 1'b0) begin
        CIC_Comp_Delay_delOut <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          CIC_Comp_Delay_delOut <= CIC_Comp_Delay_ectrl;
        end
      end
    end
  always @(posedge clk)
    begin : CIC_Comp_Delay_bypass_process
      if (rst_n == 1'b0) begin
        CIC_Comp_Delay_last_value <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          CIC_Comp_Delay_last_value <= preCIC_RESAMPLE_1;
        end
      end
    end

  assign preCIC_RESAMPLE_1 = (CIC_Comp_Filter_1_out2 == 1'b0 ? CIC_Comp_Delay_last_value :
              CIC_Comp_Delay_delOut);

  // Downsample by 625 register (Sample offset 0)
  always @(posedge clk)
    begin : Downsample_625_output_process
      if (rst_n == 1'b0) begin
        Delay1_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_625_1) begin
          Delay1_out1 <= preCIC_RESAMPLE_1;
        end
      end
    end
  always @(posedge clk)
    begin : PipelineRegister_process
      if (rst_n == 1'b0) begin
        Delay1_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_625_0) begin
          Delay1_out1_1 <= Delay1_out1;
        end
      end
    end

  assign preCIC_RESAMPLE = Delay1_out1_1;

endmodule  // CIC_COMP

