// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC\CIC_Comp_Filter_1.v
// Created: 2024-12-28 19:00:54
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CIC_Comp_Filter_1
// Source Path: DUC/DUC_module/CIC_Comp Filter 1
// Hierarchy Level: 1
// Model version: 3.19
// 
// Discrete FIR Filter
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CIC_Comp_Filter_1
          (clk,
           rst_n,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   rst_n;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  output  signed [15:0] dataOut;  // sfix16_En15
  output  validOut;


  wire syncReset;


  assign syncReset = 1'b0;

  Filter u_FilterBank (.clk(clk),
                       .rst_n(rst_n),
                       .enb(enb),
                       .dataIn(dataIn),  // sfix16_En15
                       .validIn(validIn),
                       .syncReset(syncReset),
                       .dataOut(dataOut),  // sfix16_En15
                       .validOut(validOut)
                       );

endmodule  // CIC_Comp_Filter_1

