SLStudio.Utils.RemoveHighlighting(get_param('DUC', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_DUC', 'handle'));
annotate_port('gm_DUC/DUC_module/CIC_1', 1, 1, '');
annotate_port('gm_DUC/DUC_module/Halfband Filter 1', 0, 1, '');
annotate_port('DUC/DUC_module/Halfband Filter 1', 0, 1, '');
annotate_port('gm_DUC/DUC_module/Halfband Filter 1', 0, 1, '');
annotate_port('DUC/DUC_module/Halfband Filter 1', 0, 1, '');
annotate_port('gm_DUC/DUC_module/PipelineRegister3', 0, 1, '');
annotate_port('gm_DUC/DUC_module/CIC_1/us', 0, 1, '');
annotate_port('gm_DUC/DUC_module/CIC_1/us', 1, 1, '');
annotate_port('DUC/DUC_module/CIC_1', 1, 1, '');
annotate_port('gm_DUC/DUC_module/CIC_1/CS_Section_sub_5', 0, 1, '');
annotate_port('gm_DUC/DUC_module/CIC_1/CS_Section_sub_4', 0, 1, '');
annotate_port('gm_DUC/DUC_module/CIC_1/CS_Section_sub_3', 0, 1, '');
annotate_port('gm_DUC/DUC_module/CIC_1/CS_Section_sub_2', 0, 1, '');
annotate_port('gm_DUC/DUC_module/CIC_1/CS_Section_sub_1', 0, 1, '');
annotate_port('gm_DUC/DUC_module/CIC_1/IS_Section_add_1', 0, 1, '');
annotate_port('gm_DUC/DUC_module/CIC_1/IS_Section_delay', 1, 1, '');
annotate_port('gm_DUC/DUC_module/CIC_1/IS_Section_delay_enbsw', 0, 1, '');
annotate_port('gm_DUC/DUC_module/CIC_2/us', 1, 1, '');
annotate_port('DUC/DUC_module/CIC_2', 1, 1, '');
