open_system('gm_DUC');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC/DUC_module/CIC_1', 'user2');
annotate_port('gm_DUC/DUC_module/CIC_1', 1, 1, 'cp : 8.918 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC/DUC_module/PipelineRegister3', 'user1');
annotate_port('gm_DUC/DUC_module/PipelineRegister3', 0, 1, 'cp : 0.511 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC/DUC_module/CIC_1/us', 'user2');
annotate_port('gm_DUC/DUC_module/CIC_1/us', 0, 1, 'cp : 7.129 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC/DUC_module/CIC_1/CS_Section_sub_5', 'user2');
annotate_port('gm_DUC/DUC_module/CIC_1/CS_Section_sub_5', 0, 1, 'cp : 6.456 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC/DUC_module/CIC_1/CS_Section_sub_4', 'user2');
annotate_port('gm_DUC/DUC_module/CIC_1/CS_Section_sub_4', 0, 1, 'cp : 5.267 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC/DUC_module/CIC_1/CS_Section_sub_3', 'user2');
annotate_port('gm_DUC/DUC_module/CIC_1/CS_Section_sub_3', 0, 1, 'cp : 4.078 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC/DUC_module/CIC_1/CS_Section_sub_2', 'user2');
annotate_port('gm_DUC/DUC_module/CIC_1/CS_Section_sub_2', 0, 1, 'cp : 2.889 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC/DUC_module/CIC_1/CS_Section_sub_1', 'user2');
annotate_port('gm_DUC/DUC_module/CIC_1/CS_Section_sub_1', 0, 1, 'cp : 1.7 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC/DUC_module/CIC_1/IS_Section_add_1', 'user2');
annotate_port('gm_DUC/DUC_module/CIC_1/IS_Section_add_1', 0, 1, 'cp : 8.318 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC/DUC_module/CIC_1/IS_Section_delay', 'user1');
annotate_port('gm_DUC/DUC_module/CIC_1/IS_Section_delay', 1, 1, 'cp : 8.918 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC/DUC_module/CIC_1/IS_Section_delay_enbsw', 'user2');
annotate_port('gm_DUC/DUC_module/CIC_1/IS_Section_delay_enbsw', 0, 1, 'cp : 8.676 ns');
