vlib work
vlog  DUC_module_tc.v
vlog  CIC.v
vlog  CIC_block.v
vlog  FirRdyLogic.v
vlog  SimpleDualPortRAM_generic.v
vlog  Addressable_Delay_Line.v
vlog  Addressable_Delay_Line_block.v
vlog  FilterTapSystolicPreAdd.v
vlog  CIC_Comp_Filter_1.v
vlog  CIC_COMP.v
vlog  GAIN_CORRECTION.v
vlog  FirRdyLogic_block.v
vlog  Addressable_Delay_Line_block1.v
vlog  Addressable_Delay_Line_block2.v
vlog  Addressable_Delay_Line_block3.v
vlog  FilterTapSystolicPreAdd_block.v
vlog  Halfband_Filter_1.v
vlog  HB1.v
vlog  FirRdyLogic_block1.v
vlog  Addressable_Delay_Line_block4.v
vlog  Addressable_Delay_Line_block5.v
vlog  Addressable_Delay_Line_block6.v
vlog  FilterTapSystolicPreAdd_block1.v
vlog  Halfband_Filter_2.v
vlog  HB2.v
vlog  DUC_module.v
