vlib work
vlog  DUC_module_tc.v
vlog  CIC_1.v
vlog  CIC_2.v
vlog  FirRdyLogic.v
vlog  SimpleDualPortRAM_generic.v
vlog  Addressable_Delay_Line.v
vlog  Addressable_Delay_Line_block.v
vlog  FilterTapSystolicPreAdd.v
vlog  CIC_Comp_Filter_1.v
vlog  FirRdyLogic_block.v
vlog  Addressable_Delay_Line_block1.v
vlog  Addressable_Delay_Line_block2.v
vlog  FilterTapSystolicPreAdd_block.v
vlog  CIC_Comp_Filter_2.v
vlog  FirRdyLogic_block1.v
vlog  Addressable_Delay_Line_block3.v
vlog  Addressable_Delay_Line_block4.v
vlog  Addressable_Delay_Line_block5.v
vlog  FilterTapSystolicPreAdd_block1.v
vlog  Halfband_Filter_1.v
vlog  FirRdyLogic_block2.v
vlog  Addressable_Delay_Line_block6.v
vlog  Addressable_Delay_Line_block7.v
vlog  Addressable_Delay_Line_block8.v
vlog  FilterTapSystolicPreAdd_block2.v
vlog  Halfband_Filter_2.v
vlog  DitherGen.v
vlog  Lookup_Table.v
vlog  LookUpTableGen.v
vlog  WaveformGen.v
vlog  NCO.v
vlog  DitherGen_block.v
vlog  Lookup_Table_block.v
vlog  LookUpTableGen_block.v
vlog  WaveformGen_block.v
vlog  NCO1.v
vlog  DUC_module.v
