vlib work
vlog  DUC_module_tc.v
vlog  CIC_1.v
vlog  CIC_2.v
vlog  FilterCoef.v
vlog  FilterTapSystolicPreAddWvlIn.v
vlog  subFilter.v
vlog  Filter.v
vlog  CIC_Comp_Filter_1.v
vlog  FirRdyLogic.v
vlog  Addressable_Delay_Line.v
vlog  Addressable_Delay_Line_block.v
vlog  FilterTapSystolicPreAdd.v
vlog  CIC_Comp_Filter_2.v
vlog  FirRdyLogic_block.v
vlog  SimpleDualPortRAM_generic.v
vlog  Addressable_Delay_Line_block1.v
vlog  Addressable_Delay_Line_block2.v
vlog  Addressable_Delay_Line_block3.v
vlog  FilterTapSystolicPreAdd_block.v
vlog  Halfband_Filter_1.v
vlog  FilterCoef_block.v
vlog  FilterTapSystolicWvldInC0.v
vlog  FilterTapSystolicPreAddWvlIn_block.v
vlog  subFilter_block.v
vlog  Filter_block.v
vlog  Halfband_Filter_2.v
vlog  DitherGen.v
vlog  Lookup_Table.v
vlog  LookUpTableGen.v
vlog  WaveformGen.v
vlog  NCO.v
vlog  DitherGen_block.v
vlog  Lookup_Table_block.v
vlog  LookUpTableGen_block.v
vlog  WaveformGen_block.v
vlog  NCO1.v
vlog  DUC_module.v
