// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC\GAIN_CORRECTION.v
// Created: 2025-03-25 14:21:11
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: GAIN_CORRECTION
// Source Path: DUC/DUC_module/GAIN_CORRECTION
// Hierarchy Level: 1
// Model version: 3.79
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module GAIN_CORRECTION
          (clk,
           rst_n,
           enb,
           DATA_IN,
           DATA_OUT);


  input   clk;
  input   rst_n;
  input   enb;
  input   signed [15:0] DATA_IN;  // sfix16_E23
  output  signed [15:0] DATA_OUT;  // sfix16_En14


  wire signed [15:0] kconst;  // sfix16_En14
  reg signed [15:0] kconst_1;  // sfix16_En14
  wire signed [31:0] Gain2_cast;  // sfix32_En27
  wire signed [15:0] Gain2_out1;  // sfix16_En13
  reg signed [15:0] Delay2_out1;  // sfix16_En13
  reg signed [15:0] Delay2_out1_1;  // sfix16_En13
  wire signed [31:0] Gain_Correct_mul_temp;  // sfix32_En27
  wire signed [15:0] Gain_Correct_out1;  // sfix16_En14
  reg signed [15:0] Gain_Correct_out1_1;  // sfix16_En14


  assign kconst = 16'sb0110110010111100;

  always @(posedge clk)
    begin : HwModeRegister_process
      if (rst_n == 1'b0) begin
        kconst_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          kconst_1 <= kconst;
        end
      end
    end

  assign Gain2_cast = {{2{DATA_IN[15]}}, {DATA_IN, 14'b00000000000000}};
  assign Gain2_out1 = Gain2_cast[29:14];
  always @(posedge clk)
    begin : Delay2_process
      if (rst_n == 1'b0) begin
        Delay2_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= Gain2_out1;
        end
      end
    end
  always @(posedge clk)
    begin : HwModeRegister1_process
      if (rst_n == 1'b0) begin
        Delay2_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1_1 <= Delay2_out1;
        end
      end
    end

  assign Gain_Correct_mul_temp = kconst_1 * Delay2_out1_1;
  assign Gain_Correct_out1 = Gain_Correct_mul_temp[28:13];
  always @(posedge clk)
    begin : PipelineRegister_process
      if (rst_n == 1'b0) begin
        Gain_Correct_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Gain_Correct_out1_1 <= Gain_Correct_out1;
        end
      end
    end
  assign DATA_OUT = Gain_Correct_out1_1;

endmodule  // GAIN_CORRECTION

