// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC\Halfband_Filter_1.v
// Created: 2024-12-28 19:00:54
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Halfband_Filter_1
// Source Path: DUC/DUC_module/Halfband Filter 1
// Hierarchy Level: 1
// Model version: 3.19
// 
// Discrete FIR Filter
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Halfband_Filter_1
          (clk,
           rst_n,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   rst_n;
  input   enb;
  input   signed [31:0] dataIn;  // sfix32_En30
  input   validIn;
  output  signed [15:0] dataOut;  // sfix16_En15
  output  validOut;


  wire signed [31:0] coeff;  // sfix32_En30
  wire haltProcess;
  wire signed [31:0] dinSM;  // sfix32_En30
  wire dinVldSM;
  reg [1:0] nextDelayLineRdAddrReverse;  // ufix2
  reg [1:0] rdCountReverse_1;  // ufix2
  reg [1:0] nextDelayLineWrAddr;  // ufix2
  reg [1:0] wrCount_1;  // ufix2
  reg [1:0] nextDelayLineRdAddr;  // ufix2
  reg [1:0] rdCount_1;  // ufix2
  reg [1:0] nextSharingCount;  // ufix2
  reg [1:0] sharingCount_1;  // ufix2
  reg  delayLineValidInP;
  reg  lastPhaseStrobe;
  reg  delayLineShiftEnP;
  reg  delayLineShiftEn1_1;
  wire syncResetRst;
  reg  delayLineShiftEn2_1;
  reg  delayLineShiftEn3_1;
  reg  delayLineShiftEn4_1;
  reg  delayLineShiftEn5_1;
  reg  delayLineShiftEn6_1;
  reg  delayLineShiftEn7_1;
  reg  delayLineShiftEn8_1;
  reg  delayLineShiftEn9_1;
  reg  delayLineShiftEn10_1;
  reg  delayLineShiftEn11_1;
  reg  delayLineShiftEn12_1;
  reg  delayLineShiftEn13_1;
  reg  [6:0] validOutLookahead_reg;  // ufix1 [7]
  wire validOutLookahead_1;
  reg  vldOut_1;
  wire notValid;
  reg [1:0] rdAddr0_1;  // ufix2
  reg [1:0] rdAddr1;  // ufix2
  reg [1:0] rdAddr2;  // ufix2
  reg [1:0] rdAddr3;  // ufix2
  reg [1:0] rdAddr4;  // ufix2
  reg [1:0] rdAddr5;  // ufix2
  reg [1:0] rdAddr6;  // ufix2
  reg [1:0] rdAddr7;  // ufix2
  reg [1:0] rdAddr8;  // ufix2
  reg [1:0] rdAddr9;  // ufix2
  reg [1:0] rdAddr10;  // ufix2
  reg [1:0] rdAddr11;  // ufix2
  reg [1:0] rdAddr12;  // ufix2
  reg [1:0] rdAddr13;  // ufix2
  wire rdAddrEndNonZero;
  wire rdAddrEndZero;
  reg  [4:0] finalSumValidPipe_reg;  // ufix1 [5]
  wire accumulate;
  wire signed [63:0] accDataOut;  // sfix64_En61
  reg [1:0] wrAddrP;  // ufix2
  reg [1:0] rdAddrDelayLine0;  // ufix2
  wire signed [31:0] delayLineEnd0;  // sfix32_En30
  wire signed [31:0] delayLineDataOut0deadOut;  // sfix32_En30
  reg signed [31:0] delayLineDataIn1_1;  // sfix32_En30
  reg [1:0] wrAddr1;  // ufix2
  reg [1:0] rdAddrDelayLine1;  // ufix2
  wire signed [31:0] delayLineEnd1;  // sfix32_En30
  wire signed [31:0] delayLineDataOut1;  // sfix32_En30
  reg signed [31:0] delayLineDataIn2_1;  // sfix32_En30
  reg [1:0] wrAddr2;  // ufix2
  reg [1:0] rdAddrDelayLine2;  // ufix2
  wire signed [31:0] delayLineEnd2;  // sfix32_En30
  wire signed [31:0] delayLineDataOut2;  // sfix32_En30
  reg signed [31:0] delayLineDataIn3_1;  // sfix32_En30
  reg [1:0] wrAddr3;  // ufix2
  reg [1:0] rdAddrDelayLine3;  // ufix2
  wire signed [31:0] delayLineEnd3;  // sfix32_En30
  wire signed [31:0] delayLineDataOut3;  // sfix32_En30
  reg signed [31:0] delayLineDataIn4_1;  // sfix32_En30
  reg [1:0] wrAddr4;  // ufix2
  reg [1:0] rdAddrDelayLine4;  // ufix2
  wire signed [31:0] delayLineEnd4;  // sfix32_En30
  wire signed [31:0] delayLineDataOut4;  // sfix32_En30
  reg signed [31:0] delayLineDataIn5_1;  // sfix32_En30
  reg [1:0] wrAddr5;  // ufix2
  reg [1:0] rdAddrDelayLine5;  // ufix2
  wire signed [31:0] delayLineEnd5;  // sfix32_En30
  wire signed [31:0] delayLineDataOut5;  // sfix32_En30
  reg signed [31:0] delayLineDataIn6_1;  // sfix32_En30
  reg [1:0] wrAddr6;  // ufix2
  reg [1:0] rdAddrDelayLine6;  // ufix2
  wire signed [31:0] delayLineEnd6;  // sfix32_En30
  wire signed [31:0] delayLineDataOut6;  // sfix32_En30
  reg signed [31:0] delayLineDataIn7_1;  // sfix32_En30
  reg [1:0] wrAddr7;  // ufix2
  reg [1:0] rdAddrDelayLine7;  // ufix2
  wire signed [31:0] delayLineEnd7;  // sfix32_En30
  wire signed [31:0] delayLineDataOut7;  // sfix32_En30
  reg signed [31:0] delayLineDataIn8_1;  // sfix32_En30
  reg [1:0] wrAddr8;  // ufix2
  reg [1:0] rdAddrDelayLine8;  // ufix2
  wire signed [31:0] delayLineEnd8;  // sfix32_En30
  wire signed [31:0] delayLineDataOut8;  // sfix32_En30
  reg signed [31:0] delayLineDataIn9_1;  // sfix32_En30
  reg [1:0] wrAddr9;  // ufix2
  reg [1:0] rdAddrDelayLine9;  // ufix2
  wire signed [31:0] delayLineEnd9;  // sfix32_En30
  wire signed [31:0] delayLineDataOut9;  // sfix32_En30
  reg signed [31:0] delayLineDataIn10_1;  // sfix32_En30
  reg [1:0] wrAddr10;  // ufix2
  reg [1:0] rdAddrDelayLine10;  // ufix2
  wire signed [31:0] delayLineEnd10;  // sfix32_En30
  wire signed [31:0] delayLineDataOut10;  // sfix32_En30
  reg signed [31:0] delayLineDataIn11_1;  // sfix32_En30
  reg [1:0] wrAddr11;  // ufix2
  reg [1:0] rdAddrDelayLine11;  // ufix2
  wire signed [31:0] delayLineEnd11;  // sfix32_En30
  wire signed [31:0] delayLineDataOut11;  // sfix32_En30
  reg signed [31:0] delayLineDataIn12_1;  // sfix32_En30
  wire signed [31:0] delayLineEnd12;  // sfix32_En30
  wire signed [31:0] delayLineDataOut12;  // sfix32_En30
  wire signed [31:0] preAddIn;  // sfix32_En30
  reg signed [31:0] coeffTableOut12;  // sfix32_En31
  reg signed [31:0] coeffTableRegP12_1;  // sfix32_En31
  reg signed [31:0] coeffTableReg12_1;  // sfix32_En31
  reg signed [31:0] delayLineDataIn13_1;  // sfix32_En30
  reg [1:0] wrAddr12;  // ufix2
  reg [1:0] rdAddReverse1;  // ufix2
  reg [1:0] rdAddReverse2;  // ufix2
  reg [1:0] rdAddReverse3;  // ufix2
  reg [1:0] rdAddReverse4;  // ufix2
  reg [1:0] rdAddReverse5;  // ufix2
  reg [1:0] rdAddReverse6;  // ufix2
  reg [1:0] rdAddReverse7;  // ufix2
  reg [1:0] rdAddReverse8;  // ufix2
  reg [1:0] rdAddReverse9;  // ufix2
  reg [1:0] rdAddReverse10;  // ufix2
  reg [1:0] rdAddReverse11;  // ufix2
  reg [1:0] rdAddReverse12;  // ufix2
  wire signed [31:0] delayLineEnd13;  // sfix32_En30
  wire signed [31:0] delayLineDataOut13;  // sfix32_En30
  reg signed [31:0] coeffTableOut11;  // sfix32_En31
  reg signed [31:0] coeffTableRegP11_1;  // sfix32_En31
  reg signed [31:0] coeffTableReg11_1;  // sfix32_En31
  wire signed [31:0] delayLineEnd14;  // sfix32_En30
  wire signed [31:0] delayLineDataOut14;  // sfix32_En30
  reg signed [31:0] coeffTableOut10;  // sfix32_En31
  reg signed [31:0] coeffTableRegP10_1;  // sfix32_En31
  reg signed [31:0] coeffTableReg10_1;  // sfix32_En31
  wire signed [31:0] delayLineEnd15;  // sfix32_En30
  wire signed [31:0] delayLineDataOut15;  // sfix32_En30
  reg signed [31:0] coeffTableOut9;  // sfix32_En31
  reg signed [31:0] coeffTableRegP9_1;  // sfix32_En31
  reg signed [31:0] coeffTableReg9_1;  // sfix32_En31
  wire signed [31:0] delayLineEnd16;  // sfix32_En30
  wire signed [31:0] delayLineDataOut16;  // sfix32_En30
  reg signed [31:0] coeffTableOut8;  // sfix32_En31
  reg signed [31:0] coeffTableRegP8_1;  // sfix32_En31
  reg signed [31:0] coeffTableReg8_1;  // sfix32_En31
  wire signed [31:0] delayLineEnd17;  // sfix32_En30
  wire signed [31:0] delayLineDataOut17;  // sfix32_En30
  reg signed [31:0] coeffTableOut7;  // sfix32_En31
  reg signed [31:0] coeffTableRegP7_1;  // sfix32_En31
  reg signed [31:0] coeffTableReg7_1;  // sfix32_En31
  wire signed [31:0] delayLineEnd18;  // sfix32_En30
  wire signed [31:0] delayLineDataOut18;  // sfix32_En30
  reg signed [31:0] coeffTableOut6;  // sfix32_En31
  reg signed [31:0] coeffTableRegP6_1;  // sfix32_En31
  reg signed [31:0] coeffTableReg6_1;  // sfix32_En31
  wire signed [31:0] delayLineEnd19;  // sfix32_En30
  wire signed [31:0] delayLineDataOut19;  // sfix32_En30
  reg signed [31:0] coeffTableOut5;  // sfix32_En31
  reg signed [31:0] coeffTableRegP5_1;  // sfix32_En31
  reg signed [31:0] coeffTableReg5_1;  // sfix32_En31
  wire signed [31:0] delayLineEnd20;  // sfix32_En30
  wire signed [31:0] delayLineDataOut20;  // sfix32_En30
  reg signed [31:0] coeffTableOut4;  // sfix32_En31
  reg signed [31:0] coeffTableRegP4_1;  // sfix32_En31
  reg signed [31:0] coeffTableReg4_1;  // sfix32_En31
  wire signed [31:0] delayLineEnd21;  // sfix32_En30
  wire signed [31:0] delayLineDataOut21;  // sfix32_En30
  reg signed [31:0] coeffTableOut3;  // sfix32_En31
  reg signed [31:0] coeffTableRegP3_1;  // sfix32_En31
  reg signed [31:0] coeffTableReg3_1;  // sfix32_En31
  wire signed [31:0] delayLineEnd22;  // sfix32_En30
  wire signed [31:0] delayLineDataOut22;  // sfix32_En30
  reg signed [31:0] coeffTableOut2;  // sfix32_En31
  reg signed [31:0] coeffTableRegP2_1;  // sfix32_En31
  reg signed [31:0] coeffTableReg2_1;  // sfix32_En31
  wire signed [31:0] delayLineEnd23deadOut;  // sfix32_En30
  wire signed [31:0] delayLineDataOut23;  // sfix32_En30
  reg signed [31:0] coeffTableOut1;  // sfix32_En31
  reg signed [31:0] coeffTableRegP1_1;  // sfix32_En31
  reg signed [31:0] coeffTableReg1_1;  // sfix32_En31
  wire signed [63:0] sumIn;  // sfix64_En61
  reg signed [63:0] sumOut;  // sfix64_En61
  wire signed [63:0] sumOut_0;  // sfix64_En61
  wire signed [63:0] sumOut_1;  // sfix64_En61
  wire signed [63:0] sumOut_2;  // sfix64_En61
  wire signed [63:0] sumOut_3;  // sfix64_En61
  wire signed [63:0] sumOut_4;  // sfix64_En61
  wire signed [63:0] sumOut_5;  // sfix64_En61
  wire signed [63:0] sumOut_6;  // sfix64_En61
  wire signed [63:0] sumOut_7;  // sfix64_En61
  wire signed [63:0] sumOut_8;  // sfix64_En61
  wire signed [63:0] sumOut_9;  // sfix64_En61
  wire signed [63:0] sumOut_10;  // sfix64_En61
  wire signed [63:0] sumOut_11;  // sfix64_En61
  reg signed [63:0] sumOutReg_1;  // sfix64_En61
  reg signed [63:0] accDataOut_1;  // sfix64_En61
  wire signed [63:0] accSwitchOut;  // sfix64_En61
  wire signed [63:0] accAdderOut;  // sfix64_En61
  wire signed [15:0] converterOut;  // sfix16_En15
  reg signed [15:0] dataOutRegIn;  // sfix16_En15
  reg signed [15:0] dout_re_1;  // sfix16_En15
  wire signed [15:0] dataZero;  // sfix16_En15
  reg [1:0] InputControl_out4_0;  // ufix2

  initial begin
    coeffTableRegP12_1 = 32'sb00000000000000000000000000000000;
    coeffTableRegP11_1 = 32'sb00000000000000000000000000000000;
    coeffTableRegP10_1 = 32'sb00000000000000000000000000000000;
    coeffTableRegP9_1 = 32'sb00000000000000000000000000000000;
    coeffTableRegP8_1 = 32'sb00000000000000000000000000000000;
    coeffTableRegP7_1 = 32'sb00000000000000000000000000000000;
    coeffTableRegP6_1 = 32'sb00000000000000000000000000000000;
    coeffTableRegP5_1 = 32'sb00000000000000000000000000000000;
    coeffTableRegP4_1 = 32'sb00000000000000000000000000000000;
    coeffTableRegP3_1 = 32'sb00000000000000000000000000000000;
    coeffTableRegP2_1 = 32'sb00000000000000000000000000000000;
    coeffTableRegP1_1 = 32'sb00000000000000000000000000000000;
  end

  assign coeff = 32'sb00000000000000000000000000000000;

  assign haltProcess = 1'b0;

  FirRdyLogic_block u_firRdyLogic (.clk(clk),
                                   .rst_n(rst_n),
                                   .enb(enb),
                                   .dinSwitch(dataIn),  // sfix32_En30
                                   .dinVldSwitch(validIn),
                                   .coeff(coeff),  // sfix32_En30
                                   .haltProcess(haltProcess),
                                   .dinSM(dinSM),  // sfix32_En30
                                   .dinVldSM(dinVldSM)
                                   );

  always @(posedge clk)
    begin : rdCountReverse_process
      if (rst_n == 1'b0) begin
        rdCountReverse_1 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdCountReverse_1 <= nextDelayLineRdAddrReverse;
        end
      end
    end

  always @(posedge clk)
    begin : wrCount_process
      if (rst_n == 1'b0) begin
        wrCount_1 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrCount_1 <= nextDelayLineWrAddr;
        end
      end
    end

  always @(posedge clk)
    begin : rdCount_process
      if (rst_n == 1'b0) begin
        rdCount_1 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdCount_1 <= nextDelayLineRdAddr;
        end
      end
    end

  always @(posedge clk)
    begin : sharingCount_process
      if (rst_n == 1'b0) begin
        sharingCount_1 <= 2'b00;
      end
      else begin
        if (enb) begin
          sharingCount_1 <= nextSharingCount;
        end
      end
    end

  // Input control counter combinatorial logic
  always @(dinVldSM, rdCountReverse_1, rdCount_1, sharingCount_1, wrCount_1) begin
    delayLineValidInP = (sharingCount_1 == 2'b00) && (dinVldSM == 1'b1);
    lastPhaseStrobe = sharingCount_1 == 2'b11;
    if ((dinVldSM == 1'b1) || (sharingCount_1 > 2'b00)) begin
      if (sharingCount_1 == 2'b11) begin
        nextSharingCount = 2'b00;
      end
      else begin
        nextSharingCount = sharingCount_1 + 2'b01;
      end
    end
    else begin
      nextSharingCount = sharingCount_1;
    end
    if (dinVldSM == 1'b1) begin
      if (wrCount_1 == 2'b11) begin
        InputControl_out4_0 = 2'b00;
      end
      else begin
        InputControl_out4_0 = wrCount_1 + 2'b01;
      end
    end
    else begin
      InputControl_out4_0 = wrCount_1;
    end
    if ((rdCount_1 != InputControl_out4_0) || (dinVldSM == 1'b1)) begin
      if (rdCount_1 == 2'b00) begin
        nextDelayLineRdAddr = 2'b11;
      end
      else begin
        nextDelayLineRdAddr = rdCount_1 - 2'b01;
      end
    end
    else begin
      nextDelayLineRdAddr = rdCount_1;
    end
    if ((sharingCount_1 > 2'b00) || (dinVldSM == 1'b1)) begin
      if (sharingCount_1 == 2'b11) begin
        if (wrCount_1 == 2'b11) begin
          nextDelayLineRdAddrReverse = 2'b00;
        end
        else begin
          nextDelayLineRdAddrReverse = wrCount_1 + 2'b01;
        end
      end
      else if (rdCountReverse_1 == 2'b11) begin
        nextDelayLineRdAddrReverse = 2'b00;
      end
      else begin
        nextDelayLineRdAddrReverse = rdCountReverse_1 + 2'b01;
      end
    end
    else begin
      nextDelayLineRdAddrReverse = rdCountReverse_1;
    end
    nextDelayLineWrAddr = InputControl_out4_0;
  end

  always @(posedge clk)
    begin : delayLineShiftEn0_process
      if (rst_n == 1'b0) begin
        delayLineShiftEnP <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEnP <= lastPhaseStrobe;
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn1_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEn1_1 <= delayLineShiftEnP;
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn2_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn2_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn2_1 <= delayLineShiftEn1_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn3_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn3_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn3_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn3_1 <= delayLineShiftEn2_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn4_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn4_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn4_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn4_1 <= delayLineShiftEn3_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn5_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn5_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn5_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn5_1 <= delayLineShiftEn4_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn6_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn6_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn6_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn6_1 <= delayLineShiftEn5_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn7_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn7_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn7_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn7_1 <= delayLineShiftEn6_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn8_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn8_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn8_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn8_1 <= delayLineShiftEn7_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn9_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn9_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn9_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn9_1 <= delayLineShiftEn8_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn10_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn10_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn10_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn10_1 <= delayLineShiftEn9_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn11_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn11_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn11_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn11_1 <= delayLineShiftEn10_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn12_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn12_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn12_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn12_1 <= delayLineShiftEn11_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn13_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn13_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn13_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn13_1 <= delayLineShiftEn12_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : validOutLookahead_process
      if (rst_n == 1'b0) begin
        validOutLookahead_reg <= {7{1'b0}};
      end
      else begin
        if (enb) begin
          validOutLookahead_reg[0] <= delayLineShiftEn13_1;
          validOutLookahead_reg[32'sd6:32'sd1] <= validOutLookahead_reg[32'sd5:32'sd0];
        end
      end
    end

  assign validOutLookahead_1 = validOutLookahead_reg[6];

  always @(posedge clk)
    begin : vldOut_process
      if (rst_n == 1'b0) begin
        vldOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          vldOut_1 <= validOutLookahead_1;
        end
      end
    end

  assign notValid =  ~ vldOut_1;

  always @(posedge clk)
    begin : rdAddr0_process
      if (rst_n == 1'b0) begin
        rdAddr0_1 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr0_1 <= sharingCount_1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr0_2_process
      if (rst_n == 1'b0) begin
        rdAddr1 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr1 <= rdAddr0_1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr1_1_process
      if (rst_n == 1'b0) begin
        rdAddr2 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr2 <= rdAddr1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr2_1_process
      if (rst_n == 1'b0) begin
        rdAddr3 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr3 <= rdAddr2;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr3_1_process
      if (rst_n == 1'b0) begin
        rdAddr4 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr4 <= rdAddr3;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr4_1_process
      if (rst_n == 1'b0) begin
        rdAddr5 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr5 <= rdAddr4;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr5_1_process
      if (rst_n == 1'b0) begin
        rdAddr6 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr6 <= rdAddr5;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr6_1_process
      if (rst_n == 1'b0) begin
        rdAddr7 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr7 <= rdAddr6;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr7_1_process
      if (rst_n == 1'b0) begin
        rdAddr8 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr8 <= rdAddr7;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr8_1_process
      if (rst_n == 1'b0) begin
        rdAddr9 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr9 <= rdAddr8;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr9_1_process
      if (rst_n == 1'b0) begin
        rdAddr10 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr10 <= rdAddr9;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr10_1_process
      if (rst_n == 1'b0) begin
        rdAddr11 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr11 <= rdAddr10;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr11_1_process
      if (rst_n == 1'b0) begin
        rdAddr12 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr12 <= rdAddr11;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr12_1_process
      if (rst_n == 1'b0) begin
        rdAddr13 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr13 <= rdAddr12;
        end
      end
    end

  assign rdAddrEndNonZero = rdAddr13 != 2'b00;

  assign rdAddrEndZero =  ~ rdAddrEndNonZero;

  always @(posedge clk)
    begin : finalSumValidPipe_process
      if (rst_n == 1'b0) begin
        finalSumValidPipe_reg <= {5{1'b0}};
      end
      else begin
        if (enb) begin
          finalSumValidPipe_reg[0] <= rdAddrEndZero;
          finalSumValidPipe_reg[32'sd4:32'sd1] <= finalSumValidPipe_reg[32'sd3:32'sd0];
        end
      end
    end

  assign accumulate = finalSumValidPipe_reg[4];

  assign accDataOut = 64'sh0000000000000000;

  always @(posedge clk)
    begin : wrAddr_process
      if (rst_n == 1'b0) begin
        wrAddrP <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddrP <= wrCount_1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine0 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine0 <= rdCount_1;
        end
      end
    end

  Addressable_Delay_Line_block1 u_delayLine0 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(dinSM),  // sfix32_En30
                                              .wrEn(delayLineValidInP),
                                              .wrAddr(wrAddrP),  // ufix2
                                              .rdAddr(rdAddrDelayLine0),  // ufix2
                                              .delayLineEnd(delayLineEnd0),  // sfix32_En30
                                              .dataOut(delayLineDataOut0deadOut)  // sfix32_En30
                                              );

  always @(posedge clk)
    begin : delayLineDataIn1_process
      if (rst_n == 1'b0) begin
        delayLineDataIn1_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn1_1 <= delayLineEnd0;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr0_process
      if (rst_n == 1'b0) begin
        wrAddr1 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr1 <= wrAddrP;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine0_1_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine1 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine1 <= rdAddrDelayLine0;
        end
      end
    end

  Addressable_Delay_Line_block1 u_delayLine1 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn1_1),  // sfix32_En30
                                              .wrEn(delayLineShiftEn1_1),
                                              .wrAddr(wrAddr1),  // ufix2
                                              .rdAddr(rdAddrDelayLine1),  // ufix2
                                              .delayLineEnd(delayLineEnd1),  // sfix32_En30
                                              .dataOut(delayLineDataOut1)  // sfix32_En30
                                              );

  always @(posedge clk)
    begin : delayLineDataIn2_process
      if (rst_n == 1'b0) begin
        delayLineDataIn2_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn2_1 <= delayLineEnd1;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr1_1_process
      if (rst_n == 1'b0) begin
        wrAddr2 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr2 <= wrAddr1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine1_1_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine2 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine2 <= rdAddrDelayLine1;
        end
      end
    end

  Addressable_Delay_Line_block1 u_delayLine2 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn2_1),  // sfix32_En30
                                              .wrEn(delayLineShiftEn2_1),
                                              .wrAddr(wrAddr2),  // ufix2
                                              .rdAddr(rdAddrDelayLine2),  // ufix2
                                              .delayLineEnd(delayLineEnd2),  // sfix32_En30
                                              .dataOut(delayLineDataOut2)  // sfix32_En30
                                              );

  always @(posedge clk)
    begin : delayLineDataIn3_process
      if (rst_n == 1'b0) begin
        delayLineDataIn3_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn3_1 <= delayLineEnd2;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr2_1_process
      if (rst_n == 1'b0) begin
        wrAddr3 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr3 <= wrAddr2;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine2_1_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine3 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine3 <= rdAddrDelayLine2;
        end
      end
    end

  Addressable_Delay_Line_block1 u_delayLine3 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn3_1),  // sfix32_En30
                                              .wrEn(delayLineShiftEn3_1),
                                              .wrAddr(wrAddr3),  // ufix2
                                              .rdAddr(rdAddrDelayLine3),  // ufix2
                                              .delayLineEnd(delayLineEnd3),  // sfix32_En30
                                              .dataOut(delayLineDataOut3)  // sfix32_En30
                                              );

  always @(posedge clk)
    begin : delayLineDataIn4_process
      if (rst_n == 1'b0) begin
        delayLineDataIn4_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn4_1 <= delayLineEnd3;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr3_1_process
      if (rst_n == 1'b0) begin
        wrAddr4 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr4 <= wrAddr3;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine3_1_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine4 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine4 <= rdAddrDelayLine3;
        end
      end
    end

  Addressable_Delay_Line_block1 u_delayLine4 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn4_1),  // sfix32_En30
                                              .wrEn(delayLineShiftEn4_1),
                                              .wrAddr(wrAddr4),  // ufix2
                                              .rdAddr(rdAddrDelayLine4),  // ufix2
                                              .delayLineEnd(delayLineEnd4),  // sfix32_En30
                                              .dataOut(delayLineDataOut4)  // sfix32_En30
                                              );

  always @(posedge clk)
    begin : delayLineDataIn5_process
      if (rst_n == 1'b0) begin
        delayLineDataIn5_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn5_1 <= delayLineEnd4;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr4_1_process
      if (rst_n == 1'b0) begin
        wrAddr5 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr5 <= wrAddr4;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine4_1_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine5 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine5 <= rdAddrDelayLine4;
        end
      end
    end

  Addressable_Delay_Line_block1 u_delayLine5 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn5_1),  // sfix32_En30
                                              .wrEn(delayLineShiftEn5_1),
                                              .wrAddr(wrAddr5),  // ufix2
                                              .rdAddr(rdAddrDelayLine5),  // ufix2
                                              .delayLineEnd(delayLineEnd5),  // sfix32_En30
                                              .dataOut(delayLineDataOut5)  // sfix32_En30
                                              );

  always @(posedge clk)
    begin : delayLineDataIn6_process
      if (rst_n == 1'b0) begin
        delayLineDataIn6_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn6_1 <= delayLineEnd5;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr5_1_process
      if (rst_n == 1'b0) begin
        wrAddr6 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr6 <= wrAddr5;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine5_1_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine6 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine6 <= rdAddrDelayLine5;
        end
      end
    end

  Addressable_Delay_Line_block1 u_delayLine6 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn6_1),  // sfix32_En30
                                              .wrEn(delayLineShiftEn6_1),
                                              .wrAddr(wrAddr6),  // ufix2
                                              .rdAddr(rdAddrDelayLine6),  // ufix2
                                              .delayLineEnd(delayLineEnd6),  // sfix32_En30
                                              .dataOut(delayLineDataOut6)  // sfix32_En30
                                              );

  always @(posedge clk)
    begin : delayLineDataIn7_process
      if (rst_n == 1'b0) begin
        delayLineDataIn7_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn7_1 <= delayLineEnd6;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr6_1_process
      if (rst_n == 1'b0) begin
        wrAddr7 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr7 <= wrAddr6;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine6_1_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine7 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine7 <= rdAddrDelayLine6;
        end
      end
    end

  Addressable_Delay_Line_block1 u_delayLine7 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn7_1),  // sfix32_En30
                                              .wrEn(delayLineShiftEn7_1),
                                              .wrAddr(wrAddr7),  // ufix2
                                              .rdAddr(rdAddrDelayLine7),  // ufix2
                                              .delayLineEnd(delayLineEnd7),  // sfix32_En30
                                              .dataOut(delayLineDataOut7)  // sfix32_En30
                                              );

  always @(posedge clk)
    begin : delayLineDataIn8_process
      if (rst_n == 1'b0) begin
        delayLineDataIn8_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn8_1 <= delayLineEnd7;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr7_1_process
      if (rst_n == 1'b0) begin
        wrAddr8 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr8 <= wrAddr7;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine7_1_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine8 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine8 <= rdAddrDelayLine7;
        end
      end
    end

  Addressable_Delay_Line_block1 u_delayLine8 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn8_1),  // sfix32_En30
                                              .wrEn(delayLineShiftEn8_1),
                                              .wrAddr(wrAddr8),  // ufix2
                                              .rdAddr(rdAddrDelayLine8),  // ufix2
                                              .delayLineEnd(delayLineEnd8),  // sfix32_En30
                                              .dataOut(delayLineDataOut8)  // sfix32_En30
                                              );

  always @(posedge clk)
    begin : delayLineDataIn9_process
      if (rst_n == 1'b0) begin
        delayLineDataIn9_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn9_1 <= delayLineEnd8;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr8_1_process
      if (rst_n == 1'b0) begin
        wrAddr9 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr9 <= wrAddr8;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine8_1_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine9 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine9 <= rdAddrDelayLine8;
        end
      end
    end

  Addressable_Delay_Line_block1 u_delayLine9 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn9_1),  // sfix32_En30
                                              .wrEn(delayLineShiftEn9_1),
                                              .wrAddr(wrAddr9),  // ufix2
                                              .rdAddr(rdAddrDelayLine9),  // ufix2
                                              .delayLineEnd(delayLineEnd9),  // sfix32_En30
                                              .dataOut(delayLineDataOut9)  // sfix32_En30
                                              );

  always @(posedge clk)
    begin : delayLineDataIn10_process
      if (rst_n == 1'b0) begin
        delayLineDataIn10_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn10_1 <= delayLineEnd9;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr9_1_process
      if (rst_n == 1'b0) begin
        wrAddr10 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr10 <= wrAddr9;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine9_1_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine10 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine10 <= rdAddrDelayLine9;
        end
      end
    end

  Addressable_Delay_Line_block1 u_delayLine10 (.clk(clk),
                                               .rst_n(rst_n),
                                               .enb(enb),
                                               .dataIn(delayLineDataIn10_1),  // sfix32_En30
                                               .wrEn(delayLineShiftEn10_1),
                                               .wrAddr(wrAddr10),  // ufix2
                                               .rdAddr(rdAddrDelayLine10),  // ufix2
                                               .delayLineEnd(delayLineEnd10),  // sfix32_En30
                                               .dataOut(delayLineDataOut10)  // sfix32_En30
                                               );

  always @(posedge clk)
    begin : delayLineDataIn11_process
      if (rst_n == 1'b0) begin
        delayLineDataIn11_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn11_1 <= delayLineEnd10;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr10_1_process
      if (rst_n == 1'b0) begin
        wrAddr11 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr11 <= wrAddr10;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine10_1_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine11 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine11 <= rdAddrDelayLine10;
        end
      end
    end

  Addressable_Delay_Line_block1 u_delayLine11 (.clk(clk),
                                               .rst_n(rst_n),
                                               .enb(enb),
                                               .dataIn(delayLineDataIn11_1),  // sfix32_En30
                                               .wrEn(delayLineShiftEn11_1),
                                               .wrAddr(wrAddr11),  // ufix2
                                               .rdAddr(rdAddrDelayLine11),  // ufix2
                                               .delayLineEnd(delayLineEnd11),  // sfix32_En30
                                               .dataOut(delayLineDataOut11)  // sfix32_En30
                                               );

  always @(posedge clk)
    begin : delayLineDataIn12_process
      if (rst_n == 1'b0) begin
        delayLineDataIn12_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn12_1 <= delayLineEnd11;
        end
      end
    end

  Addressable_Delay_Line_block2 u_delayLine12 (.clk(clk),
                                               .rst_n(rst_n),
                                               .enb(enb),
                                               .dataIn(delayLineDataIn12_1),  // sfix32_En30
                                               .validIn(delayLineShiftEn12_1),
                                               .rdAddr(rdAddr12),  // ufix2
                                               .delayLineEnd(delayLineEnd12),  // sfix32_En30
                                               .dataOut(delayLineDataOut12)  // sfix32_En30
                                               );

  assign preAddIn = 32'sb00000000000000000000000000000000;

  // Coefficient table for multiplier12
  always @(rdAddr12) begin
    case ( rdAddr12)
      2'b00 :
        begin
          coeffTableOut12 = 32'sb01000000000000000000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut12 = 32'sb00000000000000000000000000000000;
        end
      2'b10 :
        begin
          coeffTableOut12 = 32'sb00000000000000000000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut12 = 32'sb00000000000000000000000000000000;
        end
      default :
        begin
          coeffTableOut12 = 32'sb00000000000000000000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP12_process
      if (enb) begin
        coeffTableRegP12_1 <= coeffTableOut12;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg12_process
      if (rst_n == 1'b0) begin
        coeffTableReg12_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg12_1 <= coeffTableRegP12_1;
        end
      end
    end

  always @(posedge clk)
    begin : delayLineDataIn13_process
      if (rst_n == 1'b0) begin
        delayLineDataIn13_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn13_1 <= delayLineEnd12;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr11_1_process
      if (rst_n == 1'b0) begin
        wrAddr12 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr12 <= wrAddr11;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrReverse0_process
      if (rst_n == 1'b0) begin
        rdAddReverse1 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse1 <= rdCountReverse_1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse1_1_process
      if (rst_n == 1'b0) begin
        rdAddReverse2 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse2 <= rdAddReverse1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse2_1_process
      if (rst_n == 1'b0) begin
        rdAddReverse3 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse3 <= rdAddReverse2;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse3_1_process
      if (rst_n == 1'b0) begin
        rdAddReverse4 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse4 <= rdAddReverse3;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse4_1_process
      if (rst_n == 1'b0) begin
        rdAddReverse5 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse5 <= rdAddReverse4;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse5_1_process
      if (rst_n == 1'b0) begin
        rdAddReverse6 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse6 <= rdAddReverse5;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse6_1_process
      if (rst_n == 1'b0) begin
        rdAddReverse7 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse7 <= rdAddReverse6;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse7_1_process
      if (rst_n == 1'b0) begin
        rdAddReverse8 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse8 <= rdAddReverse7;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse8_1_process
      if (rst_n == 1'b0) begin
        rdAddReverse9 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse9 <= rdAddReverse8;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse9_1_process
      if (rst_n == 1'b0) begin
        rdAddReverse10 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse10 <= rdAddReverse9;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse10_1_process
      if (rst_n == 1'b0) begin
        rdAddReverse11 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse11 <= rdAddReverse10;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse11_1_process
      if (rst_n == 1'b0) begin
        rdAddReverse12 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse12 <= rdAddReverse11;
        end
      end
    end

  Addressable_Delay_Line_block3 u_delayLine13 (.clk(clk),
                                               .rst_n(rst_n),
                                               .enb(enb),
                                               .dataIn(delayLineDataIn13_1),  // sfix32_En30
                                               .validIn(delayLineShiftEn12_1),
                                               .wrAddr(wrAddr12),  // ufix2
                                               .rdAddr(rdAddReverse12),  // ufix2
                                               .delayLineEnd(delayLineEnd13),  // sfix32_En30
                                               .dataOut(delayLineDataOut13)  // sfix32_En30
                                               );

  // Coefficient table for multiplier11
  always @(rdAddr11) begin
    case ( rdAddr11)
      2'b00 :
        begin
          coeffTableOut11 = 32'sb00000000000000000000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut11 = 32'sb11110011001011111110011111100000;
        end
      2'b10 :
        begin
          coeffTableOut11 = 32'sb00000000000000000000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut11 = 32'sb00101000011110110010100011011100;
        end
      default :
        begin
          coeffTableOut11 = 32'sb00000000000000000000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP11_process
      if (enb) begin
        coeffTableRegP11_1 <= coeffTableOut11;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg11_process
      if (rst_n == 1'b0) begin
        coeffTableReg11_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg11_1 <= coeffTableRegP11_1;
        end
      end
    end

  Addressable_Delay_Line_block3 u_delayLine14 (.clk(clk),
                                               .rst_n(rst_n),
                                               .enb(enb),
                                               .dataIn(delayLineEnd13),  // sfix32_En30
                                               .validIn(delayLineShiftEn11_1),
                                               .wrAddr(wrAddr11),  // ufix2
                                               .rdAddr(rdAddReverse11),  // ufix2
                                               .delayLineEnd(delayLineEnd14),  // sfix32_En30
                                               .dataOut(delayLineDataOut14)  // sfix32_En30
                                               );

  // Coefficient table for multiplier10
  always @(rdAddr10) begin
    case ( rdAddr10)
      2'b00 :
        begin
          coeffTableOut10 = 32'sb00000000000000000000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut10 = 32'sb11111011110001000100111111101101;
        end
      2'b10 :
        begin
          coeffTableOut10 = 32'sb00000000000000000000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut10 = 32'sb00000110111011011111111011010100;
        end
      default :
        begin
          coeffTableOut10 = 32'sb00000000000000000000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP10_process
      if (enb) begin
        coeffTableRegP10_1 <= coeffTableOut10;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg10_process
      if (rst_n == 1'b0) begin
        coeffTableReg10_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg10_1 <= coeffTableRegP10_1;
        end
      end
    end

  Addressable_Delay_Line_block3 u_delayLine15 (.clk(clk),
                                               .rst_n(rst_n),
                                               .enb(enb),
                                               .dataIn(delayLineEnd14),  // sfix32_En30
                                               .validIn(delayLineShiftEn10_1),
                                               .wrAddr(wrAddr10),  // ufix2
                                               .rdAddr(rdAddReverse10),  // ufix2
                                               .delayLineEnd(delayLineEnd15),  // sfix32_En30
                                               .dataOut(delayLineDataOut15)  // sfix32_En30
                                               );

  // Coefficient table for multiplier9
  always @(rdAddr9) begin
    case ( rdAddr9)
      2'b00 :
        begin
          coeffTableOut9 = 32'sb00000000000000000000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut9 = 32'sb11111110010100101100010101100110;
        end
      2'b10 :
        begin
          coeffTableOut9 = 32'sb00000000000000000000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut9 = 32'sb00000010101010110101101000010011;
        end
      default :
        begin
          coeffTableOut9 = 32'sb00000000000000000000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP9_process
      if (enb) begin
        coeffTableRegP9_1 <= coeffTableOut9;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg9_process
      if (rst_n == 1'b0) begin
        coeffTableReg9_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg9_1 <= coeffTableRegP9_1;
        end
      end
    end

  Addressable_Delay_Line_block3 u_delayLine16 (.clk(clk),
                                               .rst_n(rst_n),
                                               .enb(enb),
                                               .dataIn(delayLineEnd15),  // sfix32_En30
                                               .validIn(delayLineShiftEn9_1),
                                               .wrAddr(wrAddr9),  // ufix2
                                               .rdAddr(rdAddReverse9),  // ufix2
                                               .delayLineEnd(delayLineEnd16),  // sfix32_En30
                                               .dataOut(delayLineDataOut16)  // sfix32_En30
                                               );

  // Coefficient table for multiplier8
  always @(rdAddr8) begin
    case ( rdAddr8)
      2'b00 :
        begin
          coeffTableOut8 = 32'sb00000000000000000000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut8 = 32'sb11111111011000110111101100111010;
        end
      2'b10 :
        begin
          coeffTableOut8 = 32'sb00000000000000000000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut8 = 32'sb00000001000001111010000111110111;
        end
      default :
        begin
          coeffTableOut8 = 32'sb00000000000000000000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP8_process
      if (enb) begin
        coeffTableRegP8_1 <= coeffTableOut8;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg8_process
      if (rst_n == 1'b0) begin
        coeffTableReg8_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg8_1 <= coeffTableRegP8_1;
        end
      end
    end

  Addressable_Delay_Line_block3 u_delayLine17 (.clk(clk),
                                               .rst_n(rst_n),
                                               .enb(enb),
                                               .dataIn(delayLineEnd16),  // sfix32_En30
                                               .validIn(delayLineShiftEn8_1),
                                               .wrAddr(wrAddr8),  // ufix2
                                               .rdAddr(rdAddReverse8),  // ufix2
                                               .delayLineEnd(delayLineEnd17),  // sfix32_En30
                                               .dataOut(delayLineDataOut17)  // sfix32_En30
                                               );

  // Coefficient table for multiplier7
  always @(rdAddr7) begin
    case ( rdAddr7)
      2'b00 :
        begin
          coeffTableOut7 = 32'sb00000000000000000000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut7 = 32'sb11111111110011111011110000000010;
        end
      2'b10 :
        begin
          coeffTableOut7 = 32'sb00000000000000000000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut7 = 32'sb00000000010110010001001111110010;
        end
      default :
        begin
          coeffTableOut7 = 32'sb00000000000000000000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP7_process
      if (enb) begin
        coeffTableRegP7_1 <= coeffTableOut7;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg7_process
      if (rst_n == 1'b0) begin
        coeffTableReg7_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg7_1 <= coeffTableRegP7_1;
        end
      end
    end

  Addressable_Delay_Line_block3 u_delayLine18 (.clk(clk),
                                               .rst_n(rst_n),
                                               .enb(enb),
                                               .dataIn(delayLineEnd17),  // sfix32_En30
                                               .validIn(delayLineShiftEn7_1),
                                               .wrAddr(wrAddr7),  // ufix2
                                               .rdAddr(rdAddReverse7),  // ufix2
                                               .delayLineEnd(delayLineEnd18),  // sfix32_En30
                                               .dataOut(delayLineDataOut18)  // sfix32_En30
                                               );

  // Coefficient table for multiplier6
  always @(rdAddr6) begin
    case ( rdAddr6)
      2'b00 :
        begin
          coeffTableOut6 = 32'sb00000000000000000000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut6 = 32'sb11111111111101000001001101000010;
        end
      2'b10 :
        begin
          coeffTableOut6 = 32'sb00000000000000000000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut6 = 32'sb00000000000110001011111000010000;
        end
      default :
        begin
          coeffTableOut6 = 32'sb00000000000000000000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP6_process
      if (enb) begin
        coeffTableRegP6_1 <= coeffTableOut6;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg6_process
      if (rst_n == 1'b0) begin
        coeffTableReg6_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg6_1 <= coeffTableRegP6_1;
        end
      end
    end

  Addressable_Delay_Line_block3 u_delayLine19 (.clk(clk),
                                               .rst_n(rst_n),
                                               .enb(enb),
                                               .dataIn(delayLineEnd18),  // sfix32_En30
                                               .validIn(delayLineShiftEn6_1),
                                               .wrAddr(wrAddr6),  // ufix2
                                               .rdAddr(rdAddReverse6),  // ufix2
                                               .delayLineEnd(delayLineEnd19),  // sfix32_En30
                                               .dataOut(delayLineDataOut19)  // sfix32_En30
                                               );

  // Coefficient table for multiplier5
  always @(rdAddr5) begin
    case ( rdAddr5)
      2'b00 :
        begin
          coeffTableOut5 = 32'sb00000000000000000000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut5 = 32'sb11111111111111011100001011111111;
        end
      2'b10 :
        begin
          coeffTableOut5 = 32'sb00000000000000000000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut5 = 32'sb00000000000001010101110111101011;
        end
      default :
        begin
          coeffTableOut5 = 32'sb00000000000000000000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP5_process
      if (enb) begin
        coeffTableRegP5_1 <= coeffTableOut5;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg5_process
      if (rst_n == 1'b0) begin
        coeffTableReg5_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg5_1 <= coeffTableRegP5_1;
        end
      end
    end

  Addressable_Delay_Line_block3 u_delayLine20 (.clk(clk),
                                               .rst_n(rst_n),
                                               .enb(enb),
                                               .dataIn(delayLineEnd19),  // sfix32_En30
                                               .validIn(delayLineShiftEn5_1),
                                               .wrAddr(wrAddr5),  // ufix2
                                               .rdAddr(rdAddReverse5),  // ufix2
                                               .delayLineEnd(delayLineEnd20),  // sfix32_En30
                                               .dataOut(delayLineDataOut20)  // sfix32_En30
                                               );

  // Coefficient table for multiplier4
  always @(rdAddr4) begin
    case ( rdAddr4)
      2'b00 :
        begin
          coeffTableOut4 = 32'sb00000000000000000000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut4 = 32'sb11111111111111111011001110110000;
        end
      2'b10 :
        begin
          coeffTableOut4 = 32'sb00000000000000000000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut4 = 32'sb00000000000000001101101101110010;
        end
      default :
        begin
          coeffTableOut4 = 32'sb00000000000000000000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP4_process
      if (enb) begin
        coeffTableRegP4_1 <= coeffTableOut4;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg4_process
      if (rst_n == 1'b0) begin
        coeffTableReg4_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg4_1 <= coeffTableRegP4_1;
        end
      end
    end

  Addressable_Delay_Line_block3 u_delayLine21 (.clk(clk),
                                               .rst_n(rst_n),
                                               .enb(enb),
                                               .dataIn(delayLineEnd20),  // sfix32_En30
                                               .validIn(delayLineShiftEn4_1),
                                               .wrAddr(wrAddr4),  // ufix2
                                               .rdAddr(rdAddReverse4),  // ufix2
                                               .delayLineEnd(delayLineEnd21),  // sfix32_En30
                                               .dataOut(delayLineDataOut21)  // sfix32_En30
                                               );

  // Coefficient table for multiplier3
  always @(rdAddr3) begin
    case ( rdAddr3)
      2'b00 :
        begin
          coeffTableOut3 = 32'sb00000000000000000000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut3 = 32'sb11111111111111111111100110000001;
        end
      2'b10 :
        begin
          coeffTableOut3 = 32'sb00000000000000000000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut3 = 32'sb00000000000000000001011111000010;
        end
      default :
        begin
          coeffTableOut3 = 32'sb00000000000000000000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP3_process
      if (enb) begin
        coeffTableRegP3_1 <= coeffTableOut3;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg3_process
      if (rst_n == 1'b0) begin
        coeffTableReg3_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg3_1 <= coeffTableRegP3_1;
        end
      end
    end

  Addressable_Delay_Line_block3 u_delayLine22 (.clk(clk),
                                               .rst_n(rst_n),
                                               .enb(enb),
                                               .dataIn(delayLineEnd21),  // sfix32_En30
                                               .validIn(delayLineShiftEn3_1),
                                               .wrAddr(wrAddr3),  // ufix2
                                               .rdAddr(rdAddReverse3),  // ufix2
                                               .delayLineEnd(delayLineEnd22),  // sfix32_En30
                                               .dataOut(delayLineDataOut22)  // sfix32_En30
                                               );

  // Coefficient table for multiplier2
  always @(rdAddr2) begin
    case ( rdAddr2)
      2'b00 :
        begin
          coeffTableOut2 = 32'sb00000000000000000000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut2 = 32'sb11111111111111111111111110110101;
        end
      2'b10 :
        begin
          coeffTableOut2 = 32'sb00000000000000000000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut2 = 32'sb00000000000000000000000110000101;
        end
      default :
        begin
          coeffTableOut2 = 32'sb00000000000000000000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP2_process
      if (enb) begin
        coeffTableRegP2_1 <= coeffTableOut2;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg2_process
      if (rst_n == 1'b0) begin
        coeffTableReg2_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg2_1 <= coeffTableRegP2_1;
        end
      end
    end

  Addressable_Delay_Line_block3 u_delayLine23 (.clk(clk),
                                               .rst_n(rst_n),
                                               .enb(enb),
                                               .dataIn(delayLineEnd22),  // sfix32_En30
                                               .validIn(delayLineShiftEn2_1),
                                               .wrAddr(wrAddr2),  // ufix2
                                               .rdAddr(rdAddReverse2),  // ufix2
                                               .delayLineEnd(delayLineEnd23deadOut),  // sfix32_En30
                                               .dataOut(delayLineDataOut23)  // sfix32_En30
                                               );

  // Coefficient table for multiplier1
  always @(rdAddr1) begin
    case ( rdAddr1)
      2'b00 :
        begin
          coeffTableOut1 = 32'sb00000000000000000000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut1 = 32'sb11111111111111111111111111111111;
        end
      2'b10 :
        begin
          coeffTableOut1 = 32'sb00000000000000000000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut1 = 32'sb00000000000000000000000000001011;
        end
      default :
        begin
          coeffTableOut1 = 32'sb00000000000000000000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP1_process
      if (enb) begin
        coeffTableRegP1_1 <= coeffTableOut1;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg1_process
      if (rst_n == 1'b0) begin
        coeffTableReg1_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg1_1 <= coeffTableRegP1_1;
        end
      end
    end

  assign sumIn = 64'sh0000000000000000;

  always @(posedge clk)
    begin : filterDelay_process
      if (rst_n == 1'b0) begin
        sumOut <= 64'sh0000000000000000;
      end
      else begin
        if (enb) begin
          sumOut <= sumIn;
        end
      end
    end

  FilterTapSystolicPreAdd_block u_filterTap1 (.clk(clk),
                                              .enb(enb),
                                              .din_re(delayLineDataOut1),  // sfix32_En30
                                              .preAddIn(delayLineDataOut23),  // sfix32_En30
                                              .coeff(coeffTableReg1_1),  // sfix32_En31
                                              .sumIn(sumOut),  // sfix64_En61
                                              .sumOut(sumOut_0)  // sfix64_En61
                                              );

  FilterTapSystolicPreAdd_block u_filterTap2 (.clk(clk),
                                              .enb(enb),
                                              .din_re(delayLineDataOut2),  // sfix32_En30
                                              .preAddIn(delayLineDataOut22),  // sfix32_En30
                                              .coeff(coeffTableReg2_1),  // sfix32_En31
                                              .sumIn(sumOut_0),  // sfix64_En61
                                              .sumOut(sumOut_1)  // sfix64_En61
                                              );

  FilterTapSystolicPreAdd_block u_filterTap3 (.clk(clk),
                                              .enb(enb),
                                              .din_re(delayLineDataOut3),  // sfix32_En30
                                              .preAddIn(delayLineDataOut21),  // sfix32_En30
                                              .coeff(coeffTableReg3_1),  // sfix32_En31
                                              .sumIn(sumOut_1),  // sfix64_En61
                                              .sumOut(sumOut_2)  // sfix64_En61
                                              );

  FilterTapSystolicPreAdd_block u_filterTap4 (.clk(clk),
                                              .enb(enb),
                                              .din_re(delayLineDataOut4),  // sfix32_En30
                                              .preAddIn(delayLineDataOut20),  // sfix32_En30
                                              .coeff(coeffTableReg4_1),  // sfix32_En31
                                              .sumIn(sumOut_2),  // sfix64_En61
                                              .sumOut(sumOut_3)  // sfix64_En61
                                              );

  FilterTapSystolicPreAdd_block u_filterTap5 (.clk(clk),
                                              .enb(enb),
                                              .din_re(delayLineDataOut5),  // sfix32_En30
                                              .preAddIn(delayLineDataOut19),  // sfix32_En30
                                              .coeff(coeffTableReg5_1),  // sfix32_En31
                                              .sumIn(sumOut_3),  // sfix64_En61
                                              .sumOut(sumOut_4)  // sfix64_En61
                                              );

  FilterTapSystolicPreAdd_block u_filterTap6 (.clk(clk),
                                              .enb(enb),
                                              .din_re(delayLineDataOut6),  // sfix32_En30
                                              .preAddIn(delayLineDataOut18),  // sfix32_En30
                                              .coeff(coeffTableReg6_1),  // sfix32_En31
                                              .sumIn(sumOut_4),  // sfix64_En61
                                              .sumOut(sumOut_5)  // sfix64_En61
                                              );

  FilterTapSystolicPreAdd_block u_filterTap7 (.clk(clk),
                                              .enb(enb),
                                              .din_re(delayLineDataOut7),  // sfix32_En30
                                              .preAddIn(delayLineDataOut17),  // sfix32_En30
                                              .coeff(coeffTableReg7_1),  // sfix32_En31
                                              .sumIn(sumOut_5),  // sfix64_En61
                                              .sumOut(sumOut_6)  // sfix64_En61
                                              );

  FilterTapSystolicPreAdd_block u_filterTap8 (.clk(clk),
                                              .enb(enb),
                                              .din_re(delayLineDataOut8),  // sfix32_En30
                                              .preAddIn(delayLineDataOut16),  // sfix32_En30
                                              .coeff(coeffTableReg8_1),  // sfix32_En31
                                              .sumIn(sumOut_6),  // sfix64_En61
                                              .sumOut(sumOut_7)  // sfix64_En61
                                              );

  FilterTapSystolicPreAdd_block u_filterTap9 (.clk(clk),
                                              .enb(enb),
                                              .din_re(delayLineDataOut9),  // sfix32_En30
                                              .preAddIn(delayLineDataOut15),  // sfix32_En30
                                              .coeff(coeffTableReg9_1),  // sfix32_En31
                                              .sumIn(sumOut_7),  // sfix64_En61
                                              .sumOut(sumOut_8)  // sfix64_En61
                                              );

  FilterTapSystolicPreAdd_block u_filterTap10 (.clk(clk),
                                               .enb(enb),
                                               .din_re(delayLineDataOut10),  // sfix32_En30
                                               .preAddIn(delayLineDataOut14),  // sfix32_En30
                                               .coeff(coeffTableReg10_1),  // sfix32_En31
                                               .sumIn(sumOut_8),  // sfix64_En61
                                               .sumOut(sumOut_9)  // sfix64_En61
                                               );

  FilterTapSystolicPreAdd_block u_filterTap11 (.clk(clk),
                                               .enb(enb),
                                               .din_re(delayLineDataOut11),  // sfix32_En30
                                               .preAddIn(delayLineDataOut13),  // sfix32_En30
                                               .coeff(coeffTableReg11_1),  // sfix32_En31
                                               .sumIn(sumOut_9),  // sfix64_En61
                                               .sumOut(sumOut_10)  // sfix64_En61
                                               );

  FilterTapSystolicPreAdd_block u_filterTap12 (.clk(clk),
                                               .enb(enb),
                                               .din_re(delayLineDataOut12),  // sfix32_En30
                                               .preAddIn(preAddIn),  // sfix32_En30
                                               .coeff(coeffTableReg12_1),  // sfix32_En31
                                               .sumIn(sumOut_10),  // sfix64_En61
                                               .sumOut(sumOut_11)  // sfix64_En61
                                               );

  always @(posedge clk)
    begin : sumOutReg_process
      if (rst_n == 1'b0) begin
        sumOutReg_1 <= 64'sh0000000000000000;
      end
      else begin
        if (enb) begin
          sumOutReg_1 <= sumOut_11;
        end
      end
    end

  assign accSwitchOut = (accumulate == 1'b0 ? accDataOut_1 :
              accDataOut);

  assign accAdderOut = accSwitchOut + sumOutReg_1;

  always @(posedge clk)
    begin : accDataOut_2_process
      if (rst_n == 1'b0) begin
        accDataOut_1 <= 64'sh0000000000000000;
      end
      else begin
        if (enb) begin
          accDataOut_1 <= accAdderOut;
        end
      end
    end

  assign converterOut = accDataOut_1[61:46];

  always @(posedge clk)
    begin : converterOutReg_process
      if (rst_n == 1'b0) begin
        dataOutRegIn <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          dataOutRegIn <= converterOut;
        end
      end
    end

  always @(posedge clk)
    begin : dout_re_process
      if (rst_n == 1'b0) begin
        dout_re_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && validOutLookahead_1) begin
          dout_re_1 <= dataOutRegIn;
        end
      end
    end

  assign dataZero = 16'sb0000000000000000;

  assign dataOut = (notValid == 1'b0 ? dout_re_1 :
              dataZero);

  assign validOut = vldOut_1;

endmodule  // Halfband_Filter_1

