// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC\Halfband_Filter_2.v
// Created: 2024-12-28 19:00:54
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Halfband_Filter_2
// Source Path: DUC/DUC_module/Halfband Filter 2
// Hierarchy Level: 1
// Model version: 3.19
// 
// Discrete FIR Filter
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Halfband_Filter_2
          (clk,
           rst_n,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   rst_n;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  output  signed [15:0] dataOut;  // sfix16_En15
  output  validOut;


  wire syncReset;


  assign syncReset = 1'b0;

  Filter_block u_FilterBank (.clk(clk),
                             .rst_n(rst_n),
                             .enb(enb),
                             .dataIn(dataIn),  // sfix16_En15
                             .validIn(validIn),
                             .syncReset(syncReset),
                             .dataOut(dataOut),  // sfix16_En15
                             .validOut(validOut)
                             );

endmodule  // Halfband_Filter_2

