// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC\Halfband_Filter_2.v
// Created: 2025-01-02 14:32:56
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Halfband_Filter_2
// Source Path: DUC/DUC_module/Halfband Filter 2
// Hierarchy Level: 1
// Model version: 3.26
// 
// Discrete FIR Filter
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Halfband_Filter_2
          (clk,
           rst_n,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   rst_n;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  output  signed [15:0] dataOut;  // sfix16_En15
  output  validOut;


  wire signed [15:0] coeff;  // sfix16_En15
  wire haltProcess;
  wire signed [15:0] dinSM;  // sfix16_En15
  wire dinVldSM;
  reg [1:0] nextDelayLineRdAddrReverse;  // ufix2
  reg [1:0] rdCountReverse_1;  // ufix2
  reg [1:0] nextDelayLineWrAddr;  // ufix2
  reg [1:0] wrCount_1;  // ufix2
  reg [1:0] nextDelayLineRdAddr;  // ufix2
  reg [1:0] rdCount_1;  // ufix2
  reg [1:0] nextSharingCount;  // ufix2
  reg [1:0] sharingCount_1;  // ufix2
  reg  delayLineValidInP;
  reg  lastPhaseStrobe;
  reg  delayLineShiftEnP;
  reg  delayLineShiftEn1_1;
  wire syncResetRst;
  reg  delayLineShiftEn2_1;
  reg  delayLineShiftEn3_1;
  reg  delayLineShiftEn4_1;
  reg  delayLineShiftEn5_1;
  reg  delayLineShiftEn6_1;
  reg  delayLineShiftEn7_1;
  reg  [6:0] validOutLookahead_reg;  // ufix1 [7]
  wire validOutLookahead_1;
  reg  vldOut_1;
  wire notValid;
  reg [1:0] rdAddr0_1;  // ufix2
  reg [1:0] rdAddr1;  // ufix2
  reg [1:0] rdAddr2;  // ufix2
  reg [1:0] rdAddr3;  // ufix2
  reg [1:0] rdAddr4;  // ufix2
  reg [1:0] rdAddr5;  // ufix2
  reg [1:0] rdAddr6;  // ufix2
  reg [1:0] rdAddr7;  // ufix2
  wire rdAddrEndNonZero;
  wire rdAddrEndZero;
  reg  [5:0] finalSumValidPipe_reg;  // ufix1 [6]
  wire accumulate;
  wire signed [31:0] accDataOut;  // sfix32_En30
  reg [1:0] wrAddrP;  // ufix2
  reg [1:0] rdAddrDelayLine0;  // ufix2
  wire signed [15:0] delayLineEnd0;  // sfix16_En15
  wire signed [15:0] delayLineDataOut0;  // sfix16_En15
  reg signed [15:0] delayLineDataIn1_1;  // sfix16_En15
  reg [1:0] wrAddr1;  // ufix2
  reg [1:0] rdAddrDelayLine1;  // ufix2
  wire signed [15:0] delayLineEnd1;  // sfix16_En15
  wire signed [15:0] delayLineDataOut1;  // sfix16_En15
  reg signed [15:0] delayLineDataIn2_1;  // sfix16_En15
  reg [1:0] wrAddr2;  // ufix2
  reg [1:0] rdAddrDelayLine2;  // ufix2
  wire signed [15:0] delayLineEnd2;  // sfix16_En15
  wire signed [15:0] delayLineDataOut2;  // sfix16_En15
  reg signed [15:0] delayLineDataIn3_1;  // sfix16_En15
  reg [1:0] wrAddr3;  // ufix2
  reg [1:0] rdAddrDelayLine3;  // ufix2
  wire signed [15:0] delayLineEnd3;  // sfix16_En15
  wire signed [15:0] delayLineDataOut3;  // sfix16_En15
  reg signed [15:0] delayLineDataIn4_1;  // sfix16_En15
  reg [1:0] wrAddr4;  // ufix2
  reg [1:0] rdAddrDelayLine4;  // ufix2
  wire signed [15:0] delayLineEnd4;  // sfix16_En15
  wire signed [15:0] delayLineDataOut4;  // sfix16_En15
  reg signed [15:0] delayLineDataIn5_1;  // sfix16_En15
  reg [1:0] wrAddr5;  // ufix2
  reg [1:0] rdAddrDelayLine5;  // ufix2
  wire signed [15:0] delayLineEnd5;  // sfix16_En15
  wire signed [15:0] delayLineDataOut5;  // sfix16_En15
  reg signed [15:0] delayLineDataIn6_1;  // sfix16_En15
  wire signed [15:0] delayLineEnd6;  // sfix16_En15
  wire signed [15:0] delayLineDataOut6;  // sfix16_En15
  wire signed [15:0] preAddIn;  // sfix16_En15
  reg signed [15:0] coeffTableOut6;  // sfix16_En15
  reg signed [15:0] coeffTableRegP6_1;  // sfix16_En15
  reg signed [15:0] coeffTableReg6_1;  // sfix16_En15
  reg signed [15:0] delayLineDataIn7_1;  // sfix16_En15
  reg [1:0] wrAddr6;  // ufix2
  reg [1:0] rdAddReverse1;  // ufix2
  reg [1:0] rdAddReverse2;  // ufix2
  reg [1:0] rdAddReverse3;  // ufix2
  reg [1:0] rdAddReverse4;  // ufix2
  reg [1:0] rdAddReverse5;  // ufix2
  reg [1:0] rdAddReverse6;  // ufix2
  wire signed [15:0] delayLineEnd7;  // sfix16_En15
  wire signed [15:0] delayLineDataOut7;  // sfix16_En15
  reg signed [15:0] coeffTableOut5;  // sfix16_En15
  reg signed [15:0] coeffTableRegP5_1;  // sfix16_En15
  reg signed [15:0] coeffTableReg5_1;  // sfix16_En15
  wire signed [15:0] delayLineEnd8;  // sfix16_En15
  wire signed [15:0] delayLineDataOut8;  // sfix16_En15
  reg signed [15:0] coeffTableOut4;  // sfix16_En15
  reg signed [15:0] coeffTableRegP4_1;  // sfix16_En15
  reg signed [15:0] coeffTableReg4_1;  // sfix16_En15
  wire signed [15:0] delayLineEnd9;  // sfix16_En15
  wire signed [15:0] delayLineDataOut9;  // sfix16_En15
  reg signed [15:0] coeffTableOut3;  // sfix16_En15
  reg signed [15:0] coeffTableRegP3_1;  // sfix16_En15
  reg signed [15:0] coeffTableReg3_1;  // sfix16_En15
  wire signed [15:0] delayLineEnd10;  // sfix16_En15
  wire signed [15:0] delayLineDataOut10;  // sfix16_En15
  reg signed [15:0] coeffTableOut2;  // sfix16_En15
  reg signed [15:0] coeffTableRegP2_1;  // sfix16_En15
  reg signed [15:0] coeffTableReg2_1;  // sfix16_En15
  wire signed [15:0] delayLineEnd11;  // sfix16_En15
  wire signed [15:0] delayLineDataOut11;  // sfix16_En15
  reg signed [15:0] coeffTableOut1;  // sfix16_En15
  reg signed [15:0] coeffTableRegP1_1;  // sfix16_En15
  reg signed [15:0] coeffTableReg1_1;  // sfix16_En15
  wire signed [15:0] delayLineEnd12deadOut;  // sfix16_En15
  wire signed [15:0] delayLineDataOut12;  // sfix16_En15
  reg signed [15:0] coeffTableOut0;  // sfix16_En15
  reg signed [15:0] coeffTableRegP0_1;  // sfix16_En15
  reg signed [15:0] coeffTableReg0_1;  // sfix16_En15
  wire signed [31:0] sumIn;  // sfix32_En30
  wire signed [31:0] sumOut;  // sfix32_En30
  wire signed [31:0] sumOut_0;  // sfix32_En30
  wire signed [31:0] sumOut_1;  // sfix32_En30
  wire signed [31:0] sumOut_2;  // sfix32_En30
  wire signed [31:0] sumOut_3;  // sfix32_En30
  wire signed [31:0] sumOut_4;  // sfix32_En30
  wire signed [31:0] sumOut_5;  // sfix32_En30
  reg signed [31:0] sumOutReg_1;  // sfix32_En30
  reg signed [31:0] accDataOut_1;  // sfix32_En30
  wire signed [31:0] accSwitchOut;  // sfix32_En30
  wire signed [31:0] accAdderOut;  // sfix32_En30
  wire signed [15:0] converterOut;  // sfix16_En15
  reg signed [15:0] dout_re_1;  // sfix16_En15
  wire signed [15:0] dataZero;  // sfix16_En15
  reg [1:0] InputControl_out4_0;  // ufix2

  initial begin
    coeffTableRegP6_1 = 16'sb0000000000000000;
    coeffTableRegP5_1 = 16'sb0000000000000000;
    coeffTableRegP4_1 = 16'sb0000000000000000;
    coeffTableRegP3_1 = 16'sb0000000000000000;
    coeffTableRegP2_1 = 16'sb0000000000000000;
    coeffTableRegP1_1 = 16'sb0000000000000000;
    coeffTableRegP0_1 = 16'sb0000000000000000;
  end

  assign coeff = 16'sb0000000000000000;

  assign haltProcess = 1'b0;

  FirRdyLogic_block2 u_firRdyLogic (.clk(clk),
                                    .rst_n(rst_n),
                                    .enb(enb),
                                    .dinSwitch(dataIn),  // sfix16_En15
                                    .dinVldSwitch(validIn),
                                    .coeff(coeff),  // sfix16_En15
                                    .haltProcess(haltProcess),
                                    .dinSM(dinSM),  // sfix16_En15
                                    .dinVldSM(dinVldSM)
                                    );

  always @(posedge clk)
    begin : rdCountReverse_process
      if (rst_n == 1'b0) begin
        rdCountReverse_1 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdCountReverse_1 <= nextDelayLineRdAddrReverse;
        end
      end
    end

  always @(posedge clk)
    begin : wrCount_process
      if (rst_n == 1'b0) begin
        wrCount_1 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrCount_1 <= nextDelayLineWrAddr;
        end
      end
    end

  always @(posedge clk)
    begin : rdCount_process
      if (rst_n == 1'b0) begin
        rdCount_1 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdCount_1 <= nextDelayLineRdAddr;
        end
      end
    end

  always @(posedge clk)
    begin : sharingCount_process
      if (rst_n == 1'b0) begin
        sharingCount_1 <= 2'b00;
      end
      else begin
        if (enb) begin
          sharingCount_1 <= nextSharingCount;
        end
      end
    end

  // Input control counter combinatorial logic
  always @(dinVldSM, rdCountReverse_1, rdCount_1, sharingCount_1, wrCount_1) begin
    delayLineValidInP = (sharingCount_1 == 2'b00) && (dinVldSM == 1'b1);
    lastPhaseStrobe = sharingCount_1 == 2'b11;
    if ((dinVldSM == 1'b1) || (sharingCount_1 > 2'b00)) begin
      if (sharingCount_1 == 2'b11) begin
        nextSharingCount = 2'b00;
      end
      else begin
        nextSharingCount = sharingCount_1 + 2'b01;
      end
    end
    else begin
      nextSharingCount = sharingCount_1;
    end
    if (dinVldSM == 1'b1) begin
      if (wrCount_1 == 2'b11) begin
        InputControl_out4_0 = 2'b00;
      end
      else begin
        InputControl_out4_0 = wrCount_1 + 2'b01;
      end
    end
    else begin
      InputControl_out4_0 = wrCount_1;
    end
    if ((rdCount_1 != InputControl_out4_0) || (dinVldSM == 1'b1)) begin
      if (rdCount_1 == 2'b00) begin
        nextDelayLineRdAddr = 2'b11;
      end
      else begin
        nextDelayLineRdAddr = rdCount_1 - 2'b01;
      end
    end
    else begin
      nextDelayLineRdAddr = rdCount_1;
    end
    if ((sharingCount_1 > 2'b00) || (dinVldSM == 1'b1)) begin
      if (sharingCount_1 == 2'b11) begin
        if (wrCount_1 == 2'b11) begin
          nextDelayLineRdAddrReverse = 2'b00;
        end
        else begin
          nextDelayLineRdAddrReverse = wrCount_1 + 2'b01;
        end
      end
      else if (rdCountReverse_1 == 2'b11) begin
        nextDelayLineRdAddrReverse = 2'b00;
      end
      else begin
        nextDelayLineRdAddrReverse = rdCountReverse_1 + 2'b01;
      end
    end
    else begin
      nextDelayLineRdAddrReverse = rdCountReverse_1;
    end
    nextDelayLineWrAddr = InputControl_out4_0;
  end

  always @(posedge clk)
    begin : delayLineShiftEn0_process
      if (rst_n == 1'b0) begin
        delayLineShiftEnP <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEnP <= lastPhaseStrobe;
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn1_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEn1_1 <= delayLineShiftEnP;
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn2_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn2_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn2_1 <= delayLineShiftEn1_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn3_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn3_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn3_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn3_1 <= delayLineShiftEn2_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn4_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn4_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn4_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn4_1 <= delayLineShiftEn3_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn5_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn5_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn5_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn5_1 <= delayLineShiftEn4_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn6_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn6_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn6_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn6_1 <= delayLineShiftEn5_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn7_process
      if (rst_n == 1'b0) begin
        delayLineShiftEn7_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn7_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn7_1 <= delayLineShiftEn6_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : validOutLookahead_process
      if (rst_n == 1'b0) begin
        validOutLookahead_reg <= {7{1'b0}};
      end
      else begin
        if (enb) begin
          validOutLookahead_reg[0] <= delayLineShiftEn7_1;
          validOutLookahead_reg[32'sd6:32'sd1] <= validOutLookahead_reg[32'sd5:32'sd0];
        end
      end
    end

  assign validOutLookahead_1 = validOutLookahead_reg[6];

  always @(posedge clk)
    begin : vldOut_process
      if (rst_n == 1'b0) begin
        vldOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          vldOut_1 <= validOutLookahead_1;
        end
      end
    end

  assign notValid =  ~ vldOut_1;

  always @(posedge clk)
    begin : rdAddr0_process
      if (rst_n == 1'b0) begin
        rdAddr0_1 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr0_1 <= sharingCount_1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr0_2_process
      if (rst_n == 1'b0) begin
        rdAddr1 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr1 <= rdAddr0_1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr1_1_process
      if (rst_n == 1'b0) begin
        rdAddr2 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr2 <= rdAddr1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr2_1_process
      if (rst_n == 1'b0) begin
        rdAddr3 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr3 <= rdAddr2;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr3_1_process
      if (rst_n == 1'b0) begin
        rdAddr4 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr4 <= rdAddr3;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr4_1_process
      if (rst_n == 1'b0) begin
        rdAddr5 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr5 <= rdAddr4;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr5_1_process
      if (rst_n == 1'b0) begin
        rdAddr6 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr6 <= rdAddr5;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr6_1_process
      if (rst_n == 1'b0) begin
        rdAddr7 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddr7 <= rdAddr6;
        end
      end
    end

  assign rdAddrEndNonZero = rdAddr7 != 2'b00;

  assign rdAddrEndZero =  ~ rdAddrEndNonZero;

  always @(posedge clk)
    begin : finalSumValidPipe_process
      if (rst_n == 1'b0) begin
        finalSumValidPipe_reg <= {6{1'b0}};
      end
      else begin
        if (enb) begin
          finalSumValidPipe_reg[0] <= rdAddrEndZero;
          finalSumValidPipe_reg[32'sd5:32'sd1] <= finalSumValidPipe_reg[32'sd4:32'sd0];
        end
      end
    end

  assign accumulate = finalSumValidPipe_reg[5];

  assign accDataOut = 32'sb00000000000000000000000000000000;

  always @(posedge clk)
    begin : wrAddr_process
      if (rst_n == 1'b0) begin
        wrAddrP <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddrP <= wrCount_1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine0 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine0 <= rdCount_1;
        end
      end
    end

  Addressable_Delay_Line_block6 u_delayLine0 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(dinSM),  // sfix16_En15
                                              .wrEn(delayLineValidInP),
                                              .wrAddr(wrAddrP),  // ufix2
                                              .rdAddr(rdAddrDelayLine0),  // ufix2
                                              .delayLineEnd(delayLineEnd0),  // sfix16_En15
                                              .dataOut(delayLineDataOut0)  // sfix16_En15
                                              );

  always @(posedge clk)
    begin : delayLineDataIn1_process
      if (rst_n == 1'b0) begin
        delayLineDataIn1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn1_1 <= delayLineEnd0;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr0_process
      if (rst_n == 1'b0) begin
        wrAddr1 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr1 <= wrAddrP;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine0_1_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine1 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine1 <= rdAddrDelayLine0;
        end
      end
    end

  Addressable_Delay_Line_block6 u_delayLine1 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn1_1),  // sfix16_En15
                                              .wrEn(delayLineShiftEn1_1),
                                              .wrAddr(wrAddr1),  // ufix2
                                              .rdAddr(rdAddrDelayLine1),  // ufix2
                                              .delayLineEnd(delayLineEnd1),  // sfix16_En15
                                              .dataOut(delayLineDataOut1)  // sfix16_En15
                                              );

  always @(posedge clk)
    begin : delayLineDataIn2_process
      if (rst_n == 1'b0) begin
        delayLineDataIn2_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn2_1 <= delayLineEnd1;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr1_1_process
      if (rst_n == 1'b0) begin
        wrAddr2 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr2 <= wrAddr1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine1_1_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine2 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine2 <= rdAddrDelayLine1;
        end
      end
    end

  Addressable_Delay_Line_block6 u_delayLine2 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn2_1),  // sfix16_En15
                                              .wrEn(delayLineShiftEn2_1),
                                              .wrAddr(wrAddr2),  // ufix2
                                              .rdAddr(rdAddrDelayLine2),  // ufix2
                                              .delayLineEnd(delayLineEnd2),  // sfix16_En15
                                              .dataOut(delayLineDataOut2)  // sfix16_En15
                                              );

  always @(posedge clk)
    begin : delayLineDataIn3_process
      if (rst_n == 1'b0) begin
        delayLineDataIn3_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn3_1 <= delayLineEnd2;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr2_1_process
      if (rst_n == 1'b0) begin
        wrAddr3 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr3 <= wrAddr2;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine2_1_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine3 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine3 <= rdAddrDelayLine2;
        end
      end
    end

  Addressable_Delay_Line_block6 u_delayLine3 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn3_1),  // sfix16_En15
                                              .wrEn(delayLineShiftEn3_1),
                                              .wrAddr(wrAddr3),  // ufix2
                                              .rdAddr(rdAddrDelayLine3),  // ufix2
                                              .delayLineEnd(delayLineEnd3),  // sfix16_En15
                                              .dataOut(delayLineDataOut3)  // sfix16_En15
                                              );

  always @(posedge clk)
    begin : delayLineDataIn4_process
      if (rst_n == 1'b0) begin
        delayLineDataIn4_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn4_1 <= delayLineEnd3;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr3_1_process
      if (rst_n == 1'b0) begin
        wrAddr4 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr4 <= wrAddr3;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine3_1_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine4 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine4 <= rdAddrDelayLine3;
        end
      end
    end

  Addressable_Delay_Line_block6 u_delayLine4 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn4_1),  // sfix16_En15
                                              .wrEn(delayLineShiftEn4_1),
                                              .wrAddr(wrAddr4),  // ufix2
                                              .rdAddr(rdAddrDelayLine4),  // ufix2
                                              .delayLineEnd(delayLineEnd4),  // sfix16_En15
                                              .dataOut(delayLineDataOut4)  // sfix16_En15
                                              );

  always @(posedge clk)
    begin : delayLineDataIn5_process
      if (rst_n == 1'b0) begin
        delayLineDataIn5_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn5_1 <= delayLineEnd4;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr4_1_process
      if (rst_n == 1'b0) begin
        wrAddr5 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr5 <= wrAddr4;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine4_1_process
      if (rst_n == 1'b0) begin
        rdAddrDelayLine5 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine5 <= rdAddrDelayLine4;
        end
      end
    end

  Addressable_Delay_Line_block6 u_delayLine5 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn5_1),  // sfix16_En15
                                              .wrEn(delayLineShiftEn5_1),
                                              .wrAddr(wrAddr5),  // ufix2
                                              .rdAddr(rdAddrDelayLine5),  // ufix2
                                              .delayLineEnd(delayLineEnd5),  // sfix16_En15
                                              .dataOut(delayLineDataOut5)  // sfix16_En15
                                              );

  always @(posedge clk)
    begin : delayLineDataIn6_process
      if (rst_n == 1'b0) begin
        delayLineDataIn6_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn6_1 <= delayLineEnd5;
        end
      end
    end

  Addressable_Delay_Line_block7 u_delayLine6 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn6_1),  // sfix16_En15
                                              .validIn(delayLineShiftEn6_1),
                                              .rdAddr(rdAddr6),  // ufix2
                                              .delayLineEnd(delayLineEnd6),  // sfix16_En15
                                              .dataOut(delayLineDataOut6)  // sfix16_En15
                                              );

  assign preAddIn = 16'sb0000000000000000;

  // Coefficient table for multiplier6
  always @(rdAddr6) begin
    case ( rdAddr6)
      2'b00 :
        begin
          coeffTableOut6 = 16'sb0100000000000000;
        end
      2'b01 :
        begin
          coeffTableOut6 = 16'sb0000000000000000;
        end
      2'b10 :
        begin
          coeffTableOut6 = 16'sb0000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut6 = 16'sb0000000000000000;
        end
      default :
        begin
          coeffTableOut6 = 16'sb0000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP6_process
      if (enb) begin
        coeffTableRegP6_1 <= coeffTableOut6;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg6_process
      if (rst_n == 1'b0) begin
        coeffTableReg6_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg6_1 <= coeffTableRegP6_1;
        end
      end
    end

  always @(posedge clk)
    begin : delayLineDataIn7_process
      if (rst_n == 1'b0) begin
        delayLineDataIn7_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn7_1 <= delayLineEnd6;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr5_1_process
      if (rst_n == 1'b0) begin
        wrAddr6 <= 2'b00;
      end
      else begin
        if (enb) begin
          wrAddr6 <= wrAddr5;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrReverse0_process
      if (rst_n == 1'b0) begin
        rdAddReverse1 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse1 <= rdCountReverse_1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse1_1_process
      if (rst_n == 1'b0) begin
        rdAddReverse2 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse2 <= rdAddReverse1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse2_1_process
      if (rst_n == 1'b0) begin
        rdAddReverse3 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse3 <= rdAddReverse2;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse3_1_process
      if (rst_n == 1'b0) begin
        rdAddReverse4 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse4 <= rdAddReverse3;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse4_1_process
      if (rst_n == 1'b0) begin
        rdAddReverse5 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse5 <= rdAddReverse4;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse5_1_process
      if (rst_n == 1'b0) begin
        rdAddReverse6 <= 2'b00;
      end
      else begin
        if (enb) begin
          rdAddReverse6 <= rdAddReverse5;
        end
      end
    end

  Addressable_Delay_Line_block8 u_delayLine7 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn7_1),  // sfix16_En15
                                              .validIn(delayLineShiftEn6_1),
                                              .wrAddr(wrAddr6),  // ufix2
                                              .rdAddr(rdAddReverse6),  // ufix2
                                              .delayLineEnd(delayLineEnd7),  // sfix16_En15
                                              .dataOut(delayLineDataOut7)  // sfix16_En15
                                              );

  // Coefficient table for multiplier5
  always @(rdAddr5) begin
    case ( rdAddr5)
      2'b00 :
        begin
          coeffTableOut5 = 16'sb0000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut5 = 16'sb1111001101111010;
        end
      2'b10 :
        begin
          coeffTableOut5 = 16'sb0000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut5 = 16'sb0010100001100001;
        end
      default :
        begin
          coeffTableOut5 = 16'sb0000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP5_process
      if (enb) begin
        coeffTableRegP5_1 <= coeffTableOut5;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg5_process
      if (rst_n == 1'b0) begin
        coeffTableReg5_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg5_1 <= coeffTableRegP5_1;
        end
      end
    end

  Addressable_Delay_Line_block8 u_delayLine8 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineEnd7),  // sfix16_En15
                                              .validIn(delayLineShiftEn5_1),
                                              .wrAddr(wrAddr5),  // ufix2
                                              .rdAddr(rdAddReverse5),  // ufix2
                                              .delayLineEnd(delayLineEnd8),  // sfix16_En15
                                              .dataOut(delayLineDataOut8)  // sfix16_En15
                                              );

  // Coefficient table for multiplier4
  always @(rdAddr4) begin
    case ( rdAddr4)
      2'b00 :
        begin
          coeffTableOut4 = 16'sb0000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut4 = 16'sb1111110001001000;
        end
      2'b10 :
        begin
          coeffTableOut4 = 16'sb0000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut4 = 16'sb0000011001111111;
        end
      default :
        begin
          coeffTableOut4 = 16'sb0000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP4_process
      if (enb) begin
        coeffTableRegP4_1 <= coeffTableOut4;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg4_process
      if (rst_n == 1'b0) begin
        coeffTableReg4_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg4_1 <= coeffTableRegP4_1;
        end
      end
    end

  Addressable_Delay_Line_block8 u_delayLine9 (.clk(clk),
                                              .rst_n(rst_n),
                                              .enb(enb),
                                              .dataIn(delayLineEnd8),  // sfix16_En15
                                              .validIn(delayLineShiftEn4_1),
                                              .wrAddr(wrAddr4),  // ufix2
                                              .rdAddr(rdAddReverse4),  // ufix2
                                              .delayLineEnd(delayLineEnd9),  // sfix16_En15
                                              .dataOut(delayLineDataOut9)  // sfix16_En15
                                              );

  // Coefficient table for multiplier3
  always @(rdAddr3) begin
    case ( rdAddr3)
      2'b00 :
        begin
          coeffTableOut3 = 16'sb0000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut3 = 16'sb1111111011010001;
        end
      2'b10 :
        begin
          coeffTableOut3 = 16'sb0000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut3 = 16'sb0000001000100011;
        end
      default :
        begin
          coeffTableOut3 = 16'sb0000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP3_process
      if (enb) begin
        coeffTableRegP3_1 <= coeffTableOut3;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg3_process
      if (rst_n == 1'b0) begin
        coeffTableReg3_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg3_1 <= coeffTableRegP3_1;
        end
      end
    end

  Addressable_Delay_Line_block8 u_delayLine10 (.clk(clk),
                                               .rst_n(rst_n),
                                               .enb(enb),
                                               .dataIn(delayLineEnd9),  // sfix16_En15
                                               .validIn(delayLineShiftEn3_1),
                                               .wrAddr(wrAddr3),  // ufix2
                                               .rdAddr(rdAddReverse3),  // ufix2
                                               .delayLineEnd(delayLineEnd10),  // sfix16_En15
                                               .dataOut(delayLineDataOut10)  // sfix16_En15
                                               );

  // Coefficient table for multiplier2
  always @(rdAddr2) begin
    case ( rdAddr2)
      2'b00 :
        begin
          coeffTableOut2 = 16'sb0000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut2 = 16'sb1111111110110101;
        end
      2'b10 :
        begin
          coeffTableOut2 = 16'sb0000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut2 = 16'sb0000000010011101;
        end
      default :
        begin
          coeffTableOut2 = 16'sb0000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP2_process
      if (enb) begin
        coeffTableRegP2_1 <= coeffTableOut2;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg2_process
      if (rst_n == 1'b0) begin
        coeffTableReg2_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg2_1 <= coeffTableRegP2_1;
        end
      end
    end

  Addressable_Delay_Line_block8 u_delayLine11 (.clk(clk),
                                               .rst_n(rst_n),
                                               .enb(enb),
                                               .dataIn(delayLineEnd10),  // sfix16_En15
                                               .validIn(delayLineShiftEn2_1),
                                               .wrAddr(wrAddr2),  // ufix2
                                               .rdAddr(rdAddReverse2),  // ufix2
                                               .delayLineEnd(delayLineEnd11),  // sfix16_En15
                                               .dataOut(delayLineDataOut11)  // sfix16_En15
                                               );

  // Coefficient table for multiplier1
  always @(rdAddr1) begin
    case ( rdAddr1)
      2'b00 :
        begin
          coeffTableOut1 = 16'sb0000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut1 = 16'sb1111111111110101;
        end
      2'b10 :
        begin
          coeffTableOut1 = 16'sb0000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut1 = 16'sb0000000000011111;
        end
      default :
        begin
          coeffTableOut1 = 16'sb0000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP1_process
      if (enb) begin
        coeffTableRegP1_1 <= coeffTableOut1;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg1_process
      if (rst_n == 1'b0) begin
        coeffTableReg1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg1_1 <= coeffTableRegP1_1;
        end
      end
    end

  Addressable_Delay_Line_block8 u_delayLine12 (.clk(clk),
                                               .rst_n(rst_n),
                                               .enb(enb),
                                               .dataIn(delayLineEnd11),  // sfix16_En15
                                               .validIn(delayLineShiftEn1_1),
                                               .wrAddr(wrAddr1),  // ufix2
                                               .rdAddr(rdAddReverse1),  // ufix2
                                               .delayLineEnd(delayLineEnd12deadOut),  // sfix16_En15
                                               .dataOut(delayLineDataOut12)  // sfix16_En15
                                               );

  // Coefficient table for multiplier0
  always @(rdAddr0_1) begin
    case ( rdAddr0_1)
      2'b00 :
        begin
          coeffTableOut0 = 16'sb0000000000000000;
        end
      2'b01 :
        begin
          coeffTableOut0 = 16'sb1111111111111111;
        end
      2'b10 :
        begin
          coeffTableOut0 = 16'sb0000000000000000;
        end
      2'b11 :
        begin
          coeffTableOut0 = 16'sb0000000000000011;
        end
      default :
        begin
          coeffTableOut0 = 16'sb0000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP0_process
      if (enb) begin
        coeffTableRegP0_1 <= coeffTableOut0;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg0_process
      if (rst_n == 1'b0) begin
        coeffTableReg0_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg0_1 <= coeffTableRegP0_1;
        end
      end
    end

  assign sumIn = 32'sb00000000000000000000000000000000;

  FilterTapSystolicPreAdd_block2 u_filterTap0 (.clk(clk),
                                               .enb(enb),
                                               .din_re(delayLineDataOut0),  // sfix16_En15
                                               .preAddIn(delayLineDataOut12),  // sfix16_En15
                                               .coeff(coeffTableReg0_1),  // sfix16_En15
                                               .sumIn(sumIn),  // sfix32_En30
                                               .sumOut(sumOut)  // sfix32_En30
                                               );

  FilterTapSystolicPreAdd_block2 u_filterTap1 (.clk(clk),
                                               .enb(enb),
                                               .din_re(delayLineDataOut1),  // sfix16_En15
                                               .preAddIn(delayLineDataOut11),  // sfix16_En15
                                               .coeff(coeffTableReg1_1),  // sfix16_En15
                                               .sumIn(sumOut),  // sfix32_En30
                                               .sumOut(sumOut_0)  // sfix32_En30
                                               );

  FilterTapSystolicPreAdd_block2 u_filterTap2 (.clk(clk),
                                               .enb(enb),
                                               .din_re(delayLineDataOut2),  // sfix16_En15
                                               .preAddIn(delayLineDataOut10),  // sfix16_En15
                                               .coeff(coeffTableReg2_1),  // sfix16_En15
                                               .sumIn(sumOut_0),  // sfix32_En30
                                               .sumOut(sumOut_1)  // sfix32_En30
                                               );

  FilterTapSystolicPreAdd_block2 u_filterTap3 (.clk(clk),
                                               .enb(enb),
                                               .din_re(delayLineDataOut3),  // sfix16_En15
                                               .preAddIn(delayLineDataOut9),  // sfix16_En15
                                               .coeff(coeffTableReg3_1),  // sfix16_En15
                                               .sumIn(sumOut_1),  // sfix32_En30
                                               .sumOut(sumOut_2)  // sfix32_En30
                                               );

  FilterTapSystolicPreAdd_block2 u_filterTap4 (.clk(clk),
                                               .enb(enb),
                                               .din_re(delayLineDataOut4),  // sfix16_En15
                                               .preAddIn(delayLineDataOut8),  // sfix16_En15
                                               .coeff(coeffTableReg4_1),  // sfix16_En15
                                               .sumIn(sumOut_2),  // sfix32_En30
                                               .sumOut(sumOut_3)  // sfix32_En30
                                               );

  FilterTapSystolicPreAdd_block2 u_filterTap5 (.clk(clk),
                                               .enb(enb),
                                               .din_re(delayLineDataOut5),  // sfix16_En15
                                               .preAddIn(delayLineDataOut7),  // sfix16_En15
                                               .coeff(coeffTableReg5_1),  // sfix16_En15
                                               .sumIn(sumOut_3),  // sfix32_En30
                                               .sumOut(sumOut_4)  // sfix32_En30
                                               );

  FilterTapSystolicPreAdd_block2 u_filterTap6 (.clk(clk),
                                               .enb(enb),
                                               .din_re(delayLineDataOut6),  // sfix16_En15
                                               .preAddIn(preAddIn),  // sfix16_En15
                                               .coeff(coeffTableReg6_1),  // sfix16_En15
                                               .sumIn(sumOut_4),  // sfix32_En30
                                               .sumOut(sumOut_5)  // sfix32_En30
                                               );

  always @(posedge clk)
    begin : sumOutReg_process
      if (rst_n == 1'b0) begin
        sumOutReg_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          sumOutReg_1 <= sumOut_5;
        end
      end
    end

  assign accSwitchOut = (accumulate == 1'b0 ? accDataOut_1 :
              accDataOut);

  assign accAdderOut = accSwitchOut + sumOutReg_1;

  always @(posedge clk)
    begin : accDataOut_2_process
      if (rst_n == 1'b0) begin
        accDataOut_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          accDataOut_1 <= accAdderOut;
        end
      end
    end

  assign converterOut = accDataOut_1[30:15];

  always @(posedge clk)
    begin : dout_re_process
      if (rst_n == 1'b0) begin
        dout_re_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && validOutLookahead_1) begin
          dout_re_1 <= converterOut;
        end
      end
    end

  assign dataZero = 16'sb0000000000000000;

  assign dataOut = (notValid == 1'b0 ? dout_re_1 :
              dataZero);

  assign validOut = vldOut_1;

endmodule  // Halfband_Filter_2

