// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC\HB1.v
// Created: 2025-03-25 14:21:11
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HB1
// Source Path: DUC/DUC_module/HB1
// Hierarchy Level: 1
// Model version: 3.79
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HB1
          (clk,
           rst_n,
           enb,
           DATA_IN,
           RST,
           HB1_DATA,
           VLD_OUT);


  input   clk;
  input   rst_n;
  input   enb;
  input   signed [15:0] DATA_IN;  // sfix16_En15
  input   RST;
  output  signed [15:0] HB1_DATA;  // sfix16_En15
  output  VLD_OUT;


  wire [15:0] count_step;  // uint16
  wire [15:0] count_from;  // uint16
  wire [15:0] count_reset;  // uint16
  reg [15:0] HDL_Counter_out1;  // uint16
  wire [15:0] count;  // uint16
  wire need_to_wrap;
  wire [15:0] count_value;  // uint16
  wire [15:0] count_1;  // uint16
  wire [15:0] alpha1250_out1;  // uint16
  wire HB1_VLD_out1;
  wire signed [15:0] HB1_DATA_1;  // sfix16_En15
  wire Halfband_Filter_1_out2;


  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 1249
  assign count_step = 16'b0000000000000001;
  assign count_from = 16'b0000000000000000;
  assign count_reset = 16'b0000000000000000;
  assign count = HDL_Counter_out1 + count_step;
  assign need_to_wrap = HDL_Counter_out1 == 16'b0000010011100001;
  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);
  assign count_1 = (RST == 1'b0 ? count_value :
              count_reset);
  always @(posedge clk)
    begin : HDL_Counter_process
      if (rst_n == 1'b0) begin
        HDL_Counter_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          HDL_Counter_out1 <= count_1;
        end
      end
    end
  assign alpha1250_out1 = 16'b0000010011100001;
  assign HB1_VLD_out1 = HDL_Counter_out1 == alpha1250_out1;
  Halfband_Filter_1 u_Halfband_Filter_1 (.clk(clk),
                                         .rst_n(rst_n),
                                         .enb(enb),
                                         .dataIn(DATA_IN),  // sfix16_En15
                                         .validIn(HB1_VLD_out1),
                                         .dataOut(HB1_DATA_1),  // sfix16_En15
                                         .validOut(Halfband_Filter_1_out2)
                                         );
  assign HB1_DATA = HB1_DATA_1;

  assign VLD_OUT = Halfband_Filter_1_out2;

endmodule  // HB1

