// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC\HB_filter.v
// Created: 2025-03-10 19:56:01
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HB_filter
// Source Path: DUC/DUC_module/HB_filter
// Hierarchy Level: 1
// Model version: 3.54
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HB_filter
          (clk,
           rst_n,
           enb,
           DATA_IN,
           RST,
           DATA_OUT,
           VLD);


  input   clk;
  input   rst_n;
  input   enb;
  input   signed [15:0] DATA_IN;  // sfix16_En15
  input   RST;
  output  signed [15:0] DATA_OUT;  // sfix16_En15
  output  VLD;


  wire [15:0] count_step;  // uint16
  wire [15:0] count_from;  // uint16
  wire [15:0] count_reset;  // uint16
  reg [15:0] HDL_Counter_out1;  // uint16
  wire [15:0] count;  // uint16
  wire need_to_wrap;
  wire [15:0] count_value;  // uint16
  wire [15:0] count_1;  // uint16
  wire [15:0] alpha1250_out1;  // uint16
  wire HB1_VLD_out1;
  wire signed [15:0] HB1_DATA;  // sfix16_En15
  wire Halfband_Filter_1_out2;
  wire [15:0] count_step_1;  // uint16
  wire [15:0] count_from_1;  // uint16
  wire [15:0] count_reset_1;  // uint16
  reg [15:0] HDL_Counter1_out1;  // uint16
  wire [15:0] count_2;  // uint16
  wire need_to_wrap_1;
  wire [15:0] count_value_1;  // uint16
  wire [15:0] count_3;  // uint16
  wire [15:0] alpha625_out1;  // uint16
  wire HB2_VLD_out1;
  wire signed [15:0] HB2_DATA;  // sfix16_En15
  wire Halfband_Filter_2_out2;


  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 1249
  assign count_step = 16'b0000000000000001;
  assign count_from = 16'b0000000000000000;
  assign count_reset = 16'b0000000000000000;
  assign count = HDL_Counter_out1 + count_step;
  assign need_to_wrap = HDL_Counter_out1 == 16'b0000010011100001;
  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);
  assign count_1 = (RST == 1'b0 ? count_value :
              count_reset);
  always @(posedge clk)
    begin : HDL_Counter_process
      if (rst_n == 1'b0) begin
        HDL_Counter_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          HDL_Counter_out1 <= count_1;
        end
      end
    end
  assign alpha1250_out1 = 16'b0000010011100001;
  assign HB1_VLD_out1 = HDL_Counter_out1 == alpha1250_out1;
  Halfband_Filter_1 u_Halfband_Filter_1 (.clk(clk),
                                         .rst_n(rst_n),
                                         .enb(enb),
                                         .dataIn(DATA_IN),  // sfix16_En15
                                         .validIn(HB1_VLD_out1),
                                         .dataOut(HB1_DATA),  // sfix16_En15
                                         .validOut(Halfband_Filter_1_out2)
                                         );
  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 624
  assign count_step_1 = 16'b0000000000000001;
  assign count_from_1 = 16'b0000000000000000;
  assign count_reset_1 = 16'b0000000000000000;
  assign count_2 = HDL_Counter1_out1 + count_step_1;
  assign need_to_wrap_1 = HDL_Counter1_out1 == 16'b0000001001110000;
  assign count_value_1 = (need_to_wrap_1 == 1'b0 ? count_2 :
              count_from_1);
  assign count_3 = (Halfband_Filter_1_out2 == 1'b0 ? count_value_1 :
              count_reset_1);
  always @(posedge clk)
    begin : HDL_Counter1_process
      if (rst_n == 1'b0) begin
        HDL_Counter1_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          HDL_Counter1_out1 <= count_3;
        end
      end
    end
  assign alpha625_out1 = 16'b0000001001110000;
  assign HB2_VLD_out1 = HDL_Counter1_out1 == alpha625_out1;
  Halfband_Filter_2 u_Halfband_Filter_2 (.clk(clk),
                                         .rst_n(rst_n),
                                         .enb(enb),
                                         .dataIn(HB1_DATA),  // sfix16_En15
                                         .validIn(HB2_VLD_out1),
                                         .dataOut(HB2_DATA),  // sfix16_En15
                                         .validOut(Halfband_Filter_2_out2)
                                         );
  assign DATA_OUT = HB2_DATA;

  assign VLD = Halfband_Filter_2_out2;

endmodule  // HB_filter

