cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('DUC/Subsystem/Add1','user1');
hilite_system('DUC/Subsystem/Constant1','user1');
hilite_system('DUC/Subsystem/Constant4','user1');
hilite_system('DUC/Subsystem/Constant7','user1');
hilite_system('DUC/Subsystem/Constant8','user1');
hilite_system('DUC/DUC_module','user1');
hilite_system('DUC/DUC_module/Add','user1');
hilite_system('DUC/DUC_module/CIC_1','user1');
hilite_system('DUC/DUC_module/CIC_2','user1');
hilite_system('DUC/DUC_module/CIC_Comp Filter 1','user1');
hilite_system('DUC/DUC_module/CIC_Comp Filter 2','user1');
hilite_system('DUC/DUC_module/Constant','user1');
hilite_system('DUC/DUC_module/Constant2','user1');
hilite_system('DUC/DUC_module/Constant3','user1');
hilite_system('DUC/DUC_module/Constant5','user1');
hilite_system('DUC/DUC_module/Constant6','user1');
hilite_system('DUC/DUC_module/Counter Limited','user1');
hilite_system('DUC/DUC_module/Delay','user1');
hilite_system('DUC/DUC_module/Downsample','user1');
hilite_system('DUC/DUC_module/Gain','user1');
hilite_system('DUC/DUC_module/Gain1','user1');
hilite_system('DUC/DUC_module/HDL Counter','user1');
hilite_system('DUC/DUC_module/HDL Counter1','user1');
hilite_system('DUC/DUC_module/Halfband Filter 1','user1');
hilite_system('DUC/DUC_module/Halfband Filter 2','user1');
hilite_system('DUC/DUC_module/NCO','user1');
hilite_system('DUC/DUC_module/NCO1','user1');
hilite_system('DUC/DUC_module/Relational Operator','user1');
hilite_system('DUC/DUC_module/Relational Operator1','user1');
hilite_system('DUC/DUC_module/Relational Operator2','user1');
hilite_system('DUC/Subsystem/Delay2','user1');
hilite_system('DUC/Subsystem/Delay3','user1');
hilite_system('DUC/Subsystem/Product','user1');
hilite_system('DUC/Subsystem/Product1','user1');
hilite_system('DUC/Subsystem/carrier','user1');
hilite_system('DUC/Subsystem/Data Type Conversion1','user1');
hilite_system('DUC/Subsystem/Delay1','user1');
hilite_system('DUC/Subsystem/Data Type Conversion2','user1');
hilite_system('DUC/DUC_module/Data Type Conversion','user1');
hilite_system('DUC/DUC_module/Gain2','user1');
hilite_system('DUC/DUC_module/Gain3','user1');
hilite_system('DUC/DUC_module/Delay1','user1');
hilite_system('DUC/Subsystem','user1');
