open_system('DUC');
open_system('gm_DUC');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC/DUC_module/CIC_1/us', 'user2');
annotate_port('gm_DUC/DUC_module/CIC_1/us', 1, 1, '时钟频率流水线的障碍');
hilite_system('DUC/DUC_module/CIC_1', 'user2');
annotate_port('DUC/DUC_module/CIC_1', 1, 1, '时钟频率流水线的障碍');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUC/DUC_module/CIC_2/us', 'user2');
annotate_port('gm_DUC/DUC_module/CIC_2/us', 1, 1, '时钟频率流水线的障碍');
hilite_system('DUC/DUC_module/CIC_2', 'user2');
annotate_port('DUC/DUC_module/CIC_2', 1, 1, '时钟频率流水线的障碍');
