// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC\Lookup_Table1.v
// Created: 2025-03-11 17:04:39
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Lookup_Table1
// Source Path: DUC/Wave_Source/NCO/WaveformGen/LookUpTableGen/Lookup Table1
// Hierarchy Level: 4
// Model version: 3.64
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Lookup_Table1
          (in1,
           out);


  input   [7:0] in1;  // ufix8
  output  signed [15:0] out;  // sfix16_En15


  wire [7:0] prelookup_idx_sat;  // uint8
  wire signed [15:0] Lookup_Table1_table_data [0:255];  // sfix16_En15 [256]


  assign prelookup_idx_sat = (in1 == 8'b00000000 ? 8'b00000000 :
              (in1 == 8'b11111111 ? 8'b11111111 :
              in1));

  assign Lookup_Table1_table_data[0] = 16'sb0000000000000000;
  assign Lookup_Table1_table_data[1] = 16'sb0000000011001001;
  assign Lookup_Table1_table_data[2] = 16'sb0000000110010010;
  assign Lookup_Table1_table_data[3] = 16'sb0000001001011011;
  assign Lookup_Table1_table_data[4] = 16'sb0000001100100100;
  assign Lookup_Table1_table_data[5] = 16'sb0000001111101101;
  assign Lookup_Table1_table_data[6] = 16'sb0000010010110110;
  assign Lookup_Table1_table_data[7] = 16'sb0000010101111111;
  assign Lookup_Table1_table_data[8] = 16'sb0000011001001000;
  assign Lookup_Table1_table_data[9] = 16'sb0000011100010001;
  assign Lookup_Table1_table_data[10] = 16'sb0000011111011001;
  assign Lookup_Table1_table_data[11] = 16'sb0000100010100010;
  assign Lookup_Table1_table_data[12] = 16'sb0000100101101011;
  assign Lookup_Table1_table_data[13] = 16'sb0000101000110011;
  assign Lookup_Table1_table_data[14] = 16'sb0000101011111011;
  assign Lookup_Table1_table_data[15] = 16'sb0000101111000100;
  assign Lookup_Table1_table_data[16] = 16'sb0000110010001100;
  assign Lookup_Table1_table_data[17] = 16'sb0000110101010100;
  assign Lookup_Table1_table_data[18] = 16'sb0000111000011100;
  assign Lookup_Table1_table_data[19] = 16'sb0000111011100100;
  assign Lookup_Table1_table_data[20] = 16'sb0000111110101011;
  assign Lookup_Table1_table_data[21] = 16'sb0001000001110011;
  assign Lookup_Table1_table_data[22] = 16'sb0001000100111010;
  assign Lookup_Table1_table_data[23] = 16'sb0001001000000001;
  assign Lookup_Table1_table_data[24] = 16'sb0001001011001000;
  assign Lookup_Table1_table_data[25] = 16'sb0001001110001111;
  assign Lookup_Table1_table_data[26] = 16'sb0001010001010101;
  assign Lookup_Table1_table_data[27] = 16'sb0001010100011100;
  assign Lookup_Table1_table_data[28] = 16'sb0001010111100010;
  assign Lookup_Table1_table_data[29] = 16'sb0001011010101000;
  assign Lookup_Table1_table_data[30] = 16'sb0001011101101110;
  assign Lookup_Table1_table_data[31] = 16'sb0001100000110011;
  assign Lookup_Table1_table_data[32] = 16'sb0001100011111001;
  assign Lookup_Table1_table_data[33] = 16'sb0001100110111110;
  assign Lookup_Table1_table_data[34] = 16'sb0001101010000011;
  assign Lookup_Table1_table_data[35] = 16'sb0001101101000111;
  assign Lookup_Table1_table_data[36] = 16'sb0001110000001100;
  assign Lookup_Table1_table_data[37] = 16'sb0001110011010000;
  assign Lookup_Table1_table_data[38] = 16'sb0001110110010011;
  assign Lookup_Table1_table_data[39] = 16'sb0001111001010111;
  assign Lookup_Table1_table_data[40] = 16'sb0001111100011010;
  assign Lookup_Table1_table_data[41] = 16'sb0001111111011101;
  assign Lookup_Table1_table_data[42] = 16'sb0010000010011111;
  assign Lookup_Table1_table_data[43] = 16'sb0010000101100010;
  assign Lookup_Table1_table_data[44] = 16'sb0010001000100100;
  assign Lookup_Table1_table_data[45] = 16'sb0010001011100101;
  assign Lookup_Table1_table_data[46] = 16'sb0010001110100111;
  assign Lookup_Table1_table_data[47] = 16'sb0010010001100111;
  assign Lookup_Table1_table_data[48] = 16'sb0010010100101000;
  assign Lookup_Table1_table_data[49] = 16'sb0010010111101000;
  assign Lookup_Table1_table_data[50] = 16'sb0010011010101000;
  assign Lookup_Table1_table_data[51] = 16'sb0010011101101000;
  assign Lookup_Table1_table_data[52] = 16'sb0010100000100111;
  assign Lookup_Table1_table_data[53] = 16'sb0010100011100101;
  assign Lookup_Table1_table_data[54] = 16'sb0010100110100100;
  assign Lookup_Table1_table_data[55] = 16'sb0010101001100010;
  assign Lookup_Table1_table_data[56] = 16'sb0010101100011111;
  assign Lookup_Table1_table_data[57] = 16'sb0010101111011100;
  assign Lookup_Table1_table_data[58] = 16'sb0010110010011001;
  assign Lookup_Table1_table_data[59] = 16'sb0010110101010101;
  assign Lookup_Table1_table_data[60] = 16'sb0010111000010001;
  assign Lookup_Table1_table_data[61] = 16'sb0010111011001100;
  assign Lookup_Table1_table_data[62] = 16'sb0010111110000111;
  assign Lookup_Table1_table_data[63] = 16'sb0011000001000010;
  assign Lookup_Table1_table_data[64] = 16'sb0011000011111100;
  assign Lookup_Table1_table_data[65] = 16'sb0011000110110101;
  assign Lookup_Table1_table_data[66] = 16'sb0011001001101110;
  assign Lookup_Table1_table_data[67] = 16'sb0011001100100111;
  assign Lookup_Table1_table_data[68] = 16'sb0011001111011111;
  assign Lookup_Table1_table_data[69] = 16'sb0011010010010111;
  assign Lookup_Table1_table_data[70] = 16'sb0011010101001110;
  assign Lookup_Table1_table_data[71] = 16'sb0011011000000100;
  assign Lookup_Table1_table_data[72] = 16'sb0011011010111010;
  assign Lookup_Table1_table_data[73] = 16'sb0011011101110000;
  assign Lookup_Table1_table_data[74] = 16'sb0011100000100101;
  assign Lookup_Table1_table_data[75] = 16'sb0011100011011001;
  assign Lookup_Table1_table_data[76] = 16'sb0011100110001101;
  assign Lookup_Table1_table_data[77] = 16'sb0011101001000000;
  assign Lookup_Table1_table_data[78] = 16'sb0011101011110011;
  assign Lookup_Table1_table_data[79] = 16'sb0011101110100101;
  assign Lookup_Table1_table_data[80] = 16'sb0011110001010111;
  assign Lookup_Table1_table_data[81] = 16'sb0011110100001000;
  assign Lookup_Table1_table_data[82] = 16'sb0011110110111000;
  assign Lookup_Table1_table_data[83] = 16'sb0011111001101000;
  assign Lookup_Table1_table_data[84] = 16'sb0011111100010111;
  assign Lookup_Table1_table_data[85] = 16'sb0011111111000110;
  assign Lookup_Table1_table_data[86] = 16'sb0100000001110100;
  assign Lookup_Table1_table_data[87] = 16'sb0100000100100001;
  assign Lookup_Table1_table_data[88] = 16'sb0100000111001110;
  assign Lookup_Table1_table_data[89] = 16'sb0100001001111010;
  assign Lookup_Table1_table_data[90] = 16'sb0100001100100110;
  assign Lookup_Table1_table_data[91] = 16'sb0100001111010001;
  assign Lookup_Table1_table_data[92] = 16'sb0100010001111011;
  assign Lookup_Table1_table_data[93] = 16'sb0100010100100100;
  assign Lookup_Table1_table_data[94] = 16'sb0100010111001101;
  assign Lookup_Table1_table_data[95] = 16'sb0100011001110101;
  assign Lookup_Table1_table_data[96] = 16'sb0100011100011101;
  assign Lookup_Table1_table_data[97] = 16'sb0100011111000100;
  assign Lookup_Table1_table_data[98] = 16'sb0100100001101010;
  assign Lookup_Table1_table_data[99] = 16'sb0100100100001111;
  assign Lookup_Table1_table_data[100] = 16'sb0100100110110100;
  assign Lookup_Table1_table_data[101] = 16'sb0100101001011000;
  assign Lookup_Table1_table_data[102] = 16'sb0100101011111011;
  assign Lookup_Table1_table_data[103] = 16'sb0100101110011110;
  assign Lookup_Table1_table_data[104] = 16'sb0100110001000000;
  assign Lookup_Table1_table_data[105] = 16'sb0100110011100001;
  assign Lookup_Table1_table_data[106] = 16'sb0100110110000001;
  assign Lookup_Table1_table_data[107] = 16'sb0100111000100001;
  assign Lookup_Table1_table_data[108] = 16'sb0100111011000000;
  assign Lookup_Table1_table_data[109] = 16'sb0100111101011110;
  assign Lookup_Table1_table_data[110] = 16'sb0100111111111011;
  assign Lookup_Table1_table_data[111] = 16'sb0101000010011000;
  assign Lookup_Table1_table_data[112] = 16'sb0101000100110100;
  assign Lookup_Table1_table_data[113] = 16'sb0101000111001111;
  assign Lookup_Table1_table_data[114] = 16'sb0101001001101001;
  assign Lookup_Table1_table_data[115] = 16'sb0101001100000011;
  assign Lookup_Table1_table_data[116] = 16'sb0101001110011011;
  assign Lookup_Table1_table_data[117] = 16'sb0101010000110011;
  assign Lookup_Table1_table_data[118] = 16'sb0101010011001010;
  assign Lookup_Table1_table_data[119] = 16'sb0101010101100000;
  assign Lookup_Table1_table_data[120] = 16'sb0101010111110110;
  assign Lookup_Table1_table_data[121] = 16'sb0101011010001010;
  assign Lookup_Table1_table_data[122] = 16'sb0101011100011110;
  assign Lookup_Table1_table_data[123] = 16'sb0101011110110001;
  assign Lookup_Table1_table_data[124] = 16'sb0101100001000011;
  assign Lookup_Table1_table_data[125] = 16'sb0101100011010100;
  assign Lookup_Table1_table_data[126] = 16'sb0101100101100100;
  assign Lookup_Table1_table_data[127] = 16'sb0101100111110100;
  assign Lookup_Table1_table_data[128] = 16'sb0101101010000010;
  assign Lookup_Table1_table_data[129] = 16'sb0101101100010000;
  assign Lookup_Table1_table_data[130] = 16'sb0101101110011101;
  assign Lookup_Table1_table_data[131] = 16'sb0101110000101001;
  assign Lookup_Table1_table_data[132] = 16'sb0101110010110100;
  assign Lookup_Table1_table_data[133] = 16'sb0101110100111110;
  assign Lookup_Table1_table_data[134] = 16'sb0101110111001000;
  assign Lookup_Table1_table_data[135] = 16'sb0101111001010000;
  assign Lookup_Table1_table_data[136] = 16'sb0101111011010111;
  assign Lookup_Table1_table_data[137] = 16'sb0101111101011110;
  assign Lookup_Table1_table_data[138] = 16'sb0101111111100100;
  assign Lookup_Table1_table_data[139] = 16'sb0110000001101000;
  assign Lookup_Table1_table_data[140] = 16'sb0110000011101100;
  assign Lookup_Table1_table_data[141] = 16'sb0110000101101111;
  assign Lookup_Table1_table_data[142] = 16'sb0110000111110001;
  assign Lookup_Table1_table_data[143] = 16'sb0110001001110010;
  assign Lookup_Table1_table_data[144] = 16'sb0110001011110010;
  assign Lookup_Table1_table_data[145] = 16'sb0110001101110001;
  assign Lookup_Table1_table_data[146] = 16'sb0110001111101111;
  assign Lookup_Table1_table_data[147] = 16'sb0110010001101100;
  assign Lookup_Table1_table_data[148] = 16'sb0110010011101001;
  assign Lookup_Table1_table_data[149] = 16'sb0110010101100100;
  assign Lookup_Table1_table_data[150] = 16'sb0110010111011110;
  assign Lookup_Table1_table_data[151] = 16'sb0110011001010111;
  assign Lookup_Table1_table_data[152] = 16'sb0110011011010000;
  assign Lookup_Table1_table_data[153] = 16'sb0110011101000111;
  assign Lookup_Table1_table_data[154] = 16'sb0110011110111101;
  assign Lookup_Table1_table_data[155] = 16'sb0110100000110010;
  assign Lookup_Table1_table_data[156] = 16'sb0110100010100111;
  assign Lookup_Table1_table_data[157] = 16'sb0110100100011010;
  assign Lookup_Table1_table_data[158] = 16'sb0110100110001100;
  assign Lookup_Table1_table_data[159] = 16'sb0110100111111101;
  assign Lookup_Table1_table_data[160] = 16'sb0110101001101110;
  assign Lookup_Table1_table_data[161] = 16'sb0110101011011101;
  assign Lookup_Table1_table_data[162] = 16'sb0110101101001011;
  assign Lookup_Table1_table_data[163] = 16'sb0110101110111000;
  assign Lookup_Table1_table_data[164] = 16'sb0110110000100100;
  assign Lookup_Table1_table_data[165] = 16'sb0110110010001111;
  assign Lookup_Table1_table_data[166] = 16'sb0110110011111001;
  assign Lookup_Table1_table_data[167] = 16'sb0110110101100010;
  assign Lookup_Table1_table_data[168] = 16'sb0110110111001010;
  assign Lookup_Table1_table_data[169] = 16'sb0110111000110001;
  assign Lookup_Table1_table_data[170] = 16'sb0110111010010111;
  assign Lookup_Table1_table_data[171] = 16'sb0110111011111011;
  assign Lookup_Table1_table_data[172] = 16'sb0110111101011111;
  assign Lookup_Table1_table_data[173] = 16'sb0110111111000010;
  assign Lookup_Table1_table_data[174] = 16'sb0111000000100011;
  assign Lookup_Table1_table_data[175] = 16'sb0111000010000011;
  assign Lookup_Table1_table_data[176] = 16'sb0111000011100011;
  assign Lookup_Table1_table_data[177] = 16'sb0111000101000001;
  assign Lookup_Table1_table_data[178] = 16'sb0111000110011110;
  assign Lookup_Table1_table_data[179] = 16'sb0111000111111010;
  assign Lookup_Table1_table_data[180] = 16'sb0111001001010101;
  assign Lookup_Table1_table_data[181] = 16'sb0111001010101111;
  assign Lookup_Table1_table_data[182] = 16'sb0111001100001000;
  assign Lookup_Table1_table_data[183] = 16'sb0111001101011111;
  assign Lookup_Table1_table_data[184] = 16'sb0111001110110110;
  assign Lookup_Table1_table_data[185] = 16'sb0111010000001011;
  assign Lookup_Table1_table_data[186] = 16'sb0111010001100000;
  assign Lookup_Table1_table_data[187] = 16'sb0111010010110011;
  assign Lookup_Table1_table_data[188] = 16'sb0111010100000101;
  assign Lookup_Table1_table_data[189] = 16'sb0111010101010110;
  assign Lookup_Table1_table_data[190] = 16'sb0111010110100110;
  assign Lookup_Table1_table_data[191] = 16'sb0111010111110100;
  assign Lookup_Table1_table_data[192] = 16'sb0111011001000010;
  assign Lookup_Table1_table_data[193] = 16'sb0111011010001110;
  assign Lookup_Table1_table_data[194] = 16'sb0111011011011001;
  assign Lookup_Table1_table_data[195] = 16'sb0111011100100011;
  assign Lookup_Table1_table_data[196] = 16'sb0111011101101100;
  assign Lookup_Table1_table_data[197] = 16'sb0111011110110100;
  assign Lookup_Table1_table_data[198] = 16'sb0111011111111011;
  assign Lookup_Table1_table_data[199] = 16'sb0111100001000000;
  assign Lookup_Table1_table_data[200] = 16'sb0111100010000101;
  assign Lookup_Table1_table_data[201] = 16'sb0111100011001000;
  assign Lookup_Table1_table_data[202] = 16'sb0111100100001010;
  assign Lookup_Table1_table_data[203] = 16'sb0111100101001010;
  assign Lookup_Table1_table_data[204] = 16'sb0111100110001010;
  assign Lookup_Table1_table_data[205] = 16'sb0111100111001001;
  assign Lookup_Table1_table_data[206] = 16'sb0111101000000110;
  assign Lookup_Table1_table_data[207] = 16'sb0111101001000010;
  assign Lookup_Table1_table_data[208] = 16'sb0111101001111101;
  assign Lookup_Table1_table_data[209] = 16'sb0111101010110111;
  assign Lookup_Table1_table_data[210] = 16'sb0111101011101111;
  assign Lookup_Table1_table_data[211] = 16'sb0111101100100111;
  assign Lookup_Table1_table_data[212] = 16'sb0111101101011101;
  assign Lookup_Table1_table_data[213] = 16'sb0111101110010010;
  assign Lookup_Table1_table_data[214] = 16'sb0111101111000110;
  assign Lookup_Table1_table_data[215] = 16'sb0111101111111001;
  assign Lookup_Table1_table_data[216] = 16'sb0111110000101010;
  assign Lookup_Table1_table_data[217] = 16'sb0111110001011010;
  assign Lookup_Table1_table_data[218] = 16'sb0111110010001001;
  assign Lookup_Table1_table_data[219] = 16'sb0111110010110111;
  assign Lookup_Table1_table_data[220] = 16'sb0111110011100100;
  assign Lookup_Table1_table_data[221] = 16'sb0111110100001111;
  assign Lookup_Table1_table_data[222] = 16'sb0111110100111010;
  assign Lookup_Table1_table_data[223] = 16'sb0111110101100011;
  assign Lookup_Table1_table_data[224] = 16'sb0111110110001010;
  assign Lookup_Table1_table_data[225] = 16'sb0111110110110001;
  assign Lookup_Table1_table_data[226] = 16'sb0111110111010110;
  assign Lookup_Table1_table_data[227] = 16'sb0111110111111011;
  assign Lookup_Table1_table_data[228] = 16'sb0111111000011110;
  assign Lookup_Table1_table_data[229] = 16'sb0111111000111111;
  assign Lookup_Table1_table_data[230] = 16'sb0111111001100000;
  assign Lookup_Table1_table_data[231] = 16'sb0111111001111111;
  assign Lookup_Table1_table_data[232] = 16'sb0111111010011101;
  assign Lookup_Table1_table_data[233] = 16'sb0111111010111010;
  assign Lookup_Table1_table_data[234] = 16'sb0111111011010110;
  assign Lookup_Table1_table_data[235] = 16'sb0111111011110000;
  assign Lookup_Table1_table_data[236] = 16'sb0111111100001010;
  assign Lookup_Table1_table_data[237] = 16'sb0111111100100010;
  assign Lookup_Table1_table_data[238] = 16'sb0111111100111000;
  assign Lookup_Table1_table_data[239] = 16'sb0111111101001110;
  assign Lookup_Table1_table_data[240] = 16'sb0111111101100010;
  assign Lookup_Table1_table_data[241] = 16'sb0111111101110101;
  assign Lookup_Table1_table_data[242] = 16'sb0111111110000111;
  assign Lookup_Table1_table_data[243] = 16'sb0111111110011000;
  assign Lookup_Table1_table_data[244] = 16'sb0111111110100111;
  assign Lookup_Table1_table_data[245] = 16'sb0111111110110101;
  assign Lookup_Table1_table_data[246] = 16'sb0111111111000010;
  assign Lookup_Table1_table_data[247] = 16'sb0111111111001110;
  assign Lookup_Table1_table_data[248] = 16'sb0111111111011001;
  assign Lookup_Table1_table_data[249] = 16'sb0111111111100010;
  assign Lookup_Table1_table_data[250] = 16'sb0111111111101010;
  assign Lookup_Table1_table_data[251] = 16'sb0111111111110001;
  assign Lookup_Table1_table_data[252] = 16'sb0111111111110110;
  assign Lookup_Table1_table_data[253] = 16'sb0111111111111010;
  assign Lookup_Table1_table_data[254] = 16'sb0111111111111110;
  assign Lookup_Table1_table_data[255] = 16'sb0111111111111111;
  assign out = Lookup_Table1_table_data[prelookup_idx_sat];

endmodule  // Lookup_Table1

