// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC\Lookup_Table2.v
// Created: 2025-03-11 17:04:39
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Lookup_Table2
// Source Path: DUC/Wave_Source/NCO/WaveformGen/LookUpTableGen/Lookup Table2
// Hierarchy Level: 4
// Model version: 3.64
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Lookup_Table2
          (in1,
           out);


  input   [6:0] in1;  // ufix7
  output  [3:0] out;  // ufix4_En4


  wire [6:0] prelookup_idx_sat;  // ufix7
  wire [3:0] Lookup_Table2_table_data [0:127];  // ufix4_En4 [128]


  assign prelookup_idx_sat = (in1 == 7'b0000000 ? 7'b0000000 :
              (in1 == 7'b1111111 ? 7'b1111111 :
              in1));

  assign Lookup_Table2_table_data[0] = 4'b0000;
  assign Lookup_Table2_table_data[1] = 4'b0010;
  assign Lookup_Table2_table_data[2] = 4'b0011;
  assign Lookup_Table2_table_data[3] = 4'b0101;
  assign Lookup_Table2_table_data[4] = 4'b0110;
  assign Lookup_Table2_table_data[5] = 4'b1000;
  assign Lookup_Table2_table_data[6] = 4'b1001;
  assign Lookup_Table2_table_data[7] = 4'b1011;
  assign Lookup_Table2_table_data[8] = 4'b0000;
  assign Lookup_Table2_table_data[9] = 4'b0010;
  assign Lookup_Table2_table_data[10] = 4'b0011;
  assign Lookup_Table2_table_data[11] = 4'b0101;
  assign Lookup_Table2_table_data[12] = 4'b0110;
  assign Lookup_Table2_table_data[13] = 4'b1000;
  assign Lookup_Table2_table_data[14] = 4'b1001;
  assign Lookup_Table2_table_data[15] = 4'b1011;
  assign Lookup_Table2_table_data[16] = 4'b0000;
  assign Lookup_Table2_table_data[17] = 4'b0010;
  assign Lookup_Table2_table_data[18] = 4'b0011;
  assign Lookup_Table2_table_data[19] = 4'b0101;
  assign Lookup_Table2_table_data[20] = 4'b0110;
  assign Lookup_Table2_table_data[21] = 4'b1000;
  assign Lookup_Table2_table_data[22] = 4'b1001;
  assign Lookup_Table2_table_data[23] = 4'b1011;
  assign Lookup_Table2_table_data[24] = 4'b0000;
  assign Lookup_Table2_table_data[25] = 4'b0010;
  assign Lookup_Table2_table_data[26] = 4'b0011;
  assign Lookup_Table2_table_data[27] = 4'b0101;
  assign Lookup_Table2_table_data[28] = 4'b0110;
  assign Lookup_Table2_table_data[29] = 4'b1000;
  assign Lookup_Table2_table_data[30] = 4'b1001;
  assign Lookup_Table2_table_data[31] = 4'b1011;
  assign Lookup_Table2_table_data[32] = 4'b0000;
  assign Lookup_Table2_table_data[33] = 4'b0001;
  assign Lookup_Table2_table_data[34] = 4'b0011;
  assign Lookup_Table2_table_data[35] = 4'b0100;
  assign Lookup_Table2_table_data[36] = 4'b0110;
  assign Lookup_Table2_table_data[37] = 4'b0111;
  assign Lookup_Table2_table_data[38] = 4'b1001;
  assign Lookup_Table2_table_data[39] = 4'b1010;
  assign Lookup_Table2_table_data[40] = 4'b0000;
  assign Lookup_Table2_table_data[41] = 4'b0001;
  assign Lookup_Table2_table_data[42] = 4'b0011;
  assign Lookup_Table2_table_data[43] = 4'b0100;
  assign Lookup_Table2_table_data[44] = 4'b0110;
  assign Lookup_Table2_table_data[45] = 4'b0111;
  assign Lookup_Table2_table_data[46] = 4'b1000;
  assign Lookup_Table2_table_data[47] = 4'b1010;
  assign Lookup_Table2_table_data[48] = 4'b0000;
  assign Lookup_Table2_table_data[49] = 4'b0001;
  assign Lookup_Table2_table_data[50] = 4'b0011;
  assign Lookup_Table2_table_data[51] = 4'b0100;
  assign Lookup_Table2_table_data[52] = 4'b0101;
  assign Lookup_Table2_table_data[53] = 4'b0111;
  assign Lookup_Table2_table_data[54] = 4'b1000;
  assign Lookup_Table2_table_data[55] = 4'b1001;
  assign Lookup_Table2_table_data[56] = 4'b0000;
  assign Lookup_Table2_table_data[57] = 4'b0001;
  assign Lookup_Table2_table_data[58] = 4'b0010;
  assign Lookup_Table2_table_data[59] = 4'b0100;
  assign Lookup_Table2_table_data[60] = 4'b0101;
  assign Lookup_Table2_table_data[61] = 4'b0110;
  assign Lookup_Table2_table_data[62] = 4'b0111;
  assign Lookup_Table2_table_data[63] = 4'b1000;
  assign Lookup_Table2_table_data[64] = 4'b0000;
  assign Lookup_Table2_table_data[65] = 4'b0001;
  assign Lookup_Table2_table_data[66] = 4'b0010;
  assign Lookup_Table2_table_data[67] = 4'b0011;
  assign Lookup_Table2_table_data[68] = 4'b0100;
  assign Lookup_Table2_table_data[69] = 4'b0110;
  assign Lookup_Table2_table_data[70] = 4'b0111;
  assign Lookup_Table2_table_data[71] = 4'b1000;
  assign Lookup_Table2_table_data[72] = 4'b0000;
  assign Lookup_Table2_table_data[73] = 4'b0001;
  assign Lookup_Table2_table_data[74] = 4'b0010;
  assign Lookup_Table2_table_data[75] = 4'b0011;
  assign Lookup_Table2_table_data[76] = 4'b0100;
  assign Lookup_Table2_table_data[77] = 4'b0101;
  assign Lookup_Table2_table_data[78] = 4'b0110;
  assign Lookup_Table2_table_data[79] = 4'b0111;
  assign Lookup_Table2_table_data[80] = 4'b0000;
  assign Lookup_Table2_table_data[81] = 4'b0001;
  assign Lookup_Table2_table_data[82] = 4'b0010;
  assign Lookup_Table2_table_data[83] = 4'b0011;
  assign Lookup_Table2_table_data[84] = 4'b0011;
  assign Lookup_Table2_table_data[85] = 4'b0100;
  assign Lookup_Table2_table_data[86] = 4'b0101;
  assign Lookup_Table2_table_data[87] = 4'b0110;
  assign Lookup_Table2_table_data[88] = 4'b0000;
  assign Lookup_Table2_table_data[89] = 4'b0001;
  assign Lookup_Table2_table_data[90] = 4'b0001;
  assign Lookup_Table2_table_data[91] = 4'b0010;
  assign Lookup_Table2_table_data[92] = 4'b0011;
  assign Lookup_Table2_table_data[93] = 4'b0100;
  assign Lookup_Table2_table_data[94] = 4'b0100;
  assign Lookup_Table2_table_data[95] = 4'b0101;
  assign Lookup_Table2_table_data[96] = 4'b0000;
  assign Lookup_Table2_table_data[97] = 4'b0001;
  assign Lookup_Table2_table_data[98] = 4'b0001;
  assign Lookup_Table2_table_data[99] = 4'b0010;
  assign Lookup_Table2_table_data[100] = 4'b0010;
  assign Lookup_Table2_table_data[101] = 4'b0011;
  assign Lookup_Table2_table_data[102] = 4'b0100;
  assign Lookup_Table2_table_data[103] = 4'b0100;
  assign Lookup_Table2_table_data[104] = 4'b0000;
  assign Lookup_Table2_table_data[105] = 4'b0000;
  assign Lookup_Table2_table_data[106] = 4'b0001;
  assign Lookup_Table2_table_data[107] = 4'b0001;
  assign Lookup_Table2_table_data[108] = 4'b0010;
  assign Lookup_Table2_table_data[109] = 4'b0010;
  assign Lookup_Table2_table_data[110] = 4'b0011;
  assign Lookup_Table2_table_data[111] = 4'b0011;
  assign Lookup_Table2_table_data[112] = 4'b0000;
  assign Lookup_Table2_table_data[113] = 4'b0000;
  assign Lookup_Table2_table_data[114] = 4'b0001;
  assign Lookup_Table2_table_data[115] = 4'b0001;
  assign Lookup_Table2_table_data[116] = 4'b0001;
  assign Lookup_Table2_table_data[117] = 4'b0010;
  assign Lookup_Table2_table_data[118] = 4'b0010;
  assign Lookup_Table2_table_data[119] = 4'b0010;
  assign Lookup_Table2_table_data[120] = 4'b0000;
  assign Lookup_Table2_table_data[121] = 4'b0000;
  assign Lookup_Table2_table_data[122] = 4'b0000;
  assign Lookup_Table2_table_data[123] = 4'b0000;
  assign Lookup_Table2_table_data[124] = 4'b0001;
  assign Lookup_Table2_table_data[125] = 4'b0001;
  assign Lookup_Table2_table_data[126] = 4'b0001;
  assign Lookup_Table2_table_data[127] = 4'b0001;
  assign out = Lookup_Table2_table_data[prelookup_idx_sat];

endmodule  // Lookup_Table2

