vlib work
vlog  DitherGen.v
vlog  Lookup_Table1.v
vlog  Lookup_Table2.v
vlog  LookUpTableGen.v
vlog  WaveformGen.v
vlog  NCO.v
vlog  SinglePortRAM_generic.v
vlog  SinglePortRAM_generic_AsyncRead.v
vlog  Painter.v
vlog  DitherGen_block.v
vlog  Lookup_Table.v
vlog  LookUpTableGen_block.v
vlog  WaveformGen_block.v
vlog  NCO1.v
vlog  DitherGen_block1.v
vlog  Lookup_Table_block.v
vlog  LookUpTableGen_block1.v
vlog  WaveformGen_block1.v
vlog  NCO2.v
vlog  single_tone_500_1k.v
vlog  Signal_Source_module.v
