// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC\subFilter.v
// Created: 2025-04-03 15:54:05
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: subFilter
// Source Path: DUC/AM_MultiBaseband_module/INV_SINC/Discrete FIR Filter/Filter/subFilter
// Hierarchy Level: 4
// Model version: 3.93
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module subFilter
          (clk,
           rst_n,
           enb,
           dinReg2_0_re,
           coefIn_0,
           coefIn_1,
           coefIn_2,
           coefIn_3,
           coefIn_4,
           coefIn_5,
           coefIn_6,
           coefIn_7,
           coefIn_8,
           coefIn_9,
           coefIn_10,
           coefIn_11,
           coefIn_12,
           coefIn_13,
           coefIn_14,
           coefIn_15,
           dinRegVld,
           syncReset,
           dout_1_re);


  input   clk;
  input   rst_n;
  input   enb;
  input   signed [15:0] dinReg2_0_re;  // sfix16_En11
  input   signed [15:0] coefIn_0;  // sfix16_En15
  input   signed [15:0] coefIn_1;  // sfix16_En15
  input   signed [15:0] coefIn_2;  // sfix16_En15
  input   signed [15:0] coefIn_3;  // sfix16_En15
  input   signed [15:0] coefIn_4;  // sfix16_En15
  input   signed [15:0] coefIn_5;  // sfix16_En15
  input   signed [15:0] coefIn_6;  // sfix16_En15
  input   signed [15:0] coefIn_7;  // sfix16_En15
  input   signed [15:0] coefIn_8;  // sfix16_En15
  input   signed [15:0] coefIn_9;  // sfix16_En15
  input   signed [15:0] coefIn_10;  // sfix16_En15
  input   signed [15:0] coefIn_11;  // sfix16_En15
  input   signed [15:0] coefIn_12;  // sfix16_En15
  input   signed [15:0] coefIn_13;  // sfix16_En15
  input   signed [15:0] coefIn_14;  // sfix16_En15
  input   signed [15:0] coefIn_15;  // sfix16_En15
  input   dinRegVld;
  input   syncReset;
  output  signed [15:0] dout_1_re;  // sfix16_En11


  reg  [2:0] intdelay_reg;  // ufix1 [3]
  wire tapoutVld;
  wire signed [47:0] addin;  // sfix48_En26
  reg  [1:0] intdelay_reg_1;  // ufix1 [2]
  wire multVld;
  wire signed [47:0] tapout;  // sfix48_En26
  wire signed [47:0] tapout_1;  // sfix48_En26
  wire signed [47:0] tapout_2;  // sfix48_En26
  wire signed [47:0] tapout_3;  // sfix48_En26
  wire signed [47:0] tapout_4;  // sfix48_En26
  wire signed [47:0] tapout_5;  // sfix48_En26
  wire signed [47:0] tapout_6;  // sfix48_En26
  wire signed [47:0] tapout_7;  // sfix48_En26
  wire signed [47:0] tapout_8;  // sfix48_En26
  wire signed [47:0] tapout_9;  // sfix48_En26
  wire signed [47:0] tapout_10;  // sfix48_En26
  wire signed [47:0] tapout_11;  // sfix48_En26
  wire signed [47:0] tapout_12;  // sfix48_En26
  wire signed [47:0] tapout_13;  // sfix48_En26
  wire signed [47:0] tapout_14;  // sfix48_En26
  wire signed [15:0] ZERO_OUT;  // sfix16_En11
  wire signed [47:0] tapout_15;  // sfix48_En26
  wire signed [15:0] dout_cast;  // sfix16_En11
  wire signed [15:0] muxOut;  // sfix16_En11
  reg signed [15:0] dout_1_re_1;  // sfix16_En11


  always @(posedge clk)
    begin : intdelay_process
      if (rst_n == 1'b0) begin
        intdelay_reg <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            intdelay_reg <= {3{1'b0}};
          end
          else begin
            intdelay_reg[0] <= dinRegVld;
            intdelay_reg[32'sd2:32'sd1] <= intdelay_reg[32'sd1:32'sd0];
          end
        end
      end
    end

  assign tapoutVld = intdelay_reg[2];

  assign addin = 48'sh000000000000;

  always @(posedge clk)
    begin : intdelay_1_process
      if (rst_n == 1'b0) begin
        intdelay_reg_1 <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          intdelay_reg_1[0] <= dinRegVld;
          intdelay_reg_1[1] <= intdelay_reg_1[0];
        end
      end
    end

  assign multVld = intdelay_reg_1[1];

  FilterTapWvldIn u_FTap_1 (.clk(clk),
                            .enb(enb),
                            .dinReg2_0_re(dinReg2_0_re),  // sfix16_En11
                            .coefIn_0(coefIn_0),  // sfix16_En15
                            .addin(addin),  // sfix48_En26
                            .multVld(multVld),
                            .syncReset(syncReset),
                            .tapout(tapout)  // sfix48_En26
                            );

  FilterTapWvldIn u_FTap_2 (.clk(clk),
                            .enb(enb),
                            .dinReg2_0_re(dinReg2_0_re),  // sfix16_En11
                            .coefIn_0(coefIn_1),  // sfix16_En15
                            .addin(tapout),  // sfix48_En26
                            .multVld(multVld),
                            .syncReset(syncReset),
                            .tapout(tapout_1)  // sfix48_En26
                            );

  FilterTapWvldIn u_FTap_3 (.clk(clk),
                            .enb(enb),
                            .dinReg2_0_re(dinReg2_0_re),  // sfix16_En11
                            .coefIn_0(coefIn_2),  // sfix16_En15
                            .addin(tapout_1),  // sfix48_En26
                            .multVld(multVld),
                            .syncReset(syncReset),
                            .tapout(tapout_2)  // sfix48_En26
                            );

  FilterTapWvldIn u_FTap_4 (.clk(clk),
                            .enb(enb),
                            .dinReg2_0_re(dinReg2_0_re),  // sfix16_En11
                            .coefIn_0(coefIn_3),  // sfix16_En15
                            .addin(tapout_2),  // sfix48_En26
                            .multVld(multVld),
                            .syncReset(syncReset),
                            .tapout(tapout_3)  // sfix48_En26
                            );

  FilterTapWvldIn u_FTap_5 (.clk(clk),
                            .enb(enb),
                            .dinReg2_0_re(dinReg2_0_re),  // sfix16_En11
                            .coefIn_0(coefIn_4),  // sfix16_En15
                            .addin(tapout_3),  // sfix48_En26
                            .multVld(multVld),
                            .syncReset(syncReset),
                            .tapout(tapout_4)  // sfix48_En26
                            );

  FilterTapWvldIn u_FTap_6 (.clk(clk),
                            .enb(enb),
                            .dinReg2_0_re(dinReg2_0_re),  // sfix16_En11
                            .coefIn_0(coefIn_5),  // sfix16_En15
                            .addin(tapout_4),  // sfix48_En26
                            .multVld(multVld),
                            .syncReset(syncReset),
                            .tapout(tapout_5)  // sfix48_En26
                            );

  FilterTapWvldIn u_FTap_7 (.clk(clk),
                            .enb(enb),
                            .dinReg2_0_re(dinReg2_0_re),  // sfix16_En11
                            .coefIn_0(coefIn_6),  // sfix16_En15
                            .addin(tapout_5),  // sfix48_En26
                            .multVld(multVld),
                            .syncReset(syncReset),
                            .tapout(tapout_6)  // sfix48_En26
                            );

  FilterTapWvldIn u_FTap_8 (.clk(clk),
                            .enb(enb),
                            .dinReg2_0_re(dinReg2_0_re),  // sfix16_En11
                            .coefIn_0(coefIn_7),  // sfix16_En15
                            .addin(tapout_6),  // sfix48_En26
                            .multVld(multVld),
                            .syncReset(syncReset),
                            .tapout(tapout_7)  // sfix48_En26
                            );

  FilterTapWvldIn u_FTap_9 (.clk(clk),
                            .enb(enb),
                            .dinReg2_0_re(dinReg2_0_re),  // sfix16_En11
                            .coefIn_0(coefIn_8),  // sfix16_En15
                            .addin(tapout_7),  // sfix48_En26
                            .multVld(multVld),
                            .syncReset(syncReset),
                            .tapout(tapout_8)  // sfix48_En26
                            );

  FilterTapWvldIn u_FTap_10 (.clk(clk),
                             .enb(enb),
                             .dinReg2_0_re(dinReg2_0_re),  // sfix16_En11
                             .coefIn_0(coefIn_9),  // sfix16_En15
                             .addin(tapout_8),  // sfix48_En26
                             .multVld(multVld),
                             .syncReset(syncReset),
                             .tapout(tapout_9)  // sfix48_En26
                             );

  FilterTapWvldIn u_FTap_11 (.clk(clk),
                             .enb(enb),
                             .dinReg2_0_re(dinReg2_0_re),  // sfix16_En11
                             .coefIn_0(coefIn_10),  // sfix16_En15
                             .addin(tapout_9),  // sfix48_En26
                             .multVld(multVld),
                             .syncReset(syncReset),
                             .tapout(tapout_10)  // sfix48_En26
                             );

  FilterTapWvldIn u_FTap_12 (.clk(clk),
                             .enb(enb),
                             .dinReg2_0_re(dinReg2_0_re),  // sfix16_En11
                             .coefIn_0(coefIn_11),  // sfix16_En15
                             .addin(tapout_10),  // sfix48_En26
                             .multVld(multVld),
                             .syncReset(syncReset),
                             .tapout(tapout_11)  // sfix48_En26
                             );

  FilterTapWvldIn u_FTap_13 (.clk(clk),
                             .enb(enb),
                             .dinReg2_0_re(dinReg2_0_re),  // sfix16_En11
                             .coefIn_0(coefIn_12),  // sfix16_En15
                             .addin(tapout_11),  // sfix48_En26
                             .multVld(multVld),
                             .syncReset(syncReset),
                             .tapout(tapout_12)  // sfix48_En26
                             );

  FilterTapWvldIn u_FTap_14 (.clk(clk),
                             .enb(enb),
                             .dinReg2_0_re(dinReg2_0_re),  // sfix16_En11
                             .coefIn_0(coefIn_13),  // sfix16_En15
                             .addin(tapout_12),  // sfix48_En26
                             .multVld(multVld),
                             .syncReset(syncReset),
                             .tapout(tapout_13)  // sfix48_En26
                             );

  FilterTapWvldIn u_FTap_15 (.clk(clk),
                             .enb(enb),
                             .dinReg2_0_re(dinReg2_0_re),  // sfix16_En11
                             .coefIn_0(coefIn_14),  // sfix16_En15
                             .addin(tapout_13),  // sfix48_En26
                             .multVld(multVld),
                             .syncReset(syncReset),
                             .tapout(tapout_14)  // sfix48_En26
                             );

  assign ZERO_OUT = 16'sb0000000000000000;

  FilterTapWvldIn u_FTap_16 (.clk(clk),
                             .enb(enb),
                             .dinReg2_0_re(dinReg2_0_re),  // sfix16_En11
                             .coefIn_0(coefIn_15),  // sfix16_En15
                             .addin(tapout_14),  // sfix48_En26
                             .multVld(multVld),
                             .syncReset(syncReset),
                             .tapout(tapout_15)  // sfix48_En26
                             );

  assign dout_cast = tapout_15[30:15];

  assign muxOut = (tapoutVld == 1'b0 ? ZERO_OUT :
              dout_cast);

  always @(posedge clk)
    begin : intdelay_2_process
      if (rst_n == 1'b0) begin
        dout_1_re_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dout_1_re_1 <= 16'sb0000000000000000;
          end
          else begin
            dout_1_re_1 <= muxOut;
          end
        end
      end
    end

  assign dout_1_re = dout_1_re_1;

endmodule  // subFilter

