// -------------------------------------------------------------
// 
// File Name: hdlsrc\DUC\WaveformGen_block.v
// Created: 2025-04-03 15:54:05
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: WaveformGen_block
// Source Path: DUC/AM_MultiBaseband_module/Carry2/Carrier_2/WaveformGen
// Hierarchy Level: 3
// Model version: 3.93
// 
// Wave form Generation Component
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module WaveformGen_block
          (clk,
           rst_n,
           enb,
           phaseIdx,
           sine);


  input   clk;
  input   rst_n;
  input   enb;
  input   [12:0] phaseIdx;  // ufix13_E15
  output  signed [15:0] sine;  // sfix16_En15


  reg [12:0] phaseIdxReg;  // ufix13_E15
  wire selsign;  // ufix1
  reg  [2:0] SelsignRegister_reg;  // ufix1 [3]
  wire selsignreg;  // ufix1
  wire [11:0] lutaddrexd;  // ufix12
  wire addrOverFsin;  // ufix1
  reg  [2:0] AddrOverFsinRegister_reg;  // ufix1 [3]
  wire addrOverFsinreg;  // ufix1
  wire seladdr;  // ufix1
  wire [10:0] lutaddr1;  // ufix11
  wire [11:0] lutaddrmax;  // ufix12
  wire [12:0] subtractor_sub_temp;  // ufix13
  wire [12:0] subtractor_1;  // ufix13
  wire [12:0] subtractor_2;  // ufix13
  wire [10:0] lutaddr2;  // ufix11
  wire [10:0] lutaddrsin;  // ufix11
  wire signed [15:0] lutoutsin;  // sfix16_En15
  wire signed [15:0] ampOne;  // sfix16_En15
  wire signed [15:0] lutoutsin_ampOne;  // sfix16_En15
  wire signed [16:0] uminus_cast;  // sfix17_En15
  wire signed [16:0] uminus_cast_1;  // sfix17_En15
  wire signed [15:0] lutoutsin_ampOne_inv;  // sfix16_En15


  always @(posedge clk)
    begin : phaseIdxRegister_process
      if (rst_n == 1'b0) begin
        phaseIdxReg <= 13'b0000000000000;
      end
      else begin
        if (enb) begin
          phaseIdxReg <= phaseIdx;
        end
      end
    end

  // Sine sign selection signal
  assign selsign = phaseIdxReg[12];

  always @(posedge clk)
    begin : SelsignRegister_process
      if (rst_n == 1'b0) begin
        SelsignRegister_reg <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          SelsignRegister_reg[0] <= selsign;
          SelsignRegister_reg[32'sd2:32'sd1] <= SelsignRegister_reg[32'sd1:32'sd0];
        end
      end
    end

  assign selsignreg = SelsignRegister_reg[2];

  // Get extended LUT address for overflow handling
  assign lutaddrexd = phaseIdxReg[11:0];

  // Detect sine overflow
  assign addrOverFsin = lutaddrexd == 12'b100000000000;

  always @(posedge clk)
    begin : AddrOverFsinRegister_process
      if (rst_n == 1'b0) begin
        AddrOverFsinRegister_reg <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          AddrOverFsinRegister_reg[0] <= addrOverFsin;
          AddrOverFsinRegister_reg[32'sd2:32'sd1] <= AddrOverFsinRegister_reg[32'sd1:32'sd0];
        end
      end
    end

  assign addrOverFsinreg = AddrOverFsinRegister_reg[2];

  assign seladdr = phaseIdxReg[11];

  assign lutaddr1 = phaseIdxReg[10:0];

  // Map LUT address in correct phase
  assign lutaddrmax = 12'b100000000000;

  assign subtractor_1 = {1'b0, lutaddrmax};
  assign subtractor_2 = {2'b0, lutaddr1};
  assign subtractor_sub_temp = subtractor_1 - subtractor_2;
  assign lutaddr2 = subtractor_sub_temp[10:0];

  assign lutaddrsin = (seladdr == 1'b0 ? lutaddr1 :
              lutaddr2);

  LookUpTableGen_block u_SineWave_inst (.clk(clk),
                                        .rst_n(rst_n),
                                        .enb(enb),
                                        .lutaddr(lutaddrsin),  // ufix11
                                        .lutoutput(lutoutsin)  // sfix16_En15
                                        );

  assign ampOne = 16'sb0111111111111111;

  // Assign sine amplitude One
  assign lutoutsin_ampOne = (addrOverFsinreg == 1'b0 ? lutoutsin :
              ampOne);

  assign uminus_cast = {lutoutsin_ampOne[15], lutoutsin_ampOne};
  assign uminus_cast_1 =  - (uminus_cast);
  assign lutoutsin_ampOne_inv = uminus_cast_1[15:0];

  // Select sign of Sine output
  assign sine = (selsignreg == 1'b0 ? lutoutsin_ampOne :
              lutoutsin_ampOne_inv);

endmodule  // WaveformGen_block

