############## clock and reset define##################
#create_clock -period 20.000 [get_ports sys_clk]
#set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
#set_property PACKAGE_PIN U18 [get_ports sys_clk]

##############J11 on ax7020 #############################
set_property PACKAGE_PIN F17 [get_ports {da1_data[13]}]
set_property PACKAGE_PIN F16 [get_ports {da1_data[12]}]
set_property PACKAGE_PIN F20 [get_ports {da1_data[11]}]
set_property PACKAGE_PIN F19 [get_ports {da1_data[10]}]
set_property PACKAGE_PIN G20 [get_ports {da1_data[9]}]
set_property PACKAGE_PIN G19 [get_ports {da1_data[8]}]
set_property PACKAGE_PIN H18 [get_ports {da1_data[7]}]
set_property PACKAGE_PIN J18 [get_ports {da1_data[6]}]
set_property PACKAGE_PIN L20 [get_ports {da1_data[5]}]
set_property PACKAGE_PIN L19 [get_ports {da1_data[4]}]
set_property PACKAGE_PIN M20 [get_ports {da1_data[3]}]
set_property PACKAGE_PIN M19 [get_ports {da1_data[2]}]
set_property PACKAGE_PIN K18 [get_ports {da1_data[1]}]
set_property PACKAGE_PIN K17 [get_ports {da1_data[0]}]
set_property PACKAGE_PIN J19 [get_ports {da1_wrt[0]}]
set_property PACKAGE_PIN K19 [get_ports {da1_clk[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_wrt[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_clk[0]}]



#set_property IOSTANDARD LVCMOS33 [get_ports {da2_clk[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {da2_wrt[0]}]
#set_property PACKAGE_PIN H20 [get_ports {da2_clk[0]}]
#set_property PACKAGE_PIN J20 [get_ports {da2_wrt[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[0]}]
#set_property PACKAGE_PIN L17 [get_ports {da2_data[13]}]
#set_property PACKAGE_PIN L16 [get_ports {da2_data[12]}]
#set_property PACKAGE_PIN M18 [get_ports {da2_data[11]}]
#set_property PACKAGE_PIN M17 [get_ports {da2_data[10]}]
#set_property PACKAGE_PIN D20 [get_ports {da2_data[9]}]
#set_property PACKAGE_PIN D19 [get_ports {da2_data[8]}]
#set_property PACKAGE_PIN E19 [get_ports {da2_data[7]}]
#set_property PACKAGE_PIN E18 [get_ports {da2_data[6]}]
#set_property PACKAGE_PIN G18 [get_ports {da2_data[5]}]
#set_property PACKAGE_PIN G17 [get_ports {da2_data[4]}]
#set_property PACKAGE_PIN H17 [get_ports {da2_data[3]}]
#set_property PACKAGE_PIN H16 [get_ports {da2_data[2]}]
#set_property PACKAGE_PIN G15 [get_ports {da2_data[1]}]
#set_property PACKAGE_PIN H15 [get_ports {da2_data[0]}]


set_property PACKAGE_PIN M14 [get_ports {led1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led1[0]}]

set_property PACKAGE_PIN M14 [get_ports {gpio_led_tri_o[0]}]
set_property PACKAGE_PIN M15 [get_ports {gpio_led_tri_o[1]}]
set_property PACKAGE_PIN K16 [get_ports {gpio_led_tri_o[2]}]
set_property PACKAGE_PIN J16 [get_ports {gpio_led_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led_tri_o[0]}]
