// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\DUC_1\AM_Modulator.v
// Created: 2024-10-30 21:09:17
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1.6276e-07
// Target subsystem base rate: 1.6276e-07
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1.6276e-07
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// AM_Modulated_data_out         ce_out        1.6276e-07
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: AM_Modulator
// Source Path: DUC_1/AM_Modulator
// Hierarchy Level: 0
// Model version: 3.20
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module AM_Modulator
          (clk,
           reset,
           clk_enable,
           Data_in,
           ce_out,
           AM_Modulated_data_out);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] Data_in;  // sfix16_En15
  output  ce_out;
  output  signed [15:0] AM_Modulated_data_out;  // sfix16_En14


  wire enb;
  reg signed [15:0] Delay_out1;  // sfix16_En15
  wire signed [7:0] Constant_out1;  // sfix8_En7
  reg signed [7:0] Delay1_out1;  // sfix8_En7
  wire signed [23:0] m_sin_2_pi_fm_t_mul_temp;  // sfix24_En22
  wire signed [15:0] m_sin_2_pi_fm_t_out1;  // sfix16_En15
  wire signed [7:0] Constant1_out1;  // int8
  wire signed [23:0] alpha1_m_sin_2_pi_fm_t_add_cast;  // sfix24_En15
  wire signed [23:0] alpha1_m_sin_2_pi_fm_t_add_cast_1;  // sfix24_En15
  wire signed [23:0] alpha1_m_sin_2_pi_fm_t_add_temp;  // sfix24_En15
  wire signed [15:0] alpha1_m_sin_2_pi_fm_t_out1;  // sfix16_En14
  wire Constant2_out1;
  wire signed [15:0] NCO_out1;  // sfix16_En2
  wire signed [31:0] Ec_1_m_sin_2_pi_fm_t_sin_2_pi_fc_t_mul_t;  // sfix32_En16
  wire signed [15:0] Ec_1_m_sin_2_pi_fm_t_sin_2_pi_fc_t_out1;  // sfix16_En14


  assign enb = clk_enable;

  always @(posedge clk)
    begin : Delay_rsvd_process
      if (reset == 1'b0) begin
        Delay_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= Data_in;
        end
      end
    end
  assign Constant_out1 = 8'sb01100110;
  always @(posedge clk)
    begin : Delay1_process
      if (reset == 1'b0) begin
        Delay1_out1 <= 8'sb00000000;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= Constant_out1;
        end
      end
    end
  assign m_sin_2_pi_fm_t_mul_temp = Delay_out1 * Delay1_out1;
  assign m_sin_2_pi_fm_t_out1 = m_sin_2_pi_fm_t_mul_temp[22:7];
  assign Constant1_out1 = 8'sb00000001;
  assign alpha1_m_sin_2_pi_fm_t_add_cast = {{8{m_sin_2_pi_fm_t_out1[15]}}, m_sin_2_pi_fm_t_out1};
  assign alpha1_m_sin_2_pi_fm_t_add_cast_1 = {Constant1_out1[7], {Constant1_out1, 15'b000000000000000}};
  assign alpha1_m_sin_2_pi_fm_t_add_temp = alpha1_m_sin_2_pi_fm_t_add_cast + 
    alpha1_m_sin_2_pi_fm_t_add_cast_1;
  assign alpha1_m_sin_2_pi_fm_t_out1 = alpha1_m_sin_2_pi_fm_t_add_temp[16:1];
  assign Constant2_out1 = 1'b1;
  NCO NCO_1_1 (.clk(clk),
               .reset(reset),
               .enb(clk_enable),
               .validIn(Constant2_out1),
               .sine(NCO_out1)  // sfix16_En2
               );
  assign Ec_1_m_sin_2_pi_fm_t_sin_2_pi_fc_t_mul_t = alpha1_m_sin_2_pi_fm_t_out1 * NCO_out1;
  assign Ec_1_m_sin_2_pi_fm_t_sin_2_pi_fc_t_out1 = Ec_1_m_sin_2_pi_fm_t_sin_2_pi_fc_t_mul_t[17:2];
  assign AM_Modulated_data_out = Ec_1_m_sin_2_pi_fm_t_sin_2_pi_fc_t_out1;

  assign ce_out = clk_enable;

endmodule  // AM_Modulator

