vlib work
vlog  DUC_module_tc.v
vlog  FilterCoef.v
vlog  FilterTapSystolicPreAddWvlIn.v
vlog  subFilter.v
vlog  Filter.v
vlog  CIC_Compensation.v
vlog  CIC_COMP_system.v
vlog  FilterCoef_block.v
vlog  FilterTapSystolicPreAddWvlIn_block.v
vlog  FilterTapSystolicWvldInC0.v
vlog  subFilter_block.v
vlog  Filter_block.v
vlog  Halfband.v
vlog  HB_system.v
vlog  FirRdyLogic.v
vlog  SimpleDualPortRAM_generic.v
vlog  Addressable_Delay_Line.v
vlog  Addressable_Delay_Line_block.v
vlog  Addressable_Delay_Line_block1.v
vlog  Addressable_Delay_Line_block2.v
vlog  FilterTapSystolicPreAdd.v
vlog  Lowpass.v
vlog  LP_system.v
vlog  DitherGen.v
vlog  Lookup_Table.v
vlog  LookUpTableGen.v
vlog  WaveformGen.v
vlog  NCO.v
vlog  NCO_system.v
vlog  CIC_Interpolation.v
vlog  DUC_module.v
