// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\DUC_1\DUC_AM_tc.v
// Created: 2024-09-18 10:50:58
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DUC_AM_tc
// Source Path: DUC_AM_tc
// Hierarchy Level: 1
// 
// Master clock enable input: clk_enable
// 
// enb         : identical to clk_enable
// enb_1_1_1   : identical to clk_enable
// enb_1_16_0  : 16x slower than clk with last phase
// enb_1_16_1  : 16x slower than clk with phase 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DUC_AM_tc
          (clk,
           reset,
           clk_enable,
           enb,
           enb_1_1_1,
           enb_1_16_0,
           enb_1_16_1);


  input   clk;
  input   reset;
  input   clk_enable;
  output  enb;
  output  enb_1_1_1;
  output  enb_1_16_0;
  output  enb_1_16_1;


  reg [3:0] count16;  // ufix4
  wire comp_0_tmp;
  wire phase_0_tmp;
  reg  phase_0;
  wire enb_1_16_0_1;
  wire comp_1_tmp;
  wire phase_1_tmp;
  reg  phase_1;
  wire enb_1_16_1_1;


  assign enb = clk_enable;

  assign enb_1_1_1 = clk_enable;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 15
  always @(posedge clk or negedge reset)
    begin : counter_16_process
      if (reset == 1'b0) begin
        count16 <= 4'b0001;
      end
      else begin
        if (clk_enable) begin
          count16 <= count16 + 4'b0001;
        end
      end
    end

  assign comp_0_tmp = count16 == 4'b1111;

  assign phase_0_tmp = comp_0_tmp & clk_enable;

  always @(posedge clk or negedge reset)
    begin : phase_delay_process
      if (reset == 1'b0) begin
        phase_0 <= 1'b0;
      end
      else begin
        if (clk_enable) begin
          phase_0 <= phase_0_tmp;
        end
      end
    end

  assign enb_1_16_0_1 = phase_0 & clk_enable;

  assign enb_1_16_0 = enb_1_16_0_1;

  assign comp_1_tmp = count16 == 4'b0000;

  assign phase_1_tmp = comp_1_tmp & clk_enable;

  always @(posedge clk or negedge reset)
    begin : phase_delay_1_process
      if (reset == 1'b0) begin
        phase_1 <= 1'b1;
      end
      else begin
        if (clk_enable) begin
          phase_1 <= phase_1_tmp;
        end
      end
    end

  assign enb_1_16_1_1 = phase_1 & clk_enable;

  assign enb_1_16_1 = enb_1_16_1_1;

endmodule  // DUC_AM_tc

