// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\DUC_1\Filter_block.v
// Created: 2024-10-28 22:01:09
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Filter_block
// Source Path: DUC_1/DUC_module/HB_system/Halfband/Filter
// Hierarchy Level: 3
// Model version: 3.18
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Filter_block
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           syncReset,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En14
  input   validIn;
  input   syncReset;
  output  signed [15:0] dataOut;  // sfix16_En14
  output  validOut;


  reg  dinRegVld;
  reg signed [15:0] dinReg_0_re;  // sfix16_En14
  reg signed [15:0] dinReg2_0_re;  // sfix16_En14
  wire signed [15:0] CoefOut_0;  // sfix16_En14
  wire signed [15:0] CoefOut_2;  // sfix16_En14
  wire signed [15:0] CoefOut_4;  // sfix16_En14
  wire signed [15:0] CoefOut_6;  // sfix16_En14
  wire signed [15:0] CoefOut_8;  // sfix16_En14
  wire signed [15:0] CoefOut_9;  // sfix16_En14
  reg  dinReg2Vld;
  wire signed [15:0] dout_1_re;  // sfix16_En14
  wire doutVld;


  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b0) begin
        dinRegVld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinRegVld <= 1'b0;
          end
          else begin
            dinRegVld <= validIn;
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b0) begin
        dinReg_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_re <= dataIn;
            end
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b0) begin
        dinReg2_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_re <= dinReg_0_re;
            end
          end
        end
      end
    end

  FilterCoef_block CoefTable_1_1 (.CoefOut_0(CoefOut_0),  // sfix16_En14
                                  .CoefOut_2(CoefOut_2),  // sfix16_En14
                                  .CoefOut_4(CoefOut_4),  // sfix16_En14
                                  .CoefOut_6(CoefOut_6),  // sfix16_En14
                                  .CoefOut_8(CoefOut_8),  // sfix16_En14
                                  .CoefOut_9(CoefOut_9)  // sfix16_En14
                                  );

  always @(posedge clk)
    begin : intdelay_3_process
      if (reset == 1'b0) begin
        dinReg2Vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2Vld <= 1'b0;
          end
          else begin
            dinReg2Vld <= dinRegVld;
          end
        end
      end
    end

  subFilter_block subFilter_1_re_1 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                    .coefIn_0(CoefOut_0),  // sfix16_En14
                                    .coefIn_2(CoefOut_2),  // sfix16_En14
                                    .coefIn_4(CoefOut_4),  // sfix16_En14
                                    .coefIn_6(CoefOut_6),  // sfix16_En14
                                    .coefIn_8(CoefOut_8),  // sfix16_En14
                                    .coefIn_9(CoefOut_9),  // sfix16_En14
                                    .dinRegVld(dinReg2Vld),
                                    .syncReset(syncReset),
                                    .dout_1_re(dout_1_re),  // sfix16_En14
                                    .doutVld(doutVld)
                                    );

  assign dataOut = dout_1_re;

  assign validOut = doutVld;

endmodule  // Filter_block

