// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\DUC_1\Lowpass.v
// Created: 2024-10-30 21:09:53
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Lowpass
// Source Path: DUC_1/DUC_module/LP_system/Lowpass
// Hierarchy Level: 2
// Model version: 3.20
// 
// Discrete FIR Filter
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Lowpass
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En14
  input   validIn;
  output  signed [15:0] dataOut;  // sfix16_En14
  output  validOut;


  wire signed [15:0] coeff;  // sfix16_En14
  wire haltProcess;
  wire signed [15:0] dinSM;  // sfix16_En14
  wire dinVldSM;
  reg [2:0] nextDelayLineRdAddrReverse;  // ufix3
  reg [2:0] rdCountReverse_1;  // ufix3
  reg [2:0] nextDelayLineWrAddr;  // ufix3
  reg [2:0] wrCount_1;  // ufix3
  reg [2:0] nextDelayLineRdAddr;  // ufix3
  reg [2:0] rdCount_1;  // ufix3
  reg [2:0] nextSharingCount;  // ufix3
  reg [2:0] sharingCount_1;  // ufix3
  reg  delayLineValidInP;
  reg  lastPhaseStrobe;
  reg  delayLineShiftEnP;
  reg  delayLineShiftEn1_1;
  wire syncResetRst;
  reg  delayLineShiftEn2_1;
  reg  delayLineShiftEn3_1;
  reg  [6:0] validOutLookahead_reg;  // ufix1 [7]
  wire validOutLookahead_1;
  reg  vldOut_1;
  wire notValid;
  reg [2:0] rdAddr0_1;  // ufix3
  reg [2:0] rdAddr1;  // ufix3
  reg [2:0] rdAddr2;  // ufix3
  reg [2:0] rdAddr3;  // ufix3
  wire rdAddrEndNonZero;
  wire rdAddrEndZero;
  reg  [4:0] finalSumValidPipe_reg;  // ufix1 [5]
  wire accumulate;
  wire signed [32:0] accDataOut;  // sfix33_En29
  reg [2:0] wrAddrP;  // ufix3
  reg [2:0] rdAddrDelayLine0;  // ufix3
  wire signed [15:0] delayLineEnd0;  // sfix16_En14
  wire signed [15:0] delayLineDataOut0;  // sfix16_En14
  reg signed [15:0] delayLineDataIn1_1;  // sfix16_En14
  reg [2:0] wrAddr1;  // ufix3
  reg [2:0] rdAddrDelayLine1;  // ufix3
  wire signed [15:0] delayLineEnd1;  // sfix16_En14
  wire signed [15:0] delayLineDataOut1;  // sfix16_En14
  reg signed [15:0] delayLineDataIn2_1;  // sfix16_En14
  reg [2:0] wrAddr2;  // ufix3
  reg [2:0] rdAddrDelayLine2;  // ufix3
  wire signed [15:0] delayLineEnd2;  // sfix16_En14
  wire signed [15:0] delayLineDataOut2;  // sfix16_En14
  reg signed [15:0] delayLineDataIn3_1;  // sfix16_En14
  reg [2:0] wrAddr3;  // ufix3
  reg [2:0] rdAddReverse1;  // ufix3
  reg [2:0] rdAddReverse2;  // ufix3
  reg [2:0] rdAddReverse3;  // ufix3
  wire signed [15:0] delayLineEnd3;  // sfix16_En14
  wire signed [15:0] delayLineDataOut3;  // sfix16_En14
  reg signed [15:0] coeffTableOut2;  // sfix16_En15
  reg signed [15:0] coeffTableRegP2_1;  // sfix16_En15
  reg signed [15:0] coeffTableReg2_1;  // sfix16_En15
  wire signed [15:0] delayLineEnd4;  // sfix16_En14
  wire signed [15:0] delayLineDataOut4;  // sfix16_En14
  reg signed [15:0] coeffTableOut1;  // sfix16_En15
  reg signed [15:0] coeffTableRegP1_1;  // sfix16_En15
  reg signed [15:0] coeffTableReg1_1;  // sfix16_En15
  wire signed [15:0] delayLineEnd5deadOut;  // sfix16_En14
  wire signed [15:0] delayLineDataOut5;  // sfix16_En14
  reg signed [15:0] coeffTableOut0;  // sfix16_En15
  reg signed [15:0] coeffTableRegP0_1;  // sfix16_En15
  reg signed [15:0] coeffTableReg0_1;  // sfix16_En15
  wire signed [32:0] sumIn;  // sfix33_En29
  wire signed [32:0] sumOut;  // sfix33_En29
  wire signed [32:0] sumOut_0;  // sfix33_En29
  wire signed [32:0] sumOut_1;  // sfix33_En29
  reg signed [32:0] sumOutReg_1;  // sfix33_En29
  reg signed [32:0] accDataOut_1;  // sfix33_En29
  wire signed [32:0] accSwitchOut;  // sfix33_En29
  wire signed [32:0] accAdderOut;  // sfix33_En29
  wire signed [15:0] converterOut;  // sfix16_En14
  reg signed [15:0] dataOutRegIn;  // sfix16_En14
  reg signed [15:0] dout_re_1;  // sfix16_En14
  wire signed [15:0] dataZero;  // sfix16_En14
  reg [2:0] InputControl_out4_0;  // ufix3

  initial begin
    coeffTableRegP2_1 = 16'sb0000000000000000;
    coeffTableRegP1_1 = 16'sb0000000000000000;
    coeffTableRegP0_1 = 16'sb0000000000000000;
  end

  assign coeff = 16'sb0000000000000000;

  assign haltProcess = 1'b0;

  FirRdyLogic firRdyLogic_1_1 (.clk(clk),
                               .reset(reset),
                               .enb(enb),
                               .dinSwitch(dataIn),  // sfix16_En14
                               .dinVldSwitch(validIn),
                               .coeff(coeff),  // sfix16_En14
                               .haltProcess(haltProcess),
                               .dinSM(dinSM),  // sfix16_En14
                               .dinVldSM(dinVldSM)
                               );

  always @(posedge clk)
    begin : rdCountReverse_process
      if (reset == 1'b0) begin
        rdCountReverse_1 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdCountReverse_1 <= nextDelayLineRdAddrReverse;
        end
      end
    end

  always @(posedge clk)
    begin : wrCount_process
      if (reset == 1'b0) begin
        wrCount_1 <= 3'b000;
      end
      else begin
        if (enb) begin
          wrCount_1 <= nextDelayLineWrAddr;
        end
      end
    end

  always @(posedge clk)
    begin : rdCount_process
      if (reset == 1'b0) begin
        rdCount_1 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdCount_1 <= nextDelayLineRdAddr;
        end
      end
    end

  always @(posedge clk)
    begin : sharingCount_process
      if (reset == 1'b0) begin
        sharingCount_1 <= 3'b000;
      end
      else begin
        if (enb) begin
          sharingCount_1 <= nextSharingCount;
        end
      end
    end

  // Input control counter combinatorial logic
  always @(dinVldSM, rdCountReverse_1, rdCount_1, sharingCount_1, wrCount_1) begin
    delayLineValidInP = (sharingCount_1 == 3'b000) && (dinVldSM == 1'b1);
    lastPhaseStrobe = sharingCount_1 == 3'b100;
    if ((dinVldSM == 1'b1) || (sharingCount_1 > 3'b000)) begin
      if (sharingCount_1 == 3'b100) begin
        nextSharingCount = 3'b000;
      end
      else begin
        nextSharingCount = sharingCount_1 + 3'b001;
      end
    end
    else begin
      nextSharingCount = sharingCount_1;
    end
    if (dinVldSM == 1'b1) begin
      if (wrCount_1 == 3'b100) begin
        InputControl_out4_0 = 3'b000;
      end
      else begin
        InputControl_out4_0 = wrCount_1 + 3'b001;
      end
    end
    else begin
      InputControl_out4_0 = wrCount_1;
    end
    if ((rdCount_1 != InputControl_out4_0) || (dinVldSM == 1'b1)) begin
      if (rdCount_1 == 3'b000) begin
        nextDelayLineRdAddr = 3'b100;
      end
      else begin
        nextDelayLineRdAddr = rdCount_1 - 3'b001;
      end
    end
    else begin
      nextDelayLineRdAddr = rdCount_1;
    end
    if ((sharingCount_1 > 3'b000) || (dinVldSM == 1'b1)) begin
      if (sharingCount_1 == 3'b100) begin
        if (wrCount_1 == 3'b100) begin
          nextDelayLineRdAddrReverse = 3'b000;
        end
        else begin
          nextDelayLineRdAddrReverse = wrCount_1 + 3'b001;
        end
      end
      else if (rdCountReverse_1 == 3'b100) begin
        nextDelayLineRdAddrReverse = 3'b000;
      end
      else begin
        nextDelayLineRdAddrReverse = rdCountReverse_1 + 3'b001;
      end
    end
    else begin
      nextDelayLineRdAddrReverse = rdCountReverse_1;
    end
    nextDelayLineWrAddr = InputControl_out4_0;
  end

  always @(posedge clk)
    begin : delayLineShiftEn0_process
      if (reset == 1'b0) begin
        delayLineShiftEnP <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEnP <= lastPhaseStrobe;
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn1_process
      if (reset == 1'b0) begin
        delayLineShiftEn1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEn1_1 <= delayLineShiftEnP;
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn2_process
      if (reset == 1'b0) begin
        delayLineShiftEn2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn2_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn2_1 <= delayLineShiftEn1_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : delayLineShiftEn3_process
      if (reset == 1'b0) begin
        delayLineShiftEn3_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn3_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn3_1 <= delayLineShiftEn2_1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : validOutLookahead_process
      if (reset == 1'b0) begin
        validOutLookahead_reg <= {7{1'b0}};
      end
      else begin
        if (enb) begin
          validOutLookahead_reg[0] <= delayLineShiftEn3_1;
          validOutLookahead_reg[32'sd6:32'sd1] <= validOutLookahead_reg[32'sd5:32'sd0];
        end
      end
    end

  assign validOutLookahead_1 = validOutLookahead_reg[6];

  always @(posedge clk)
    begin : vldOut_process
      if (reset == 1'b0) begin
        vldOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          vldOut_1 <= validOutLookahead_1;
        end
      end
    end

  assign notValid =  ~ vldOut_1;

  always @(posedge clk)
    begin : rdAddr0_process
      if (reset == 1'b0) begin
        rdAddr0_1 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdAddr0_1 <= sharingCount_1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr0_2_process
      if (reset == 1'b0) begin
        rdAddr1 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdAddr1 <= rdAddr0_1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr1_1_process
      if (reset == 1'b0) begin
        rdAddr2 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdAddr2 <= rdAddr1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddr2_1_process
      if (reset == 1'b0) begin
        rdAddr3 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdAddr3 <= rdAddr2;
        end
      end
    end

  assign rdAddrEndNonZero = rdAddr3 != 3'b000;

  assign rdAddrEndZero =  ~ rdAddrEndNonZero;

  always @(posedge clk)
    begin : finalSumValidPipe_process
      if (reset == 1'b0) begin
        finalSumValidPipe_reg <= {5{1'b0}};
      end
      else begin
        if (enb) begin
          finalSumValidPipe_reg[0] <= rdAddrEndZero;
          finalSumValidPipe_reg[32'sd4:32'sd1] <= finalSumValidPipe_reg[32'sd3:32'sd0];
        end
      end
    end

  assign accumulate = finalSumValidPipe_reg[4];

  assign accDataOut = 33'sh000000000;

  always @(posedge clk)
    begin : wrAddr_process
      if (reset == 1'b0) begin
        wrAddrP <= 3'b000;
      end
      else begin
        if (enb) begin
          wrAddrP <= wrCount_1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine_process
      if (reset == 1'b0) begin
        rdAddrDelayLine0 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine0 <= rdCount_1;
        end
      end
    end

  Addressable_Delay_Line delayLine0_1 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dataIn(dinSM),  // sfix16_En14
                                       .wrEn(delayLineValidInP),
                                       .wrAddr(wrAddrP),  // ufix3
                                       .rdAddr(rdAddrDelayLine0),  // ufix3
                                       .delayLineEnd(delayLineEnd0),  // sfix16_En14
                                       .dataOut(delayLineDataOut0)  // sfix16_En14
                                       );

  always @(posedge clk)
    begin : delayLineDataIn1_process
      if (reset == 1'b0) begin
        delayLineDataIn1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn1_1 <= delayLineEnd0;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr0_process
      if (reset == 1'b0) begin
        wrAddr1 <= 3'b000;
      end
      else begin
        if (enb) begin
          wrAddr1 <= wrAddrP;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine0_1_process
      if (reset == 1'b0) begin
        rdAddrDelayLine1 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine1 <= rdAddrDelayLine0;
        end
      end
    end

  Addressable_Delay_Line delayLine1_1 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dataIn(delayLineDataIn1_1),  // sfix16_En14
                                       .wrEn(delayLineShiftEn1_1),
                                       .wrAddr(wrAddr1),  // ufix3
                                       .rdAddr(rdAddrDelayLine1),  // ufix3
                                       .delayLineEnd(delayLineEnd1),  // sfix16_En14
                                       .dataOut(delayLineDataOut1)  // sfix16_En14
                                       );

  always @(posedge clk)
    begin : delayLineDataIn2_process
      if (reset == 1'b0) begin
        delayLineDataIn2_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn2_1 <= delayLineEnd1;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr1_1_process
      if (reset == 1'b0) begin
        wrAddr2 <= 3'b000;
      end
      else begin
        if (enb) begin
          wrAddr2 <= wrAddr1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrDelayLine1_1_process
      if (reset == 1'b0) begin
        rdAddrDelayLine2 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine2 <= rdAddrDelayLine1;
        end
      end
    end

  Addressable_Delay_Line_block delayLine2_1 (.clk(clk),
                                             .reset(reset),
                                             .enb(enb),
                                             .dataIn(delayLineDataIn2_1),  // sfix16_En14
                                             .wrEn(delayLineShiftEn2_1),
                                             .wrAddr(wrAddr2),  // ufix3
                                             .rdAddr(rdAddrDelayLine2),  // ufix3
                                             .lutAddr(rdAddr2),  // ufix3
                                             .delayLineEnd(delayLineEnd2),  // sfix16_En14
                                             .dataOut(delayLineDataOut2)  // sfix16_En14
                                             );

  always @(posedge clk)
    begin : delayLineDataIn3_process
      if (reset == 1'b0) begin
        delayLineDataIn3_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn3_1 <= delayLineEnd2;
        end
      end
    end

  always @(posedge clk)
    begin : wrAddr2_1_process
      if (reset == 1'b0) begin
        wrAddr3 <= 3'b000;
      end
      else begin
        if (enb) begin
          wrAddr3 <= wrAddr2;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddrReverse0_process
      if (reset == 1'b0) begin
        rdAddReverse1 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdAddReverse1 <= rdCountReverse_1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse1_1_process
      if (reset == 1'b0) begin
        rdAddReverse2 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdAddReverse2 <= rdAddReverse1;
        end
      end
    end

  always @(posedge clk)
    begin : rdAddReverse2_1_process
      if (reset == 1'b0) begin
        rdAddReverse3 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdAddReverse3 <= rdAddReverse2;
        end
      end
    end

  Addressable_Delay_Line_block1 delayLine3_1 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn3_1),  // sfix16_En14
                                              .validIn(delayLineShiftEn3_1),
                                              .wrAddr(wrAddr3),  // ufix3
                                              .rdAddr(rdAddReverse3),  // ufix3
                                              .delayLineEnd(delayLineEnd3),  // sfix16_En14
                                              .dataOut(delayLineDataOut3)  // sfix16_En14
                                              );

  // Coefficient table for multiplier2
  always @(rdAddr2) begin
    case ( rdAddr2)
      3'b000 :
        begin
          coeffTableOut2 = 16'sb1111001100000101;
        end
      3'b001 :
        begin
          coeffTableOut2 = 16'sb1110100010101111;
        end
      3'b010 :
        begin
          coeffTableOut2 = 16'sb0010001111001100;
        end
      3'b011 :
        begin
          coeffTableOut2 = 16'sb0111010010111111;
        end
      3'b100 :
        begin
          coeffTableOut2 = 16'sb0000000000000000;
        end
      default :
        begin
          coeffTableOut2 = 16'sb0000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP2_process
      if (enb) begin
        coeffTableRegP2_1 <= coeffTableOut2;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg2_process
      if (reset == 1'b0) begin
        coeffTableReg2_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg2_1 <= coeffTableRegP2_1;
        end
      end
    end

  Addressable_Delay_Line_block2 delayLine4_1 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineEnd3),  // sfix16_En14
                                              .validIn(delayLineShiftEn2_1),
                                              .wrAddr(wrAddr2),  // ufix3
                                              .rdAddr(rdAddReverse2),  // ufix3
                                              .delayLineEnd(delayLineEnd4),  // sfix16_En14
                                              .dataOut(delayLineDataOut4)  // sfix16_En14
                                              );

  // Coefficient table for multiplier1
  always @(rdAddr1) begin
    case ( rdAddr1)
      3'b000 :
        begin
          coeffTableOut1 = 16'sb0000001111011110;
        end
      3'b001 :
        begin
          coeffTableOut1 = 16'sb1111110010100100;
        end
      3'b010 :
        begin
          coeffTableOut1 = 16'sb1111100100110100;
        end
      3'b011 :
        begin
          coeffTableOut1 = 16'sb0000011001101011;
        end
      3'b100 :
        begin
          coeffTableOut1 = 16'sb0000101111010111;
        end
      default :
        begin
          coeffTableOut1 = 16'sb0000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP1_process
      if (enb) begin
        coeffTableRegP1_1 <= coeffTableOut1;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg1_process
      if (reset == 1'b0) begin
        coeffTableReg1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg1_1 <= coeffTableRegP1_1;
        end
      end
    end

  Addressable_Delay_Line_block2 delayLine5_1 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineEnd4),  // sfix16_En14
                                              .validIn(delayLineShiftEn1_1),
                                              .wrAddr(wrAddr1),  // ufix3
                                              .rdAddr(rdAddReverse1),  // ufix3
                                              .delayLineEnd(delayLineEnd5deadOut),  // sfix16_En14
                                              .dataOut(delayLineDataOut5)  // sfix16_En14
                                              );

  // Coefficient table for multiplier0
  always @(rdAddr0_1) begin
    case ( rdAddr0_1)
      3'b000 :
        begin
          coeffTableOut0 = 16'sb0000000010010001;
        end
      3'b001 :
        begin
          coeffTableOut0 = 16'sb0000000100000010;
        end
      3'b010 :
        begin
          coeffTableOut0 = 16'sb1111111100100011;
        end
      3'b011 :
        begin
          coeffTableOut0 = 16'sb1111110111111110;
        end
      3'b100 :
        begin
          coeffTableOut0 = 16'sb0000000110111000;
        end
      default :
        begin
          coeffTableOut0 = 16'sb0000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP0_process
      if (enb) begin
        coeffTableRegP0_1 <= coeffTableOut0;
      end
    end

  always @(posedge clk)
    begin : coeffTableReg0_process
      if (reset == 1'b0) begin
        coeffTableReg0_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg0_1 <= coeffTableRegP0_1;
        end
      end
    end

  assign sumIn = 33'sh000000000;

  FilterTapSystolicPreAdd filterTap0_1 (.clk(clk),
                                        .enb(enb),
                                        .din_re(delayLineDataOut0),  // sfix16_En14
                                        .preAddIn(delayLineDataOut5),  // sfix16_En14
                                        .coeff(coeffTableReg0_1),  // sfix16_En15
                                        .sumIn(sumIn),  // sfix33_En29
                                        .sumOut(sumOut)  // sfix33_En29
                                        );

  FilterTapSystolicPreAdd filterTap1_1 (.clk(clk),
                                        .enb(enb),
                                        .din_re(delayLineDataOut1),  // sfix16_En14
                                        .preAddIn(delayLineDataOut4),  // sfix16_En14
                                        .coeff(coeffTableReg1_1),  // sfix16_En15
                                        .sumIn(sumOut),  // sfix33_En29
                                        .sumOut(sumOut_0)  // sfix33_En29
                                        );

  FilterTapSystolicPreAdd filterTap2_1 (.clk(clk),
                                        .enb(enb),
                                        .din_re(delayLineDataOut2),  // sfix16_En14
                                        .preAddIn(delayLineDataOut3),  // sfix16_En14
                                        .coeff(coeffTableReg2_1),  // sfix16_En15
                                        .sumIn(sumOut_0),  // sfix33_En29
                                        .sumOut(sumOut_1)  // sfix33_En29
                                        );

  always @(posedge clk)
    begin : sumOutReg_process
      if (reset == 1'b0) begin
        sumOutReg_1 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          sumOutReg_1 <= sumOut_1;
        end
      end
    end

  assign accSwitchOut = (accumulate == 1'b0 ? accDataOut_1 :
              accDataOut);

  assign accAdderOut = accSwitchOut + sumOutReg_1;

  always @(posedge clk)
    begin : accDataOut_2_process
      if (reset == 1'b0) begin
        accDataOut_1 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          accDataOut_1 <= accAdderOut;
        end
      end
    end

  assign converterOut = accDataOut_1[30:15];

  always @(posedge clk)
    begin : converterOutReg_process
      if (reset == 1'b0) begin
        dataOutRegIn <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          dataOutRegIn <= converterOut;
        end
      end
    end

  always @(posedge clk)
    begin : dout_re_process
      if (reset == 1'b0) begin
        dout_re_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && validOutLookahead_1) begin
          dout_re_1 <= dataOutRegIn;
        end
      end
    end

  assign dataZero = 16'sb0000000000000000;

  assign dataOut = (notValid == 1'b0 ? dout_re_1 :
              dataZero);

  assign validOut = vldOut_1;

endmodule  // Lowpass

