// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\DUC_1\LP_system.v
// Created: 2024-10-30 21:09:53
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LP_system
// Source Path: DUC_1/DUC_module/LP_system
// Hierarchy Level: 1
// Model version: 3.20
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LP_system
          (clk,
           reset,
           enb,
           LP_in,
           rst,
           LP_out,
           LP_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] LP_in;  // sfix16_En14
  input   rst;
  output  signed [15:0] LP_out;  // sfix16_En14
  output  LP_vld;


  wire [7:0] count_step;  // uint8
  wire [7:0] count_from;  // uint8
  wire [7:0] count_reset;  // uint8
  reg [7:0] HDL_Counter_out1;  // uint8
  wire [7:0] count;  // uint8
  wire need_to_wrap;
  wire [7:0] count_value;  // uint8
  wire [7:0] count_1;  // uint8
  wire [7:0] Constant1_out1;  // uint8
  wire Relational_Operator1_out1;
  wire signed [15:0] LP;  // sfix16_En14
  wire Lowpass_out2;
  reg signed [15:0] Delay_out1;  // sfix16_En14
  reg  Delay1_out1;


  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 63
  assign count_step = 8'b00000001;
  assign count_from = 8'b00000000;
  assign count_reset = 8'b00000000;
  assign count = HDL_Counter_out1 + count_step;
  assign need_to_wrap = HDL_Counter_out1 == 8'b00111111;
  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);
  assign count_1 = (rst == 1'b0 ? count_value :
              count_reset);
  always @(posedge clk)
    begin : HDL_Counter_process
      if (reset == 1'b0) begin
        HDL_Counter_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          HDL_Counter_out1 <= count_1;
        end
      end
    end
  assign Constant1_out1 = 8'b00111111;
  assign Relational_Operator1_out1 = HDL_Counter_out1 == Constant1_out1;
  Lowpass Lowpass_1_1 (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .dataIn(LP_in),  // sfix16_En14
                       .validIn(Relational_Operator1_out1),
                       .dataOut(LP),  // sfix16_En14
                       .validOut(Lowpass_out2)
                       );
  always @(posedge clk)
    begin : Delay_rsvd_process
      if (reset == 1'b0) begin
        Delay_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= LP;
        end
      end
    end
  assign LP_out = Delay_out1;

  always @(posedge clk)
    begin : Delay1_process
      if (reset == 1'b0) begin
        Delay1_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= Lowpass_out2;
        end
      end
    end
  assign LP_vld = Delay1_out1;

endmodule  // LP_system

